### ISSUE TITLE
Don't automatically enable Comment Mail upon activation

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#100]
![2015-06-22_20-21-48](https://cloud.githubusercontent.com/assets/53005/8296246/680919d6-191c-11e5-8b9d-f471eca7169a.png)

After installing Comment Mail (v150620) on my personal site (where I'm currently using StCR), I was a bit alarmed to see that Comment Mail was automatically enabled. This alarmed me because I knew that StCR + Comment Mail enabled at the same time was probably not a good idea, so I quickly disabled it.

I suggest we _don't_ automatically enable Comment Mail, ever. Even when StCR is _not_ installed or active, we shouldn't assume that a site owner is _ready_ to enable Comment Mail right from the start (they haven't even had the opportunity to configure it!). 

As we do with ZenCache, I suggest Comment Mail remain disabled when we first activate the plugin. Then we can show a Dashboard message that says something like "Comment Mail is not active! To review your configuration and enable Comment Mail, [click here](#)."

**Comment by jaswsinc** [comment]
@raamdev writes...
> I suggest we don't automatically enable Comment Mail, ever. Even when StCR is not installed or active, we shouldn't assume that a site owner is ready to enable Comment Mail right from the start (they haven't even had the opportunity to configure it!).

Agree :+1:

**Comment by jaswsinc** [comment]
Closing this. We no longer activate CM by default.

> Then we can show a Dashboard message that says something like "Comment Mail is not active! To review your configuration and enable Comment Mail, click here."

It's not worded in the exact way, but we already do provide a link which leads a site owner to the basic config. options for Comment Mail whenever it is activated. I think that will suffice.
