### ISSUE TITLE
Intro to "CAN-SPAM Compliance" option panel

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#101]
![2015-06-22_20-27-09](https://cloud.githubusercontent.com/assets/53005/8296346/87df3410-191d-11e5-8292-e3259fcb42e6.png)

The CAN-SPAM Compliance option panel does not (as of v150620) explain anything about what "CAN-SPAM Compliance" actually is, why it's necessary, or what it's doing inside Comment Mail.

We should write a little blurb that summarizes what CAN-SPAM Compliance actually is, why it's important, and what a site owner needs to know about it. The end of the paragraph can link to more info on CAN-SPAM Compliance.

Many site owners want to keep their email notifications as simple as possible, so they'll probably want to disable this or delete everything in the text box. We should explain upfront why that's probably not a good idea.

**Comment by jaswsinc** [comment]
:+1:

**Comment by jaswsinc** [comment]
KBA published here: http://comment-mail.com/kb-article/can-spam-compliance/

**Comment by jaswsinc** [comment]
Done.

![](https://www.filepicker.io/api/file/rqUC4auMT32N5Lmo5VjE#.png)
