### ISSUE TITLE
Suggestions for improving the Edit Subscription page (Front-End)

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#102]
![2015-06-22_18-33-36](https://cloud.githubusercontent.com/assets/53005/8294913/cc67a67c-190d-11e5-9f8b-6a243888ed0e.png)

## A

The "Post ID #" label is not very user-friendly (as of v150620). Nobody is going to remember posts by their ID#, not even site owners. When looking at a list of all the posts, the things that are most easily remembered are 1) the Post Title and 2) the date the post was published.

I feel the "Post ID #" label should be replaced with simply "Post" and that the drop-down box should use a format like "June 20th, 2015 - Hello Earthlings".

## B

The "If empty, you'll be subscribed to all comments" just feels very unintuitive. It's a drop-down box... how do you leave a drop-down box "empty"? (It took me forever to figure out there's a little X to clear the selection.) Instead, there should simply be a default option at the top of the list that says "--Subscribe to all Comments/Replies to this Post--". You shouldn't need to _clear_ anything.

As with the "Post ID#" issue I mentioned above, the "Comment ID#" means nothing to nobody (except maybe a developer working on Comment Mail). Also, while this may be more work than it's worth, adding clip of the first few words of each comment listed on that box would really help somebody trying to find the comment they want to subscribe to.

---

## What's the point of editing Post ID / Comment ID?

My honest feeling about this whole functionality (the ability to change the post/comment you're subscribed to) makes absolutely no sense in my mind. The only thing someone should be able to do from this screen is edit meta information associated with an existing subscription.

When someone clicks "Edit" on an existing subscription (from My Subscriptions list), the Post Name and Comment ID they're subscribed to should be static and unchangeable and they should ONLY be able to edit the following information: 

![2015-06-22_20-53-32](https://cloud.githubusercontent.com/assets/53005/8296639/f33557e6-1920-11e5-86a3-cd2046144bdc.png)

**NOTE: I discovered a security issue related to this feature (the ability to edit Post ID / Comment ID), <del>which I will be posting in a separate GitHub Issue.</del> See https://github.com/websharks/comment-mail/issues/103**

**Comment by raamdev** [comment]
The other reason it would make sense to get rid of the ability to edit the Post ID / Comment ID is that on a site with thousands of posts and thousands of comments (like my own), both of those fields becomes pretty much useless.

For example, I noticed on my site (where I have 1,700+ published posts and 11,000+ approved comments), the Post ID drop-down box doesn't even list anything--all I can do is type in a number. As a visitor to the site editing my subscription, how will I know the Post ID# of the post I want to change my subscription to? And with 1,700+ posts, it's simply impractical to list all of those in a drop-down box.

![2015-06-22_20-58-22](https://cloud.githubusercontent.com/assets/53005/8296720/2caa3c7a-1922-11e5-92ca-87634ef9d2e2.png)

**Comment by jaswsinc** [comment]
@raamdev writes...
> I feel the "Post ID #" label should be replaced with simply "Post" and that the drop-down box should use a format like "June 20th, 2015 - Hello Earthlings".

Agree :+1:

@raamdev writes...
> Instead, there should simply be a default option at the top of the list that says "--Subscribe to all Comments/Replies to this Post--". You shouldn't need to clear anything.

Agree :+1:

@raamdev writes...
> When someone clicks "Edit" on an existing subscription (from My Subscriptions list), the Post Name and Comment ID they're subscribed to should be static and unchangeable and they should ONLY be able to edit the following information:

Agree :+1:

**Comment by jaswsinc** [comment]
Referencing: http://harvesthq.github.io/chosen/

**Comment by jaswsinc** [comment]
Noting that not all posts have a title.

**Comment by jaswsinc** [comment]
Noting that on sites with thousands of posts, manual entry is needed (at this point, at least), and an ID is impossible for a user to know about.

**Comment by jaswsinc** [comment]
![](https://www.filepicker.io/api/file/rhyxrgumSTi7fie2t4Xr#.png)
![](https://www.filepicker.io/api/file/AWmkHSfvQN2tQeaDrbLn#.png)

**Comment by jaswsinc** [comment]
@raamdev Please review when you get a moment. I'll leave this open for now.

**Comment by jaswsinc** [comment]
Left to do...

- [] On the front-end; remove the ID number from each Post and only show this whenever a title is not available. Also consider post types.
- [] On the front-end; remove comment ID numbers.

**Comment by raamdev** [comment]
> Referencing: http://harvesthq.github.io/chosen/

What's this referencing? That's a broken link for me and the top level sub-domain leads to an unconfigured MAMP installation?

@jaswsinc Can you clarify all of the possible places someone might get to the "Add New Subscription" page?

**Comment by jaswsinc** [comment]
@raamdev writes...
> Referencing: http://harvesthq.github.io/chosen/
> What's this referencing? That's a broken link for me and the top level sub-domain leads to an unconfigured MAMP installation?

Hmm. Interesting. This link is working for me. It's the documentation on a jQuery plugin called Chosen, which is what powers the dropdown menus that present the list of Posts/Comments.

**Comment by jaswsinc** [comment]
@raamdev writes...
> Can you clarify all of the possible places someone might get to the "Add New Subscription" page?

- A visitor can access the Add New form by clicking the "subscribe without commenting" link, or by clicking to add a new subscription from their subscriptions summary page.
- A site owner can add a new subscription from the Dashboard.

**Comment by jaswsinc** [comment]
@raamdev writes...
> That's a broken link for me and the top level sub-domain leads to an unconfigured MAMP installation?

This link is pointing to a `gh-pages` branch on GitHub. So the fact that you're seeing a MAMP installation is somewhat concerning. I'm going to list the link in code, just in case the URL itself is somehow being manipulated: `http://harvesthq.github.io/chosen/`

See also: `https://github.com/harvesthq/chosen`

**Comment by jaswsinc** [comment]
I'm going to close this now, as I feel that all points have been covered, with the exception of the fork of this issue in https://github.com/websharks/comment-mail/issues/108, which is an edge case that we can take a closer look at soon.

**Comment by raamdev** [comment]
> the fact that you're seeing a MAMP installation is somewhat concerning.

Yes, definitely very strange (and concerning!). The link works fine now (points to the docs you mentioned), but it definitely _was not_ working when I tried it last night.
