### ISSUE TITLE
Security Issue: Edit Subscriptions allows subscribing to Private or Password-Protected posts

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#103]
(Tested as of v150620.)

As a visitor, when I'm editing my subscription, I can type in any Post ID# number in the field and then click in the "Comment ID# Field" to refresh the list of comments attached to that post.

![2015-06-22_20-58-22](https://cloud.githubusercontent.com/assets/53005/8296726/39d5a1aa-1922-11e5-99b8-ffcdf899ea37.png)

However, I can also do this even if the Post ID that I enter is marked as Private or Password Protected!

Note: I've confirmed that I can get a list of comments on the Private or Password Protected post simply by entering the Post ID # and refreshing the Comment ID # field, however I have not confirmed that I can actually subscribe and then receive any subsequent comments to that Private or Password Protected post (I assume that I probably can, which is a big security issue).

Related: https://github.com/websharks/comment-mail/issues/102

**Comment by raamdev** [comment]
@jaswsinc Note: I suggested in https://github.com/websharks/comment-mail/issues/102 that we change the Edit Subscription page so that it's not possible to modify the Post ID or Comment ID of an existing subscription. You agreed to that change in your reply comment. Making that change would make this security issue a moot point, as that would make it not be possible to change the Post ID / Comment ID of an existing subscription.

**Comment by jaswsinc** [comment]
Copy that. Thanks!

**Comment by jaswsinc** [comment]
```
<?php
print_r(get_post_stati(array('exclude_from_search' => FALSE)));
```

```
Array
(
    [publish] => publish
    [future] => future
    [draft] => draft
    [pending] => pending
    [private] => private
    [inherit] => inherit
)
```

**Comment by jaswsinc** [comment]
Confirming: `$sub_post->post_status !== 'publish'`
https://github.com/websharks/comment-mail/blob/150620/comment-mail/includes/classes/queue-processor.php#L444

Confirming: `$post->post_status !== 'publish'`
https://github.com/websharks/comment-mail/blob/150620/comment-mail/includes/classes/queue-processor.php#L486

Confirming: `in_array($post->post_type, array('revision', 'nav_menu_item'), TRUE)`
https://github.com/websharks/comment-mail/blob/150620/comment-mail/includes/classes/queue-processor.php#L489

**Comment by jaswsinc** [comment]
Confirming that password protected posts process subscriptions as they should.

**Comment by jaswsinc** [comment]
Confirming:

```
if(!$args['exclude_post_statuses'] && !is_admin()) // If not in an admin area.
					$args['exclude_post_statuses'] = array('future', 'draft', 'pending', 'private');
```

https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/classes/utils-markup.php#L369-L370

---

Confirming: `'exclude_password_protected' => !is_admin(),`

https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/classes/utils-markup.php#L356

**Comment by jaswsinc** [comment]
Security hardened. Thanks for the report!

**Comment by raamdev** [comment]
Awesome! Thanks!
