### ISSUE TITLE
Default sort order for Subscriptions table should be reverse chronological

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#104]
As of v150620, the default sort order for the Subscriptions table (**Comment Mail → Subscriptions**) is by Subscriber name:

![2015-06-22_21-20-26](https://cloud.githubusercontent.com/assets/53005/8296952/1d86f956-1925-11e5-89f0-eae2febceb09.png)

However, it would make far more sense to sort this table the same way the WordPress Comments table itself is sorted, in reverse chronological order (newest to oldest):

![2015-06-22_21-26-49](https://cloud.githubusercontent.com/assets/53005/8296982/786e0a94-1925-11e5-832c-330c0b598e9e.png)

**Comment by jaswsinc** [comment]
Done. Thanks!
