### ISSUE TITLE
Enable Built-In Template System by default

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#105]
At present (as of v150620), when Comment Mail is installed, activated, and then enabled, there's nothing that appears on the front-end (i.e., on the comment form) that allows Comment Mail to actually be used. In other words, a site owner feels lost ("what's wrong? what am I missing?"). It took me over a minute to 'discover' this "optional" section and find that I had to change this setting to enable the built-in template system:

![2015-06-22_21-36-23](https://cloud.githubusercontent.com/assets/53005/8297063/e62c3230-1926-11e5-9329-d71f8260ad5f.png)

This should be enabled by default. If I site owner discovers, after installing, activating, and enabling Comment Mail, that the default Comment Mail template does not work properly with their theme's comment form, _then_ they can come in and disable this option and/or customize it so that it works with their theme.

**Comment by jaswsinc** [comment]
Thanks for the heads up!

This particular option is named `comment_form_sub_template_enable` and it defaults to a value of `1` (enabled). However, if you install Comment Mail into a WordPress installation that was previously running StCR, we try to match your StCR configuration and this default value could be modified.

@raamdev @reedyseth Could you guys review this line and let me know if I have this wrong, of it the line is right, but the behavior should be modified to avoid confusion? See: https://github.com/websharks/comment-mail/blob/master/comment-mail/includes/stcr.php#L49

**Comment by Reedyseth** [comment]
> This should be enabled by default. If I site owner discovers, after installing, activating, and enabling Comment Mail, that the default Comment Mail template does not work properly with their theme's comment form

@raamdev @jaswsinc Totally agree, this is just like the `Virtual Management Page` on StCR, the same behavior describe on the option is the same as in StCR. Usually you only need to create your custom template when the Theme that you are using does not support virtual pages or need a cool page instead of the default created by the plugin. So yes I think it should be enable by default.

**Comment by jaswsinc** [comment]
@reedyseth @raamdev If I pull the value for this option:

```php
get_option('subscribe_reloaded_show_subscription_box')
```

and it is not a `1` or another boolean-ish true value, then the default checkbox template that appears in the comment form (i.e., to allow one to subscribe) should not appear? Do I have that right?

In other words, why would `get_option('subscribe_reloaded_show_subscription_box')` by empty? What reasons could there be for this?

**Comment by Reedyseth** [comment]
> In other words, why would get_option('subscribe_reloaded_show_subscription_box') by empty? What reasons could there be for this?

Yes it shouldn't appear, but if no value on `subscribe_reloaded_show_subscription_box` is added then the plugin will add it itself(https://github.com/Reedyseth/subscribe-to-comments-reloaded/blob/master/subscribe-to-comments-reloaded/subscribe-to-comments-reloaded.php#L114), which is not a good.

This is part of the old StCR code that needs a review, but if you set this to no on the options panel then the subscription box will not be visible, this means that only when the default `yes` value is set to `no`.

**Comment by raamdev** [comment]
> and it is not a 1 or another boolean-ish true value, then the default checkbox template that appears in the comment form (i.e., to allow one to subscribe) should not appear? Do I have that right?

Correct.

> This particular option is named comment_form_sub_template_enable and it defaults to a value of 1 (enabled). However, if you install Comment Mail into a WordPress installation that was previously running StCR, we try to match your StCR configuration and this default value could be modified.

Ah, I was not aware that's how it was working. In that case the current behavior sounds _correct_ to me. I was testing this on my personal site where I have `subscribe_reloaded_show_subscription_box` disabled (since I'm using a custom integration with my theme). So, it looks like Comment Mail did exactly what it should've done (i.e., it also disabled the automatic CM template insertion, making the assumption that I probably want to do a manual integration with my theme as I did with StCR).

> Could you guys review this line and let me know if I have this wrong. Or, if the line is right, but the behavior should be modified to avoid confusion? See: https://github.com/websharks/comment-mail/blob/master/comment-mail/includes/stcr.php#L49

That looks correct to me.

---

What would've helped me avoid this confusion was if Comment Mail _told me_ which settings it imported from StCR--something that basically listed [all of these StCR settings](https://github.com/websharks/comment-mail/blob/master/comment-mail/includes/stcr.php#L34-L43) that Comment Mail imports, along with links to each relevant section in the Comment Mail configuration so that I can review those imported settings. We have a GitHub issue open to track improving this: https://github.com/websharks/comment-mail/issues/97#issuecomment-114376618.

**Comment by raamdev** [comment]
I just confirmed that Comment Mail (v150620) enables the Built-In Template System by default when it's installed on a clean WordPress site (i.e., when it's not importing an existing setting from StCR).

![2015-06-23_15-45-50](https://cloud.githubusercontent.com/assets/53005/8315487/1b6d63e0-19bf-11e5-9fdf-f3bc6cd6af87.png)

I'm going to go ahead and close this issue, but @Reedyseth or @jaswsinc have anything to add, feel free to reopen. :-)

**Comment by Reedyseth** [comment]
> but @Reedyseth or @jaswsinc have anything to add, feel free to reopen. :-)

So far so good, so nothing else to add.
