### ISSUE TITLE
"Fatal Error" trying to reactivate StCR after installing Comment Mail

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#106]
## Steps to reproduce this bug

1. Install, activate, and enable StCR
1. Install, activate, and enable Comment Mail
1. Deactivate the StCR plugin
1. Enable the StCR plugin

## Expected Behavior 

StCR should reactivate, as it had no issue running alongside Comment Mail.

## Observed Behavior

![2015-06-22_21-43-26](https://cloud.githubusercontent.com/assets/53005/8297122/d1be5386-1927-11e5-9e77-8134037d2315.png)

**Comment by Reedyseth** [comment]
OK, I follow the steps and was able to replicate the issue. Let you know the findings.!!

**Comment by jaswsinc** [comment]
Referencing: https://github.com/websharks/comment-mail/blob/master/comment-mail/includes/stcr.php#L111

**Comment by jaswsinc** [comment]
I think we just need an `!is_admin()` check there, so that when a plugin is activated for the first time there is no collision.

**Comment by Reedyseth** [comment]
@jaswsinc I am debugging right now and is correct the CM declare the function first than StCR.

**Comment by jaswsinc** [comment]
Yep, I agree. CM is checking to see if it exists first, but when a plugin is activated from the Dashboard it loaded after the `init` hook. Thus, CM is operating under the wrong assumption in that particular case. If we add an `!is_admin()` check before creating that function override in CM it should resolve this.

**Comment by Reedyseth** [comment]
> If we add an !is_admin() check before creating that function override in CM it should resolve this.

Correct!, I just tested and it `!is_admin()` fixed it.

**Comment by jaswsinc** [comment]
@reedyseth Cool! Would it be possible for you to submit a Pull Request with the changes that corrected this on your side?

**Comment by Reedyseth** [comment]
> Would it be possible for you to submit a Pull Request with the changes that corrected this on your side?

I just push the branch with the commit, is it ok like this ? https://github.com/websharks/comment-mail/tree/bug/%23106

**Comment by jaswsinc** [comment]
@Reedyseth writes...
> I just push the branch with the commit, is it ok like this ? https://github.com/websharks/comment-mail/tree/bug/%23106 and then make the pull request ?

That worked. Thanks again!

In the future, if you can submit your Pull Request with the "base" branch set to `000000-dev` that would be helpful. I think that a recent change I made in our default branch might have caused your PR to be submitted against `master` instead. Anyway, if you see that happen again in the future, please change it to `000000-dev` if you think about it.

![](https://www.filepicker.io/api/file/DHbUjCSmQCaH7krB55Gx#.png)

**Comment by Reedyseth** [comment]
> In the future, if you can submit your Pull Request with the "base" branch set to 000000-dev that would be helpful.

Got it !

**Comment by raamdev** [comment]
@Reedyseth @jaswsinc Woohoo! Nice work collaborating on this. :-) Thanks!

**Comment by jaswsinc** [comment]
Agree :smile: Great to have @reedyseth helping us out here!

**Comment by Reedyseth** [comment]
Thank you @raamdev @jaswsinc , I was in a break with the babies, so I am glad to collaborate.
