### ISSUE TITLE
Error 400 (OAuth2 Error) after logging in using Google SSO Integration

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#110]
## Steps to reproduce this bug

1. Install, activate, and enable Comment Mail (using v150625)
2. Follow instructions on KB article on how to setup Google [SSO Integration](http://comment-mail.com/kb-article/sso-integration/)
3. Add Callback URL on Google Dev Console as provided on the [Comment Mail Demo site's Dashboard](https://demos.websharks-inc.com/comment-mail/wp-admin/admin.php?page=comment_mail)
4. Go back to [Blog post](http://demos.websharks-inc.com/comment-mail/hello-earthlings/) and try to log in using the Google SSO integration

![screen shot 2015-06-26 at 1 17 46 am](https://cloud.githubusercontent.com/assets/7514953/8361073/78f8bf56-1ba3-11e5-8800-13db7a944238.png)

## Expected behaviour 

User should be able to log in to Google account and reply to the blog post.

## Observed behaviour

Getting this error after providing login details.

![screen shot 2015-06-26 at 1 18 43 am](https://cloud.githubusercontent.com/assets/7514953/8361139/e3c1f6d6-1ba3-11e5-85d6-259f818be9df.png)

**Comment by raamdev** [comment]
@kristineds I was unable to reproduce this bug. I followed all of the steps outlined in the [Google SSO Integration](http://comment-mail.com/kb-article/sso-integration/#-google) section of the KB Article and then upon testing logging in via Google from the Comment Form, a WordPress account was automatically created for me and I was logged in. Besides a few bumps (see https://github.com/websharks/comment-mail/issues/88#issuecomment-115464917), the process was seamless.

I did notice while following the Google SSO Integration instructions that there was a field that had a default URL inside it (`https://www.example.com/`) and I had to manually remove that from the field before clicking "Create Client ID"; that was not explained in the KB Article, so I'm wondering if you didn't clear that field when you set things up and that's maybe what's causing this issue?

![2015-06-25_21-59-00](https://cloud.githubusercontent.com/assets/53005/8369556/af6522b0-1b89-11e5-9d2e-ae468a87ba45.png)

**Comment by kristineds** [comment]
@raamdev : I cleared that field when setting it up. Just tried reproducing it now and it working perfectly.
What bugs me is that I tried this 3 times yesterday and it gave me that error. Anyway, I'm closing this issue now. Thanks for checking. :+1:

**Comment by jaswsinc** [comment]
@kristineds writes...
> I cleared that field when setting it up. Just tried reproducing it now and it working perfectly.
> 
> What bugs me is that I tried this 3 times yesterday and it gave me that error.

Good to know. If we get customers writing in with the same experience we might need to run further tests. Maybe there is some propagation time needed on the Google side of things. I have not seen that yet myself, but anything is possible.
