### ISSUE TITLE
Link to view subscriptions after StCR Import loads inside iFrame

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#111]
See screenshots below:

![2015-06-25_20-52-53](https://cloud.githubusercontent.com/assets/53005/8368736/52794e6c-1b7c-11e5-8a4a-58d0e81d60b7.png)
![2015-06-25_20-50-12](https://cloud.githubusercontent.com/assets/53005/8368737/5460eb90-1b7c-11e5-8b93-a55bab8f7651.png)

**Comment by jaswsinc** [comment]
Doh! haha... Great catch. TY
