### ISSUE TITLE
Expose important Config. Options sub-sections on Dashboard sidebar menu 

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#112]
The **Import/Export**, **Email Templates**, and **Site Templates** sub-sections inside the Config. Options panel are not clearly visible and they're easy to miss when you're not already familiar with the Comment Mail interface.

I strongly suggest that we add these three important sections as sub-menus directly on the Dashboard sidebar menu, as that will help make them stand out better and easier to find and access. These three sections (especially the **Email Templates** and **Site Templates**) as such important and vital (not to mention powerful) parts of the Comment Mail configuration that we should do everything we can to make sure site owners don't miss them.

![2015-06-25_21-13-05](https://cloud.githubusercontent.com/assets/53005/8368917/1be71c96-1b7f-11e5-9d52-4829821d7959.png)

---

![2015-06-25_21-06-24](https://cloud.githubusercontent.com/assets/53005/8368901/d3116b70-1b7e-11e5-9478-0c13c14ffe26.png)

---

![2015-06-25_21-15-58](https://cloud.githubusercontent.com/assets/53005/8368933/782028f4-1b7f-11e5-9c56-c7d1f344b7db.png)

---

![2015-06-25_21-05-50](https://cloud.githubusercontent.com/assets/53005/8368902/d4a097e0-1b7e-11e5-803e-31b75cdda192.png)

**Comment by jaswsinc** [comment]
Done! Thanks.
