### ISSUE TITLE
Facebook App Error: App not Setup (Still in Development Mode)

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#115]
### Steps to reproduce this bug
-------------------
1. Follow instructions on KB article on how to setup [Facebook SSO Integration](http://comment-mail.com/kb-article/sso-integration/#-facebook)
2. Reply to your blog post by logging in using Facebook

### Expected behaviour 
-----------------
- User should be able to reply to the blog post by logging in using own Facebook account
- KB article on setting up [Facebook SSO Integration](http://comment-mail.com/kb-article/sso-integration/#-facebook) should be updated to show how to disable the app in development mode and switch to public mode. 

##### Step 6: Disable Development mode
You will need to add a contact email for the Facebook app you just created. Select "Settings" in the left sidebar and provide a valid contact email.

![screen shot 2015-07-02 at 1 03 52 am](https://cloud.githubusercontent.com/assets/7514953/8613621/a7446826-2713-11e5-8494-cf9f685f2bdb.png)

Once your app is ready to be publicly available, you can now select "Status & Reviews" in the left sidebar and click on "Yes" to enable your app and all its live features.

![screen shot 2015-07-02 at 1 05 25 am](https://cloud.githubusercontent.com/assets/7514953/8613627/b183d812-2713-11e5-9860-19fd943a59f1.png)
---------

### Observed behaviour
---------
Getting this error after providing login details.

![screen shot 2015-07-02 at 1 00 56 am](https://cloud.githubusercontent.com/assets/7514953/8613950/5ca93fd6-2717-11e5-8a90-e8ac5385d5d8.png)

**Comment by jaswsinc** [comment]
@kristineds Excellent work on identifying this and documenting it. I'll try to update the KB article very soon. Thank you! Thank you!

**Comment by kristineds** [comment]
> Excellent work on identifying this and documenting it. I'll try to update the KB article very soon. Thank you! Thank you!

Glad to help! :+1:

**Comment by jaswsinc** [comment]
Next Release Changelog:

- (Comment Mail Pro) **Documentation Improvement:** The KB article that provides instructions for [setting up Facebook as a Comment Mail SSO Provider](http://comment-mail.com/kb-article/sso-integration/#-facebook) has been updated to include two additional steps. Props @kristineds. See also: [this GitHub issue](https://github.com/websharks/comment-mail/issues/115) if you'd like additional details.

**Comment by kristineds** [comment]
:+1:

**Comment by samirsamedov** [comment]
Thank you kristineds

**Comment by vaikutin** [comment]
Hi Thank you for the tip. I found the page design is updated. Here is latest at 27 Feb. 2017.

![facebookapppublic](https://cloud.githubusercontent.com/assets/25386704/23399754/129c85fe-fdaa-11e6-884d-8e926cb248f6.jpg)

**Comment by developerdiary** [comment]
Hi Team,

We make app live still getting development app error. 

Is any others setting we have to make in FB.

**Comment by otarazan** [comment]
I am also experiencing same issue. The app status in facebook is live. But when I try to login it says "App not setup"

**Comment by leonardocoutinho** [comment]
Same error for me

**Comment by parthdesai1208** [comment]
Same error I faced
My app is live but error says "This app is still in development mode and you don't have access to it"
