### ISSUE TITLE
Comment-Mail Email: UTF-8 "Branch Icon" Showing Up As Box

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail#116]
On the auto-sent email from Comment-Mail, a box appears next to the URL.

Please see screenshot : 
![image](https://cloud.githubusercontent.com/assets/13220018/8631975/7114b11a-27b9-11e5-8a83-30571f54e514.png)

Box appears next to url instead of Branch Icon which should look like this: 
![image](https://cloud.githubusercontent.com/assets/13220018/8631978/83b78a86-27b9-11e5-96fe-a4df4588d4f7.png)

Temporary Solutions from Jason:

- Check your system font to see if it is missing that UTF-8 glyph and perhaps update to a font that supports it.
- Or, alter the default Comment Mail template file that controls the Email Header. This is available in the Comment Mail config. options under "Email Templates".

**Comment by jaswsinc** [comment]
Thanks for reporting this compatibility issue! :-)

**Comment by raamdev** [comment]
I would vote for just removing that glyph from the default email template and let the site URL line up underneath the site title. I don't see that glyph adding much value here. 

More important than making the default email templates fancy is making them as widely-compatible as possible.

**Comment by jaswsinc** [comment]
> I don't see that glyph adding much value here.

:+1: Agree.

**Comment by jaswsinc** [comment]
# Next Actions

## Start a New Feature Branch

_These instructions assume that you've already done a `git clone`, so you already have a copy of both the Comment Mail and Comment Mail Pro repos on your system._

### Lite Version

```bash
$ cd ~/projects/websharks/comment-mail
$ git checkout 000000-dev # Start from the dev branch.
$ git pull # Make sure you have the most up-to-date copy.
$ git checkout -b feature/116 # New feature branch for this issue.
$ git status # Quick review. You should be on branch feature/116
```

### Pro Version

```bash
$ cd ~/projects/websharks/comment-mail-pro
$ git checkout 000000-dev # Start from the dev branch.
$ git pull # Make sure you have the most up-to-date copy.
$ git checkout -b feature/116 # New feature branch for this issue.
$ git status # Quick review. You should be on branch feature/116
```

---

## Make Changes

_I'm pointing you to lines in the code as it exists on GitHub. However, you should make these changes in the files on your own system; using your favorite editor._

### Lite Version

- Remove `&#42774;`; see https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/templates/type-s/email/snippet/header-tag.php#L8

### Pro Version

- Remove `&#42774;`; see https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/includes/templates/type-s/email/snippet/header-tag.php#L8

- Remove `&#42774;`; see https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/includes/templates/type-a/email/header-tag.php#L46

---

## Commit & Push To GitHub

### Lite Version

```bash
$ cd ~/projects/websharks/comment-mail
$ git status # Quick review. You should see the changed file appear in the list.
$ git add --all && git commit -m 'Removing incompatible branch icon entity. See: websharks/comment-mail#116'
$ git push -u origin feature/116
```

### Pro Version

```bash
$ cd ~/projects/websharks/comment-mail-pro
$ git status # Quick review. You should see the changed files appear in the list.
$ git add --all && git commit -m 'Removing incompatible branch icon entities. See: websharks/comment-mail#116'
$ git push -u origin feature/116
```

---

## Go to GitHub and submit Pull Requests

**Comment by jaswsinc** [comment]
Assigning this to @kristineds

**Comment by jaswsinc** [comment]
Awesome. Two PRs from @kristineds merged into the dev branch. Thanks! :-)

**Comment by kristineds** [comment]
> Awesome. Two PRs from @kristineds merged into the dev branch. Thanks! :-)

Cool!! :+1:

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Bug Fix**: Removed a UTF-8 "Branch Icon" in the default email templates that was not showing up properly in some email clients. Props @renzms @kristineds. See [Issue #116](https://github.com/websharks/comment-mail/issues/116).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Bug Fix**: Removed a UTF-8 "Branch Icon" in the default email templates that was not showing up properly in some email clients. Props @renzms @kristineds. See [Issue #116](https://github.com/websharks/comment-mail/issues/116).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#116).
