### ISSUE TITLE
Missing default translation file

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#118]
The Lite and Pro versions of the plugin are currently missing a default translation file (e.g., `includes/translations/comment-mail.pot`). We'll need to have that added so that users can start contributing translations into other languages.

**Comment by Li-An** [comment]
I agree with that :-)

**Comment by jaswsinc** [comment]
@kristineds Interested in learning how to generate the POT file for Comment Mail?

**Comment by kristineds** [comment]
> Interested in learning how to generate the POT file for Comment Mail?

Definitely. Count me in! Where should I start?

**Comment by jaswsinc** [comment]
# Prerequisites

- Create a directory on your system in a place where you want to keep tools like these. I suggest: `~/projects/websharks` (i.e., `/Users/kristine/projects/websharks`)

## Tools You'll Need

### Gettext Translation Utility

```bash
$ brew install gettext
$ brew link gettext --force
```

### WebSharks POT Generator for WordPress

```bash
$ git clone https://github.com/websharks/wp-i18n-tools ~/projects/websharks/wp-i18n-tools
```

---

## Repos You'll Need

```bash
$ git clone https://github.com/websharks/comment-mail ~/projects/websharks/comment-mail
$ git clone https://github.com/websharks/comment-mail-pro ~/projects/websharks/comment-mail-pro
```

---

## Branches You'll Need

You'll want to create two new "feature" branches that you can submit for review when you're done. Once you generate the POT translation files, you will open two Pull Requests on GitHub and request that your feature branches be merged with the latest development copy.

### Lite Version

```bash
$ cd ~/projects/websharks/comment-mail
$ git checkout 000000-dev # Start from the dev branch.
$ git pull # To be sure that you're working from the latest remote copy.
$ git checkout -b feature/118 # A feature branch for this GitHub issue number.
$ git status # Quick review. You should be on branch feature/118
```

### Pro Version

```bash
$ cd ~/projects/websharks/comment-mail-pro
$ git checkout 000000-dev # Start from the dev branch.
$ git pull # To be sure that you're working from the latest remote copy.
$ git checkout -b feature/118 # A feature branch for this GitHub issue number.
$ git status # Quick review. You should be on branch feature/118
```

---

## Generate the POT Translation Files

### Lite Version

```bash
$ mkdir ~/projects/websharks/comment-mail/comment-mail/includes/translations
$ ~/projects/websharks/wp-i18n-tools/makepot.php wp-plugin ~/projects/websharks/comment-mail/comment-mail ~/projects/websharks/comment-mail/comment-mail/includes/translations/comment-mail.pot
```

### Pro Version

```bash
$ mkdir ~/projects/websharks/comment-mail-pro/comment-mail-pro/includes/translations
$ ~/projects/websharks/wp-i18n-tools/makepot.php wp-plugin ~/projects/websharks/comment-mail-pro/comment-mail-pro ~/projects/websharks/comment-mail-pro/comment-mail-pro/includes/translations/comment-mail-pro.pot
```

---

## Commit and Push Changes to GitHub

## Lite Version

```bash
$ cd ~/projects/websharks/comment-mail
$ git status # Do a quick review. The POT file should be listed here.
$ git add --all && git commit -m 'Adding POT translation file.'
$ git push -u origin feature/118
```

## Pro Version

```bash
$ cd ~/projects/websharks/comment-mail-pro
$ git status # Do a quick review. The POT file should be listed here.
$ git add --all && git commit -m 'Adding POT translation file.'
$ git push -u origin feature/118
```

---

## Open Two Pull Requests on GitHub

If you make it this far on your own, you'll amaze me :-) Just let me know if you need any help. Once you get to this point I'll steer you through the Pull Requests in Slack. Or, if you run into any bumps just hit me on Slack too :-)

**Comment by jaswsinc** [comment]
@kristineds To submit your Pull Requests

## Lite Version

- Go to this page: https://github.com/websharks/comment-mail/branches
- Find your feature branch; i.e., `feature/118`
- Click "New Pull Request"
- Give it a title that references this issue; e.g., "POT; see: websharks/comment-mail#118"
- Give it a body that references this issue; e.g., "Closes websharks/comment-mail#118"
- Submit.

## Pro Version

- Go to this page: https://github.com/websharks/comment-mail-pro/branches
- Find your feature branch; i.e., `feature/118`
- Click "New Pull Request"
- Give it a title that references this issue; e.g., "POT; see: websharks/comment-mail#118"
- Give it a body that references this issue; e.g., "Closes websharks/comment-mail#118"
- Submit.

**Comment by jaswsinc** [comment]
:100: A+ for @kristineds ~ Two PRs merged. We now have POT translation files.

Lite version: https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/translations/comment-mail.pot

Pro version: https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/includes/translations/comment-mail-pro.pot

**Comment by kristineds** [comment]
> A+ for @kristineds ~ Two PRs merged. We now have POT translation files.

Woohoo!! :+1:

**Comment by Li-An** [comment]
OK, it's my turn to work...

**Comment by raamdev** [comment]
> A+ for @kristineds ~ Two PRs merged. We now have POT translation files.

Woohoo! Nice work @kristineds :-) Great documentation @jaswsinc!

> OK, it's my turn to work...

I'm looking forward to the French translation! :-)

**Comment by Li-An** [comment]
I have a question: what is exactly "overload property" ?

**Comment by jaswsinc** [comment]
> I have a question: what is exactly "overload property" ?

There are some parts of Comment Mail that contain errors that may occur in edge cases. It's generally OK to just skip these whenever you do a translation. For instance, if you find the line of code that contains translatable text, and it's just throwing a PHP Exception; i.e., `threw new \Except([translatable text here])`, you can just skip this if you like. Ideally, these will never be seen :-)

To answer your question though, see: http://php.net/manual/en/language.oop5.overloading.php

**Comment by Li-An** [comment]
Thanks for the tip. As the work is bigger than expected, it's a good idea to skip error messages much more interesting in english for developpers. 
I've found the link to php.net but the official french expression is "surcharge magique" that sounds... magical :-) ??? So the reason of my question.

**Comment by Li-An** [comment]
Some more questions - sorry I work slowly on the translation:
The Act Can concern only US residents ? If so, maybe you could add an option to desactivate this because it's perturbarting if not needed.

Found "Powered by Notes" ??

**Comment by jaswsinc** [comment]
> official french expression is "surcharge magique" that sounds... magical :-)

haha! Yeah, it sure does. I'd leave it in there. It sounds awesome! :smile: 

> Some more questions - sorry I work slowly on the translation:

Oh, no worries. I imagine it must be hard work.

> The Act Can concern only US residents ?

Are you referring to "overloading". Sorry, not sure I understand.

> Found "Powered by Notes" ??

The "Powered by Notes" are actually just a note at the bottom of the site and at the bottom of emails that Comment Mail sends. e.g., "Powered by Comment Mail". Also known as "branding", "supporting comment mail".

**Comment by raamdev** [comment]
> Are you referring to "overloading". Sorry, not sure I understand.

I think he's referring to the CAN-SPAM Act; is that applicable to U.S. Residents only? And if so, shouldn't non-US residents be able to disable it?

**Comment by Li-An** [comment]
Yes, sorry, I was referring to CAN-SPAM Act. Raamdev made it much clearer.

About "Powered by Notes": this will be the message shown in footer ? The exact message ? I was excepting for "Powered by Comment Mail" or "Powered by %s".

**Comment by jaswsinc** [comment]
> Yes, sorry, I was referring to CAN-SPAM Act. Raamdev made it much clearer.

I see. Thanks! :-) Yes, the CAN-SPAM Act is U.S. only and we will be working to make it possible for others to bypass this in the future, or perhaps reword this section later. You might give this a label of something like (in English): "Postal Address and Privacy Policy" and then translate.

---

> The exact message ? I was excepting for "Powered by Comment Mail" or "Powered by %s".

The `%s` is replaced with the name of the software automatically. So your translation should include the `%s`, but you can change the "Powered by" text in your translation.

**Comment by Li-An** [comment]
But I've got the sentence "Powered by Notes". So I will translate it into "Propulsé par Notes". But, what is "Notes" here ???

**Comment by jaswsinc** [comment]
Notes = a brief record of facts, topics, or thoughts, written down as an aid to memory.

i.e., Powered by Comment Mail

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Added the default translation file. Translators can now build translations using the default translation file located in `includes/translations/`. Props @kristineds. See [Issue #118](https://github.com/websharks/comment-mail/issues/118).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Added the default translation file. Translators can now build translations using the default translation file located in `includes/translations/`. Props @kristineds. See [Issue #118](https://github.com/websharks/comment-mail/issues/118).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#118).
