### ISSUE TITLE
CAN-SPAM U.S. Only (Allow Others to Disable)

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#122]
A fork of https://github.com/websharks/comment-mail/issues/118#issuecomment-123127046

**Comment by jaswsinc** [comment]
## Next Actions

## Prerequisites

This issue will require some basic knowledge of PHP. It will be a good learning experience. If you have any trouble editing the `menu-page.php` file referenced below, please ask for help on Slack :-)

## Start New Feature Branch

I'll assume whoever works on this knows how to do this. If you need help or have forgotten, please let me know. Remember that a feature branch should follow the issue number; e.g., `feature/122` for this issue.

## Make Changes

- Edit this section of the menu page for configuration options.
  - Lite version, see: https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/classes/menu-page.php#L263-L310
  - Pro version, same: https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/includes/classes/menu-page.php#L263-L310

### Remove references to CAN-SPAM which is U.S. only.

The idea here is that we want to rename the title of this panel. It currently reads, "CAN-SPAM Compliance", but we should remove references to the CAN-SPAM Act in favor of a more generalized approach that will be more internationally relevant.

![2015-07-23_05-49-21](https://cloud.githubusercontent.com/assets/1563559/8852073/99866c7a-30ff-11e5-8355-0bedb79b5b93.png)

## Commit Changes

```bash
$ git add --all && git commit -m 'Rename CAN-SPAM section. See: websharks/comment-mail#122'
```

## Push to GitHub

```bash
$ git push -u origin feature/122
```

## Submit Pull Requests

**Comment by kristineds** [comment]
Submitted PRs for [Comment Mail Lite](https://github.com/websharks/comment-mail/pull/126) and [Pro version](https://github.com/websharks/comment-mail-pro/pull/5).

**Comment by kristineds** [comment]
@jaswsinc Submitted PRs for  [Lite](https://github.com/websharks/comment-mail/pull/126) and [Pro version](https://github.com/websharks/comment-mail-pro/pull/5). with updated changes. Please review. :)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Removed references to "CAN-SPAM Act", which is a United States law that may not be understood or applicable to Comment Mail users outside of the United States. Props @Li-An and @kristineds. See [Issue #122](https://github.com/websharks/comment-mail/issues/122).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Removed references to "CAN-SPAM Act", which is a United States law that may not be understood or applicable to Comment Mail users outside of the United States. Props @Li-An and @kristineds. See [Issue #122](https://github.com/websharks/comment-mail/issues/122).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#122).
