### ISSUE TITLE
Missing Comment Mail Logo on list of plugins 

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#125]
If you search for **Comment Mail** in the [WordPress plugin directory](https://wordpress.org/plugins/), Comment Mail doesn't have a logo. It would be nice to have one so it is easier for potential customers to recognize it. 

![screen shot 2015-07-23 at 11 53 05 pm](https://cloud.githubusercontent.com/assets/7514953/8856916/6dde8c14-31a0-11e5-83d9-d27c654af3be.png)

**Comment by jaswsinc** [comment]
I was trying to get you access that you need to do this, but there seems to be a problem at WordPress.org at the moment. I'll come back to this later though :-)

**Comment by kristineds** [comment]
@jaswsinc Thanks! Will wait for it when you get a chance. :)

**Comment by jaswsinc** [comment]
@kristineds I went back to WordPress.org and tried this again. I can't seem to add you as a committer there yet. I keep getting an error that reads, "no user". It's almost like your WordPress.org profile is corrupted in some way. Strange!

If you get a chance, you might try updating your profile and/or resetting your WordPress.org password. Maybe after this I can try again and it will magically work (I hope). If not we might need to check with the WordPress.org team to see why I can't add you as a committer.

**Comment by kristineds** [comment]
@jaswsinc Just updated my profile and reset the WordPress.org password. Can you please try it again? :) Hopefully it works this time.

**Comment by jaswsinc** [comment]
No dice. How strange!

@raamdev Are you able to add `kristineds` as a Comment Mail Committer at WordPress.org?

Have you ever had a problem doing so in the past? I keep getting an empty response; i.e., no error, no nothing. The only indication I have that there's a problem is that I am redirected to a URL that ends with `?error=no-user`

**Comment by raamdev** [comment]
> Are you able to add kristineds as a Comment Mail Committer at WordPress.org?

I'm getting the same error as you. I just posted a question in WordPress Slack and will let you know what I hear.

**Comment by jaswsinc** [comment]
Cool. TY :-)

**Comment by raamdev** [comment]
@jaswsinc 
> Try "KristineDS" instead. Usernames are case sensitive

Using `KristineDS` worked. @kristineds is now a committer on WordPress.org for the Comment Mail plugin.

**Comment by raamdev** [comment]
Proper username case can be found on this profile page: https://wordpress.org/support/profile/kristineds

**Comment by jaswsinc** [comment]
Awesome. Thanks @raamdev!
~ @kristineds I'll come back to this soon.

**Comment by jaswsinc** [comment]
`icon-128x128.png`

![icon-128x128](https://cloud.githubusercontent.com/assets/1563559/8958821/96fdbedc-35b3-11e5-87db-1e9edf0cb1d2.png)

---

`icon-256x256.png`

![icon-256x256](https://cloud.githubusercontent.com/assets/1563559/8958822/96ff2204-35b3-11e5-8aa9-eaff37d06711.png)

**Comment by jaswsinc** [comment]
## Next Actions

## Checkout Subversion Repo from WordPress.org

```bash
$ svn checkout http://plugins.svn.wordpress.org/comment-mail/ ~/projects/websharks/comment-mail-wp
```

_**Note:** The `svn` command-line tool comes with OSX, so you should already have this. If you want the latest version run `brew install svn`. I just run the default version that comes with OSX though, as I don't use this tool much at all anyway. In fact, I only use it for WordPress.org repos._

---

## Add Icon Files to `/assets` Directory

- `~/projects/websharks/comment-mail-wp/assets/icon-128x128.png`
- `~/projects/websharks/comment-mail-wp/assets/icon-256x256.png`

---

## Commit Changes and Push to WordPress.org

```bash
$ cd ~/projects/websharks/comment-mail-wp
$ svn add assets/icon-* # Add icons to your commit.
$ svn commit -m 'Adding plugin icons; see: https://github.com/websharks/comment-mail/issues/125'
```

_**Note:** Unlike Git, with Subversion when you do a `commit -m` it automatically pushes changes to the repo; i.e., there is no separate `push` required._

---

## Wait for Propagation

Wait approx. 10 minutes and then check if the icons are showing up in areas where you'd expect to find them at WordPress.org and in the Dashboard.

**Comment by jaswsinc** [comment]
@kristineds Whenever you do `commit -m` you'll be asked for your WordPress.org username/password. Be sure to enter your username in the proper caSe; i.e., `KristineDS` ~ WordPress.org is picky.

**Comment by kristineds** [comment]
@jaswsinc I'm getting this error

```
Transmitting file data .svn: E195023: Commit failed (details follow):
svn: E195023: Changing file '/Users/kristineds/projects/websharks/comment-mail-wp/assets/icon-128x128.png' is forbidden by the server
svn: E175013: Access to '/!svn/txr/1209134-rbqx/comment-mail/assets/icon-128x128.png' forbidden
```

**Comment by kristineds** [comment]
@jaswsinc Confirming that Comment Mail logo has been added on the WordPress Plugin Lists

![screen shot 2015-07-31 at 11 51 42 pm](https://cloud.githubusercontent.com/assets/7514953/9011367/755ccf74-37df-11e5-8d81-ac3f827c82fa.png)

**Comment by jaswsinc** [comment]
Awesome! :-) I'd say this could be closed now. Nice work @kristineds

**Comment by kristineds** [comment]
Thanks! Closing this issue.
