### ISSUE TITLE
Add the text "Pro" on Comment Mail dashboard

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#131]
It would be nice to have the text **(Pro)** added after the word **Comment Mail** on the Dashboard so it is consistent with our other plugins like _s2Member_ when upgraded to the Pro version. It is also easier for users to determine if they're using the Pro version without having to check the Plugin list. 

#### Before:
![screen shot 2015-07-27 at 11 28 41 am](https://cloud.githubusercontent.com/assets/7514953/8898370/b972d7b8-3455-11e5-9519-bb2f6ab1781b.png)

#### After:
![screen shot 2015-07-27 at 11 52 02 am](https://cloud.githubusercontent.com/assets/7514953/8898391/1f4dc796-3456-11e5-87ba-557cea36c8ed.png)

**Comment by jaswsinc** [comment]
@kristineds I agree. That would be a nice touch!

The only problem I see is that it forces the line to wrap which is annoying; i.e., the name of the plugin is just a bit too long for us to fit ` (Pro)` on the end without forcing it to wrap--given the default width of this bar in the WordPress Dashboard.

Perhaps we could work on building a second variation of our SVG plugin icon. One that has a little "pro" overlay. That could be enabled to help indicate that it's the pro edition of the plugin. Thoughts on that?

**Comment by raamdev** [comment]
Another possibility: Add a `+` to indicate it's Comment Mail + all the Pro features:

![2015-07-27_17-01-07](https://cloud.githubusercontent.com/assets/53005/8917624/2842f616-3481-11e5-903d-57623a98f94b.png)

The Plugins list itself could still say "Comment Mail Pro"; the only place we'd use the `Comment Mail+` would be on the menu itself (for space reasons).

**Comment by kristineds** [comment]
@jaswsinc @raamdev Either one of your suggestions works for me. :) 
Here is what it looks like with the text *Pro* as a superscript

![screen shot 2015-07-28 at 11 03 29 pm](https://cloud.githubusercontent.com/assets/7514953/8934972/e37f3290-357c-11e5-837b-b1e4ad28977a.png)

**Comment by jaswsinc** [comment]
Love the superscript idea! Reducing the font size of that "Pro" label might make it even better.

Referencing: https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L1199

```
$_menu_title = $this->name.' <sup style="font-size:80%;">Pro</sup>';
```

If you can make that work and test it, I'd love to have a PR we can merge into the pro copy.

**Comment by raamdev** [comment]
> Here is what it looks like with the text Pro as a superscript

Brilliant! I love the superscript idea too.

> `<sup style="font-size:80%;`

I suggest using `75%`; `80%` has issues when actually using the menu:

## Superscript at 80%

![2015-07-28_13-59-59](https://cloud.githubusercontent.com/assets/53005/8939254/50b4c42a-3531-11e5-986b-cd9311af6950.png)
![2015-07-28_14-00-40](https://cloud.githubusercontent.com/assets/53005/8939256/53b2abc4-3531-11e5-8d81-5c8b1d90a423.png)

## Superscript at 75%

![2015-07-28_13-59-45](https://cloud.githubusercontent.com/assets/53005/8939258/590d8daa-3531-11e5-8456-0751098cd7aa.png)
![2015-07-28_14-01-21](https://cloud.githubusercontent.com/assets/53005/8939259/5a952598-3531-11e5-91c2-c76511de39a3.png)

**Comment by raamdev** [comment]
Also, adding the superscript pushes down the "Comment Mail" text:

![2015-07-28_14-16-34](https://cloud.githubusercontent.com/assets/53005/8939604/59acc300-3533-11e5-80c8-76746214e781.png)

So you'll need to add the following CSS tweak to get the alignment fixed:

 ```css
#toplevel_page_comment_mail div.wp-menu-name {
     padding-top: 3px;
}
```

![2015-07-28_14-15-15](https://cloud.githubusercontent.com/assets/53005/8939608/5f7cbb78-3533-11e5-91e3-95ce05304d3d.png)

**Comment by kristineds** [comment]
@raamdev @jaswsinc On what file can I add that CSS tweak? :) Is it this one? https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/client-s/css/menu-pages.css

**Comment by jaswsinc** [comment]
Let's see if you can get by without that, because the `menu-pages.css` file is not loaded for every admin page--only for pages that are for Comment Mail. I think if you set the `line-height` for the `<sup>` tag you can avoid this.

```
<sup style="font-size:60%; line-height:1;">Pro</sup>
```

**Comment by jaswsinc** [comment]
![2015-07-29_10-02-37](https://cloud.githubusercontent.com/assets/1563559/8965612/17d7ea94-35d9-11e5-87a1-b54a9d1bc019.png)

**Comment by raamdev** [comment]
> `<sup style="font-size:60%; line-height:1;">Pro</sup>`

Confirmed. That works great on my end too!

**Comment by kristineds** [comment]
Submitted PRs for CM [Lite](https://github.com/websharks/comment-mail/pull/133) and [Pro](https://github.com/websharks/comment-mail-pro/pull/9)

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Added a "Pro" label to the plugin name to clearly indicate when the Pro version of Comment Mail is installed. Props @kristineds. See [Issue #131](https://github.com/websharks/comment-mail/issues/131).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#131).
