### ISSUE TITLE
Remove ™ (trademark) symbol from WordPress.org Plugin Name

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#132]
We've all noticed these mysterious characters on WordPress.org:

![2015-07-29_13-14-50](https://cloud.githubusercontent.com/assets/53005/8964497/eff87fe6-35f3-11e5-8c8b-564a1015bf50.png)

I realized they must be related to the ™ trademark character we have at the end of "Comment Mail".

![2015-07-29_13-14-36](https://cloud.githubusercontent.com/assets/53005/8964793/a0bf8bde-35f5-11e5-9e5e-6927dac83dce.png)

I suggest we remove the trademark character from the plugin name on WordPress.org (e.g., from the top of the `readme.txt` file).

**Comment by jaswsinc** [comment]
:+1:

**Comment by jaswsinc** [comment]
@Reedyseth Interesting in tackling this one?

If so, please use the same technique as before. New branch `feature/132` for both lite and pro; and submit pull requests for a team review.

---

## Clone Repos Locally

_Skip this if you've already done it in the past._

```bash
$ git clone https://github.com/websharks/comment-mail ~/projects/websharks/comment-mail
$ git clone https://github.com/websharks/comment-mail-pro ~/projects/websharks/comment-mail-pro
```

---

## Start from a fresh dev branch...

```bash
$ cd ~/projects/websharks/comment-mail # Move to the repo directory.
$ git checkout 000000-dev # Always start from the dev branch.
$ git pull # Make sure you're working from the latest copy.
```

_Repeat for pro version._

---

## Start New Feature Branch for this Issue

```bash
$ git checkout -b feature/132 # New feature branch for issue number 132
```

_Repeat for pro version._

---

## Make Changes

Referencing:
- https://github.com/websharks/comment-mail/blob/150709/comment-mail/readme.txt#L1
- https://github.com/websharks/comment-mail/blob/150709/comment-mail/readme.txt#L15

_We could remove the ™ and ® symbols there as Raam noted above._

_Repeat for pro version._

---

## Commit and Push

```bash
$ git status # Quick check. You should be on the feature/132 branch.
$ git add --all && git commit -m 'Removing symbols; see: websharks/comment-mail#132'
$ git push -u origin feature/132
```

_Repeat for pro version._

## Open Pull Requests

- https://github.com/websharks/comment-mail/branches
- https://github.com/websharks/comment-mail-pro/branches

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting PRs for this issue
- websharks/comment-mail/pull/141
- websharks/comment-mail-pro/pull/15

**Comment by jaswsinc** [comment]
Great! Thanks for knocking that one out :-)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Bug Fix**: Fixed an issue with the plugin title showing odd characters on WordPress.org pages. Props @kristineds. See [Issue #132](https://github.com/websharks/comment-mail/issues/132).
