### ISSUE TITLE
3rd Party Plugin Compatibility: MailChimp for WordPress

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#134]
The [MailChimp for WordPress](https://wordpress.org/plugins/mailchimp-for-wp/) plugin should be tested for compatibility with Comment Mail. There's [a report](https://github.com/stcr/subscribe-to-comments-reloaded/issues/93) of issues running that plugin with StCR, so we should confirm the same issue does not exist with Comment Mail. 

Note that the issue may be related to a feature only available in [MailChimp for WordPress Pro](https://mc4wp.com/features/).

> I think I found the problem.
> It's about unchecking the Mailchimp field and selecting not to subscribe to new comments.
> 
> You can run the following test by yourself and if it's not working, we found the problem:
> Select not to subscribe.
> Uncheck the checkbox below.

---

> I think mail chimp has a hook that is is hijacking the one use by StCR, probably this one
> 
> `comment_post`

**Comment by renzms** [comment]
@raamdev Tested this with StCR, haven't experienced what was reported here: https://github.com/stcr/subscribe-to-comments-reloaded/issues/93

So it may only be occurring with Mailchimp for WordPress Pro like you said. I'll test some more and try with Comment Mail afterwards.

**Comment by raamdev** [comment]
@renzms Thanks! Note that this issue also needs to be tested _after_ the work on https://github.com/websharks/comment-mail/issues/114 has been merged in.

**Comment by raamdev** [comment]
@renzms Sorry, https://github.com/websharks/comment-mail/issues/114 has already been merged into `000000-dev`. So I should have said that MailChimp for WordPress + Comment Mail needs to be tested when the new MailChimp + Comment Mail integration (https://github.com/websharks/comment-mail/issues/114) is enabled.

**Comment by renzms** [comment]
@raamdev Ok, no worries! So once #114 is completed/enabled, I'll go ahead and get back to this one!

**Comment by raamdev** [comment]
> once #114 is completed/enabled, I'll go ahead and get back to this one!

It has already been merged into `000000-dev` so you can go ahead and test the dev branch.

**Comment by renzms** [comment]
@raamdev 

Tested with recent release, and I'm now experiencing what the user experienced here: https://github.com/stcr/subscribe-to-comments-reloaded/issues/93

Tested using 3 different emails.

When changing the option from the drop down to `no, do not subscribe` or leaving the options as `no, do not subscribe` the other subscribed emails no longer received notifications. I needed to comment again or go through `subscribe without commenting` again to receive the notifications for any updates for the other already subscribed email accounts.

____

Two other things I noticed:

1. When using `subscribe without commenting` and after registering and subscribing successfully, I clicked the link to view subscriptions and it gave me an error:

![testscreen](https://cloud.githubusercontent.com/assets/13220018/12046690/986e50e2-aef8-11e5-800d-20f2a6100973.png)

Should I open up a new bug report for that? Or is there something wrong in my configuration?

2. On a personal gmail email account, I didn't receiving any notifications at all from Comment-Mail(not even spam), but on the WebSharks gmail based account I used for testing it would sometimes appear in Spam, other times not. I think it only occurred when I had to re-subscribe after the `do not subscribe` option was used on another account for testing.

**Comment by raamdev** [comment]
@renzms writes...
> When changing the option from the drop down to no, do not subscribe or leaving the options as no, do not subscribe the other subscribed emails no longer received notifications. I needed to comment again or go through subscribe without commenting again to receive the notifications for any updates for the other already subscribed email accounts.

Interesting. Thanks for testing and sharing those details. It sounds like the MailChimp for WordPress plugin is hooking into some of the same areas of WordPress as Comment Mail and is possibly overriding Comment Mail in some scenarios.

Could you search the codebase for both plugins and find out which filters/actions both plugins are hooking into?

@renzms writes...
> When using subscribe without commenting and after registering and subscribing successfully, I clicked the link to view subscriptions and it gave me an error:

If you disable all plugins except Comment Mail, do you still have that issue? If so then yes, please open a new bug report with steps for reproducing.

@renzms writes...
> On a personal gmail email account, I didn't receiving any notifications at all from Comment-Mail(not even spam), but on the WebSharks gmail based account I used for testing it would sometimes appear in Spam, other times not. I think it only occurred when I had to re-subscribe after the do not subscribe option was used on another account for testing.

That sounds like issues with the SMTP configuration. You might try installing the WP-Mail-SMTP plugin and configuring it with your Gmail account so that all email is going through an authenticated SMTP server. (If you're testing Comment Mail Pro, you can use **Comment Mail → Config. Options → SMTP Server Integration**.)

**Comment by renzms** [comment]
@raamdev 

Ok I'll try to check on all these things.

On the old StCR, @Reedyseth mentioned that `comment_post` could be the culprit behind the bug, as MailChimp uses the same hool

**Comment by renzms** [comment]
@raamdev 

>If you disable all plugins except Comment Mail, do you still have that issue? If so then yes, please open a new bug report with steps for reproducing.

Disabled all plugins, confirmed working now as intended. Weird thing is, when I tried tracking down which plugin caused the error/conflict by enabling the plugins one by one and testing different combinations of plugins, the error didn't happen anymore. I have the same exact plugins enabled now and its working fine.

**Comment by raamdev** [comment]
@renzms Hmm, that's odd. Maybe try starting over from scratch with a clean WP install and install the MailChimp for WordPress plugin _first_, then install Comment Mail and see if you can reproduce it?

**Comment by renzms** [comment]
@raamdev 

That error was in regards to the Subscription List error, _that_ I cannot reproduce even in the clean installation. But the "`unsubscribe to comments` and it unsubscribes everyone from the thread" bug still occurs.

**Comment by raamdev** [comment]
> But the "unsubscribe to comments and it unsubscribes everyone from the thread" bug still occurs.

Can you provide me with a list of steps to reproduce this in a clean WP install?

**Comment by renzms** [comment]
@raamdev 
> Can you provide me with a list of steps to reproduce this in a clean WP install?

Sure thing,

###Steps to reproduce

- Install Mail Chimp and Comment Mail
- Setup Mail Chimp and Comment Mail
- Create a test post
- Test using different emails and try commenting in different ways, e.g. Reply, New Comment, etc
- Subscribe to comments using all test email accounts
- Comment again, but note which test account you used. When changing the option from the drop down to `no, do not subscribe` or leaving the options as `no, do not subscribe` the other subscribed emails no longer receive notifications. 


I needed to comment again or go through subscribe without commenting again to receive the notifications for any updates for the other already subscribed email accounts.

**Comment by jaswsinc** [comment]
I edited Renz's post above to correct this:

```
###Steps to reproduce
```

should be:

```
### Steps to reproduce
```

Referencing: https://daringfireball.net/projects/markdown/syntax#header

**Comment by raamdev** [comment]
@renzms writes...
> Steps to reproduce

Have you tried investigating what's causing this bug? Any ideas?

**Comment by renzms** [comment]
@raamdev 

Tested on Comment Mail Pro v160818/Comment Mail v160824 + MailChimp Version 4.0.4.

There no longer seems to be an issue. When commenting and unsubscribing/choosing `no, do not subscribe`, this does not seem to affect the other subscriptions.

**Comment by raamdev** [comment]
@renzms Thanks for confirming! I'll close this for now.
