### ISSUE TITLE
Test WP v4.3 WP_List_Table Changes

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#135]
See: https://make.wordpress.org/core/2015/08/08/list-table-changes-in-4-3/
~ We need to test Comment Mail against WordPress v4.3 to see if any changes are necessary. Comment Mail extends this class, so any changes to this class could cause a problem.

**Comment by raamdev** [comment]
@jaswsinc writes... 
> I think we can close this issue now, as I haven't seen any problems in recent releases of WordPress.
