### ISSUE TITLE
Bug: Multisite Uninstall

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#136]
## Overview

The uninstaller for Comment Mail should consider that each child blog in a network could have been running the Comment Mail plugin. For that reason, the uninstaller should attempt to iterate through each blog and apply the uninstall routines to each child blog in order to remove all traces.

Referencing: https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/classes/uninstaller.php#L52-L60

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Bug Fix**: Fixed a Multisite uninstallation bug that was preventing Comment Mail from taking Child Blogs into consideration when uninstalling, which was resulting in an incomplete uninstallation. See [Issue #136](https://github.com/websharks/comment-mail/issues/136).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Bug Fix**: Fixed a Multisite uninstallation bug that was preventing Comment Mail from taking Child Blogs into consideration when uninstalling, which was resulting in an incomplete uninstallation. See [Issue #136](https://github.com/websharks/comment-mail/issues/136).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#136).
