### ISSUE TITLE
Test WP v4.4 Comment Form Changes

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#146]
We need to test Comment Mail with the Comment Form changes coming in WP v4.4. See: https://make.wordpress.org/core/2015/09/25/changes-to-fields-output-by-comment_form-in-wordpress-4-4/

**Comment by jaswsinc** [comment]
In WP v4.4 the hooks have changed the location of the SSO login buttons and the Comment Subscription Options fields. I don't see a problem here, but the presentation has been altered slightly.

![2015-10-27_16-10-40](https://cloud.githubusercontent.com/assets/1563559/10776348/735e6a9a-7cc5-11e5-8451-26a456788d04.png)

**Comment by raamdev** [comment]
I suggest we move the Comment Mail Subscription Options to the bottom of those fields, just after **Website** and just before the **Post Comment** button. That would be in align with why these changes to the comment form layout were introduced in the first place (prioritize the Comment → Name → Email, followed by other fields/options).

It also makes sense that the CM options should come just before submitting the comment, as opposed to in between typing the comment and typing your name.

**Comment by jaswsinc** [comment]
Agree.

**Comment by jaswsinc** [comment]
## Next Actions (Pro Version)

- New feature branch in the `websharks/comment-mail-pro` repo.

- Comment out [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L702); i.e., leave it there, but please `// `comment it out.

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L702) add the following:

  ```php
  add_filter('comment_form_submit_field', array($this, 'comment_form_filter_prepend'), 5, 1);
  ```

  _Referencing: [hook in the WordPress core](https://github.com/WordPress/WordPress/blob/master/wp-includes/comment-template.php#L2278)_

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L2189) add the following:

  ```php
  /**
   * Comment form integration; via filter.
   *
   * @since 15xxxx Improving comment form compat.
   *
   * @attaches-to `comment_form_submit_field` filter.
   *
   * @param mixed $value Value passed in by a filter.
   *
   * @return mixed The `$value`; possibly filtered here.
   */
  public function comment_form_filter_prepend($value)
  {
  	if(!is_null($fired = &$this->static_key('comment_form')))
  		return $value; // We only handle this for a single hook.
  	// The first hook to fire this will win automatically.
  	if(is_string($value))
  	{
  		$fired = TRUE; // Flag as `TRUE` now.
  		ob_start(); // Output buffer.
  		new comment_form_after();
  		$value = ob_get_clean().$value;
  	}
  	return $value;
  }
  ```

- Test against WordPress v4.4 and post screenshot along with your PR.

---

## Next Actions (Lite Version)

- Repeat the same steps from above in the lite version please.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **WP v4.4 Compat.** This release improves compatibility with subtle changes to `comment_form_*` hooks in WordPress v4.4+. Props @kristineds and @raamdev. See also: [this GitHub issue](https://github.com/websharks/comment-mail/issues/146) if you'd like additional details.
