### ISSUE TITLE
Improve Color Scheme for Template to Enhance Readability

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#147]
Referencing:  https://wordpress.org/support/topic/two-suggestions-8?replies=1

------
> I must admit, though, that I have great difficulty reading the code sections for the templates. The colors just don't stand out enough against the black background. Could you, perhaps, experiment with some other color schemes to enhance readability?

-----

Templates referred to are the Email header/footer and Site templates. Perhaps something like this:
Color Scheme: [`#282A36, #DA5647, #F5AB55, #71DA8C, #57AFBD`]

![screen shot 2015-10-19 at 6 56 34 pm](https://cloud.githubusercontent.com/assets/7514953/10576410/a749f88c-7695-11e5-9961-61fcdb36aaa4.png)

**Comment by raamdev** [comment]
It would be nice to have a toggle somewhere that allows either changing the style, or just disabling syntax highlighting altogether. (Both would be ideal.)

**Comment by jaswsinc** [comment]
## Overview

This syntax highlighting is a feature provided (and themed by) CodeMirror. See [theme demos](https://codemirror.net/demo/theme.html) to experiment with other themes. See also: [this line of code in Comment Mail](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L1068) where the CodeMirror theme is loaded; i.e., to get a general sense of how this works in Comment Mail.

## Next Actions (Pro Version)

- New feature branch in the `websharks/comment-mail-pro` repo.

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L568) add a new option key.

  ```php
  'template_syntax_theme' => 'ambiance',
  ```

- Replace [this line of code](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L1068) with the following:

  ```php
  wp_enqueue_style('codemirror-'.$this->options['template_syntax_theme'].'-theme', set_url_scheme('//cdnjs.cloudflare.com/ajax/libs/codemirror/4.7.0/theme/'.urlencode($this->options['template_syntax_theme']).'.min.css'), array('codemirror'), NULL, 'all');
  ```

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/includes/classes/menu-page.php#L1668) add the following.

  ```php
  $_panel_body .= '<table>'.
                 '  <tbody>'.
                 $form_fields->select_row(
  	               array(
  		               'label'           => sprintf(__('Syntax Highlighting Theme', $this->plugin->text_domain), esc_html($this->plugin->name)),
  		               'placeholder'     => __('Select an Option...', $this->plugin->text_domain),
  		               'name'            => 'template_syntax_theme',
  		               'current_value'   => $current_value_for('template_syntax_theme'),
  		               'allow_arbitrary' => FALSE,
  		               'options'         => array(
  			               'ambiance'      => __('Ambiance', $this->plugin->text_domain),
  			               'base16-dark'   => __('Base 16 Dark', $this->plugin->text_domain),
                                       // add additional lines each for each of the available themes.
  		               ),
  		               'notes_after'     => '',
  	               )).
                 '  </tbody>'.
                 '</table>';
  ```

  Note that a select menu will be presented which allows a site owner to choose from any of the available `.min.css` theme files listed [here](https://cdnjs.com/libraries/codemirror/4.7.0).

  _You will need to modify the code snippet above to include all available theme options; i.e., add new options to the `'options'         => array` in the snippet below. The only two listed at the moment are `ambiance` (default) and `base16-dark`. There are many others to choose from._

  With the above in place, you should find that a new configurable option will appear here.

  ![2015-10-27_00-59-17](https://cloud.githubusercontent.com/assets/1563559/10753465/0468d0f0-7c46-11e5-91f5-d2a8cafb8794.png)

- Test your changes to be sure that is possible to change the syntax theme as expected.

- Submit PR.

## Next Actions (Lite Version)

- New feature branch in the `websharks/comment-mail` repo.

- In the `websharks/comment-mail` (lite variation) repo, after [this line](https://github.com/websharks/comment-mail/blob/150709/comment-mail/plugin.inc.php#L435) add the following:

  ```php
  'template_syntax_theme',
  ```

- After [this line](https://github.com/websharks/comment-mail/blob/150709/comment-mail/plugin.inc.php#L722) add a new option key.

  ```php
  'template_syntax_theme' => 'ambiance',
  ```

- Replace [this line of code](https://github.com/websharks/comment-mail/blob/150709/comment-mail/plugin.inc.php#L1215) with the following:

  ```php
  wp_enqueue_style('codemirror-'.$this->options['template_syntax_theme'].'-theme', set_url_scheme('//cdnjs.cloudflare.com/ajax/libs/codemirror/4.7.0/theme/'.urlencode($this->options['template_syntax_theme']).'.min.css'), array('codemirror'), NULL, 'all');
  ```

- Delete the existing [`menu-page.php` file](https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/classes/menu-page.php) in the lite version and replace it with an exact copy of the `menu-page.php` file that you worked on in the pro version; i.e., the one that now includes a new configurable option that allows you to choose a syntax theme.

  _Note that both the lite/pro versions can use the same `menu-page.php` file. The file will automatically adapt accordingly. This also allows for a pro preview in the lite version. The syntax theme will only be configurable in the pro version however._

- Test your changes to be sure that this option shows up in a pro preview in the lite version.

  ![2015-10-27_00-59-17](https://cloud.githubusercontent.com/assets/1563559/10753465/0468d0f0-7c46-11e5-91f5-d2a8cafb8794.png)

- Submit PR.

**Comment by jaswsinc** [comment]
@kristineds While working on this issue feel free to choose a different default theme if you find another that you feel would work better as a default syntax theme/style.

The current default is:

```php
'template_syntax_theme' => 'ambiance',
```

**Comment by jaswsinc** [comment]
Next Pro Release Changelog:

- (Comment Mail Pro) **Theme Syntax Highlighting:** This release makes it possible for the color-scheme used in template file syntax highlighting to be changed to any one of 30+ options. See: **Dashboard → Comment Mail → Config. Options → Template-Related Settings**. Props @kristineds. See also: [this GitHub issue](https://github.com/websharks/comment-mail/issues/147) if you'd like additional details.

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#147).
