### ISSUE TITLE
Add Ability to Auto-Subscribe Specific User Roles

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#148]
Referencing:  https://wordpress.org/support/topic/two-suggestions-8?replies=1

> I notice you provide some forms of auto-subscription. Could you add the ability to auto-subscribe specific user roles (including s2Member user roles, of course!)?

**Comment by raamdev** [comment]
Is this referring to auto-subscribe to the comments for a post? Or auto-subscribe to a specific mailing list?

**Comment by jaswsinc** [comment]
Possible short-term workaround:

![2015-10-20_06-46-49](https://cloud.githubusercontent.com/assets/1563559/10610935/67ad5046-76f6-11e5-8752-1c86a18295f0.png)

**Comment by KTS915** [comment]
@raamdev,

"Is this referring to auto-subscribe to the comments for a post? Or auto-subscribe to a specific mailing list?"

As I understand it, the current Auto-Subscribe feature (to which @jaswsinc has pointed in the graphic above) relates to all posts of a particular type. That is what I am looking for, but with functionality extended to user roles (including custom user roles), so that certain roles will automatically receive notification of any comments on such posts without the need for signing up first.

**Comment by raamdev** [comment]
@KTS915 I see. Thank you for the clarification! So an additional field that allows you to define a list of User Roles so that any users associated with those roles should automatically be subscribed to any posts of the post type listed in the "Auto-Subscribe Post Types" field, is that correct?

If so, I'm seeing a potential performance issue here. What if there were thousands of users associated with a role listed in the Auto-Subscribe Roles field? That would require Comment Mail to create a subscription for potentially thousands of users _every time a new post is created_. 

I'm not saying it's impossible, just sharing my thoughts. :-)

**Comment by KTS915** [comment]
@raamdev,

In those circumstances, I agree that there would be a performance issue. But I'd say that that is just something for the user to consider, perhaps prompted by a warning in the style that WebSharks often provides alongside options to select various functions in its plugins.

The sites for which I'm envisioning using this functionality are essentially intranets (which means there also won't be CAN-SPAM issues). They wouldn't typically have more than 100 users, so I don't think there would be a problem there. Or have I misunderstood the nature of the performance issue which you note?

Emails wouldn't be sent out whenever a post is created, would they? (That wouldn't be good.) So long as emails are sent only when a comment is made, that would be perfect.

**Comment by raamdev** [comment]
> Emails wouldn't be sent out whenever a post is created, would they? (That wouldn't be good.) So long as emails are sent only when a comment is made, that would be perfect.

Right, I wasn't referring to emails being sent out. (Comment Mail already has a queue system for that anyway, to handle large volumes of outgoing email.) I was referring to the fact that a new comments subscription for each user would need to be created in the database whenever a new post is created.

I'll wait for thoughts on performance issues from @jaswsinc. :-)

**Comment by jaswsinc** [comment]
> I was referring to the fact that a new comments subscription for each user would need to be created in the database whenever a new post is created

It could be, yes. However, it would take several hundred inserts for that to be a real concern. A few extra queue insertions to cover other roles should be just fine.

This is the [source file](https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/classes/sub-auto-injector.php) that will need to be updated. I'll come back to this soon! :-)

**Comment by jaswsinc** [comment]
## Next Actions (Pro Version)

- New feature branch in the `websharks/comment-mail-pro` repo.

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L440) add a new configurable option key.

  ```php
  'auto_subscribe_roles' => '', // Comma-delimited list of WP Roles.
  ```

- After [this line](https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/classes/sub-auto-injector.php#L182) add a new class member as follows:

  ```php
  /**
   * Injects users by role.
   *
   * @since 15xxxx Adding auto-subscribe roles.
   */
  protected function maybe_inject_users_by_role()
  {
    if(!$this->plugin->options['auto_subscribe_roles'])
      return; // Not applicable.
      
    $roles = $this->plugin->options['auto_subscribe_roles'];
    $roles = preg_split('/[;,\s]+/', $roles, NULL, PREG_SPLIT_NO_EMPTY);

    foreach($roles as $_role) // All users w/ any of these roles.
    {
      foreach(get_users('role='.$_role) as $_user)
      {
        if(!($_user instanceof \WP_User) || !$_user->user_email)
          continue; // Not applicable/possible.
          
        $_data = array(
          'post_id'    => $this->post->ID,
          'comment_id' => 0, // Subscribe to all comments.
          'deliver'    => $this->plugin->options['auto_subscribe_deliver'],
          'fname'      => $_user->first_name,
          'lname'      => $_user->last_name,
          'email'      => $_user->user_email,
          'status'     => 'subscribed',
        );
        new sub_inserter($_data, array(
          'process_events' => $this->process_events,
        ));
      }
      unset($_user, $_data); // Housekeeping.
    }
    unset($_role); // Housekeeping.
  }
  ```

- After [this line](https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/classes/sub-auto-injector.php#L109) add the following:

  ```php
  $this->maybe_inject_users_by_role();
  ```

- After [this line](https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/classes/menu-page.php#L528) add a new configurable option as follows:

   ```php
  ' <table>'.
  '    <tbody>'.
  $form_fields->input_row(
    array(
      'label'         => __('Auto-Subscribe the Following WordPress Roles:', $this->plugin->text_domain),
      'placeholder'   => __('e.g., administrator,editor,author,contributor', $this->plugin->text_domain),
      'name'          => 'auto_subscribe_roles',
      'current_value' => $current_value_for('auto_subscribe_roles'),
      'notes_after'   => '<p>'.__('You can enter a comma-delimited list of WordPress Roles; e.g., <code>administrator,editor,author,contributor</code>.', $this->plugin->text_domain).'</p>',
    )).
  '    </tbody>'.
  ' </table>'.
  ```

  You should find that it shows up here.

  ![2015-10-27_03-22-26](https://cloud.githubusercontent.com/assets/1563559/10756615/ffb18a0c-7c59-11e5-906a-a4cd72516d5e.png)

- Submit PR.

## Next Actions (Lite Version)

- New feature branch in the `websharks/comment-mail` repo.

- Repeat the steps above in the lite version, with the following exception:

  - You can skip the last step when working on the lite version. The `menu-page.php` file is identical for both the lite and pro versions. It will automatically adapt accordingly. So whenever you reach the very last step where you are making changes to the `menu-page.php` file, you can simply delete the existing `menu-page.php` in the lite version, and replace it with an exact copy of what you worked on as a part of the pro version—which should now include a text box where you can enter a comma-delimited list of WordPress Roles that should be auto-subscribed.

- Submit PR.

**Comment by jaswsinc** [comment]
_**Tip:** While working on this issue you can take note of the way that Constructors work in PHP. See: http://php.net/manual/en/language.oop5.decon.php_

_Notice [this line](https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/classes/sub-auto-injector.php#L83) in the code you're working on. Perhaps run some tests locally with sample code from the article at PHP to get a better sense of how Class Constructors work._

**Comment by renzms** [comment]
![comment mail config options renz s test area wordpress](https://github-cloud.s3.amazonaws.com/assets%2F13220018%2F10958579%2F9590be60-83aa-11e5-92e8-d24e494d39b0.jpg)

Submitting PR for Pro version.

**Comment by jaswsinc** [comment]
@renzms Woohoo!!!! :octocat:  That's fantastic. Love that feature.

Couple of minor enhancements I'd like to request... See screenshot.

![2015-11-04_18-46-47](https://cloud.githubusercontent.com/assets/1563559/10959419/b9cc56b2-8324-11e5-9ed0-f74b67bdcca2.png)

**Comment by KTS915** [comment]
@renzms, @jaswsinc,

This looks great! I am looking forward to testing it out!

**Comment by renzms** [comment]
![comment mail config options renz s test area wordpress 1](https://cloud.githubusercontent.com/assets/13220018/10988119/8e5166ac-8474-11e5-9be4-4a4fbd9be3fb.jpg)

@KTS915 Thanks!

@jaswsinc Will that do?

**Comment by jaswsinc** [comment]
@renzms Yes! That's just about got it.

Here's what you have now...

> A list of WordPress roles can be provided, allowing you to auto-subscribe other WordPress Roles to every post automatically.

I suggest the following changes:

- Capitalize "Roles" in this context.
- Link the first instance of "WordPress Roles" to [this page](https://codex.wordpress.org/Roles_and_Capabilities).
- Change the wording slightly, as seen below.

---

A list of [WordPress Roles](https://codex.wordpress.org/Roles_and_Capabilities) can be provided, allowing you to auto-subscribe all users who have one of those Roles, to every post automatically.

**Comment by jaswsinc** [comment]
@KTS915 You can grab yourself a free copy of Comment Mail Pro using coupon code: `KTS915`. Good for you only. I'd love to hear any feedback that you have. Free [checkout here](https://comment-mail.com/checkout/?type=unlimited&s2-ssl=yes&s2p-coupon=KTS915).

Once you get signed up over at comment-mail.com, you can also visit this page to join our beta list, and that way you'll get an early copy of the beta software that we are working on here: https://comment-mail.com/beta-testers/

**Comment by KTS915** [comment]
@jaswsinc,

Wow, thanks very much! That's very generous of you. I have just signed up.

**Comment by jaswsinc** [comment]
It's the least we can do. I'm looking forward to a day when you might consider working with us :-) I think I speak for everyone on our team when I say that we _really_ appreciate everything that do for the community, and that we all value your feedback and contributions here at GitHub as well.

**Comment by KTS915** [comment]
Well, that's very nice of you. I'm not sure what you have in mind, but if you'd like to talk via email, I'd be happy to do that.

**Comment by jaswsinc** [comment]
Cool. That would be great. If you can send your contact info to `devs` %at% `websharks-inc.com` I will get back to you.

**Comment by renzms** [comment]
![comment mail config options renz s test area wordpress 2](https://cloud.githubusercontent.com/assets/13220018/10988851/23ceeee2-847b-11e5-9a36-afaa3169ebbe.jpg)

Submitting PRs (Lite and Pro)

**Comment by jaswsinc** [comment]
Next Release Changelog:

- (Comment Mail/Comment Mail Pro) **Auto-Subscribe Roles:** This release makes it possible to auto-subscribe specific user Roles in WordPress, to every post automatically. Props @renzms and @KTS915.  See also: [this GitHub issue](https://github.com/websharks/comment-mail/issues/148) if you'd like additional details.

**Comment by raamdev** [comment]
@jaswsinc @renzms We should clarify this new Auto-Subscribe Roles feature a bit more in the description. Right now it says:

> - A list of WordPress roles can be provided, allowing you to auto-subscribe all users who have one of those Roles, to every post automatically.

However, that sentence leaves me with several questions: Does "auto-subscribe all users who have one of those Roles, to every post automatically" mean that all users with those roles will immediately have a subscription to every post created, even for existing posts? (I assume not, but that's not clear to me because "allowing **you** to auto-subscribe all users" makes it sound like I'm somehow auto-subscribing all users.) 

I suggest changing it to the following to improve clarity (emphasis mine; I woun:

> - A list of WordPress roles can be provided. All users who have one of the listed Roles will be auto-subscribed to all comments/replies for every new post automatically.

**Comment by jaswsinc** [comment]
> A list of WordPress roles can be provided. All users who have one of the listed Roles will be auto-subscribed to all comments/replies for every new post automatically.

I agree. That is more descriptive and more accurate. @renzms If you could submit another PR to make that adjustment I'd really appreciate it.

**Comment by raamdev** [comment]
@renzms Note that you'll need to submit a PR for both Lite and Pro versions.

**Comment by renzms** [comment]
@jaswsinc @raamdev 
Lite and Pro PR's submitted.

**Comment by jaswsinc** [comment]
@renzms @raamdev Beautiful. Thank you!
