### ISSUE TITLE
PSR 2/4 Compliance

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#150]
- [x] The entire codebase should be formatted for PSR-2 compliance.
- [x] Instead of using Git Submodules, we should switch to Composer.
- [x] Convert to Phing build script if possible.
- [x] Consider building the lite variation from the pro version like ZC.
- [x] Resolve [this bug](https://github.com/websharks/comment-mail/issues/173#issuecomment-181420932) whenever reformatting and cleanup takes place.
- [x] ~~Partially~~ Fully resolve [this issue](https://github.com/websharks/comment-mail/blob/151224/comment-mail/plugin.php#L28).

---

Remaining...

- [x] Finish refactoring classes.
- [x] Review `::` static calls and refactor.
- [x] Review underscore calls and refactor.
- [x] Search/replace `.exit(` concatenation calls.
- [x] Lint check entire codebase for PSR 2/4 issues.
- [x] Add conflict check; i.e., CM vs. CM Pro back in.
- [x] Search for `(?:static|cache)Key('` with static references.
- [x] Review and perhaps remove several calls to `(?:include|require)(_once)?`
- [x] Review SQL queries with single quotes, which previously had double quotes.

Remaining...

- [ ] Add `/*[pro strip-from="lite"]*/  /*[/pro]*/` markers for lite generation.

   **(partial completion)**

---

_Noting that existing custom templates out-in-the-wild will be broken by these changes. Simple templates will remain functional, but Advanced PHP templates that have been customized in previous versions will no longer work after these changes._

**Comment by jaswsinc** [comment]
- Convert to Phing build script if possible.
- Consider building the lite variation from the pro version like ZC.

**Comment by jaswsinc** [comment]
Assigning this issue to myself. This needs to be done sooner rather than later; if I can find the time. At the moment, we are all juggling both the old and the new formatting styles and there is no easy way for us to all get on the same page when it comes to the Comment Mail codebase.

**Comment by raamdev** [comment]
@jaswsinc Do you think we can close this issue in time for the RC (Friday, December 4th) or should I punt this to a Future Release milestone?

**Comment by jaswsinc** [comment]
I would punt this. I'm working on this, but even if I get it done before Friday it should go through a lot more testing than we have time for in the upcoming RC IMO.

**Comment by jaswsinc** [comment]
I should note that I will probably push _some_ work on this together with my review and tweaks to the MailChimp integration. However, I plan to leave this open and continue working on this for the next couple weeks.

**Comment by raamdev** [comment]
Copy that. Thank you.

**Comment by jaswsinc** [comment]
@raamdev The work in this issue is becoming slightly more urgent. However, I'm concerned about me trying to tackle this while everyone has open PRs, because this issue is going to introduce sweeping changes to the entire codebase (e.g., formatting indentation, brackets, etcs), potentially causing a lot of confusion with open PRs getting merged in.

So I suggest that we try to schedule a week for this work to be done, and during that week we try to make sure there are no open PRs already, and that everyone works on something else while I straighten this mess out.

**Comment by jaswsinc** [comment]
You have the next release scheduled for Feb 2nd, so I suggest we try to start work on this Feb 5th (the following Friday). I might be able to do it over that weekend, and if not I'll have the rest of the following week to finish it up. I'm adding this to the calendar so that you can OK it.

**Comment by raamdev** [comment]
> next release scheduled for Feb 2nd, so I suggest we try to start work on this Feb 5th (the following Friday)

Agreed. I'm assigning this to the Future Release milestone so that we can tackle it first-thing as after the current release is finished.

**Comment by jaswsinc** [comment]
Noting that this was pushed to Feb 12th by Raam.

**Comment by jaswsinc** [comment]
Adding new item to this checklist.

- Look for this bug whenever reformatting and cleanup takes place.

**Comment by raamdev** [comment]
@jaswsinc FYI, I assigned issues #173 and #230 to you, since you want to work on those as part of this GitHub issue.

**Comment by raamdev** [comment]
@jaswsinc This work can proceed now that the Comment Mail v160213 GA release has been completed. Let me know if you'd like help with anything here. :smile:

**Comment by jaswsinc** [comment]
Awesome. Thanks!

**Comment by jaswsinc** [comment]
Noting that existing custom templates out-in-the-wild will be broken by these changes.

**Comment by jaswsinc** [comment]
## New Namespace Constants (like Comet Cache)

```php
define(__NAMESPACE__.'\\QV_PREFIX', 'cm_');
define(__NAMESPACE__.'\\SHORT_NAME', 'CM');
define(__NAMESPACE__.'\\NAME', 'Comment Mail');
define(__NAMESPACE__.'\\DOMAIN', 'comment-mail.com');
define(__NAMESPACE__.'\\GLOBAL_NS', 'comment_mail');
define(__NAMESPACE__.'\\SLUG_TD', 'comment-mail');
define(__NAMESPACE__.'\\TRANSIENT_PREFIX', 'cmtmail_');
define(__NAMESPACE__.'\\VERSION', ${__FILE__}['version']);
define(__NAMESPACE__.'\\PLUGIN_FILE', ${__FILE__}['plugin']);
define(__NAMESPACE__.'\\IS_PRO', ${__FILE__}['is_pro']);
```

Comment Mail has two that Comet Cache does not have yet.

- `QV_PREFIX`
- `TRANSIENT_PREFIX`

**Comment by raamdev** [comment]
@jaswsinc writes...
> Noting that existing custom templates out-in-the-wild will be broken by these changes. Simple templates will remain functional, but Advanced PHP templates that have been customized in previous versions will no longer work after these changes.

Hmm, that seems like a pretty big deal. What sort of failure will occur if someone did customize an Advanced PHP template in a prior release? Is there any way for us to detect if Advanced PHP templates have been modified and notify the site owner that they need to update their template?

**Comment by jaswsinc** [comment]
> What sort of failure will occur if someone did customize an Advanced PHP template in a prior release?

They use a different PHP namespace and they call upon methods that were renamed to their `camelCase` equivalent. So using older PHP templates with the newly modified codebase will result in PHP fatal errors.

> Is there any way for us to detect if Advanced PHP templates have been modified and notify the site owner that they need to update their template?

A version-specific upgrade routine might be able to handle this.

**Comment by raamdev** [comment]
> A version-specific upgrade routine might be able to handle this.

Roger that. I think we should definitely work on this to avoid fatal PHP errors if at all possible. I'll open a separate issue to track this.

**Comment by raamdev** [comment]
@jaswsinc I'm ready to merge this into `000000-dev` unless you have any objections.

**Comment by jaswsinc** [comment]
No objections :-)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Restructured Codebase**: The codebase has been completely restructured to improve performance, enhance flexibility, and make it easier to build in new features! Props @jaswsinc. See [Issue #150](https://github.com/websharks/comment-mail/issues/150).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Restructured Codebase**: The codebase has been completely restructured to improve performance, enhance flexibility, and make it easier to build in new features! Props @jaswsinc. See [Issue #150](https://github.com/websharks/comment-mail/issues/150).

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#150).
