### ISSUE TITLE
Undefined Indexes (Pro options in Lite)

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#152]
Installing the current `000000-dev` branch of Comment Mail Lite with debugging enabled generates the following:

```
PHP Notice:  Undefined index: list_server_enable in /Users/raam/Sites/test.dev/wp-content/plugins/comment-mail/plugin.inc.php on line 824
PHP Notice:  Undefined index: list_server in /Users/raam/Sites/test.dev/wp-content/plugins/comment-mail/plugin.inc.php on line 824
PHP Notice:  Undefined index: list_server_mailchimp_api_key in /Users/raam/Sites/test.dev/wp-content/plugins/comment-mail/plugin.inc.php on line 824
PHP Notice:  Undefined index: list_server_mailchimp_list_id in /Users/raam/Sites/test.dev/wp-content/plugins/comment-mail/plugin.inc.php on line 824
```

Here's [L824 in `plugin.inc.php`](https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/plugin.inc.php#L824); why are we even going through Pro options keys there in the Lite version?

**Comment by jaswsinc** [comment]
@raamdev Thanks for reporting this.

> Here's L824 in plugin.inc.php; why are we even going through Pro options keys there in the Lite version?

That is there so that it is not possible to save any pro-only option keys in the lite version. It's one part of what makes a pro-preview possible in the lite version, and also what makes it possible for us to use an exact copy of the `menu-page.php` file for both versions of the software.

The iteration is making sure that all pro-only option keys have a default value for the pro preview.

**Comment by jaswsinc** [comment]
## Next Actions (Lite Version Only)

- New feature branch in `websharks/comment-mail` repo.

- After [this line](https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/plugin.inc.php#L670) add the missing pro-only option keys.

  _See missing keys here that exist in the pro version. These need to exist in the lite version also please: https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/plugin.inc.php#L511-L517_

- Submit PR.

**Comment by jaswsinc** [comment]
@kristineds Thanks! :-)

_I'm going to skip the changelog entry for this work, since this problem existed only in the dev branch following some recent work to integrate MailChimp into the pro version._
