### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ','

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#153]
### Steps to reproduce this bug

- Install Comment Mail Lite `000000-dev` branch on a fresh WordPress install, activate, and enable Comment Mail
- Edit the "Hello World" post and click the "0 Subscriptions" in the Comment Mail meta box

![2015-10-28_00-45-18](https://cloud.githubusercontent.com/assets/53005/10779881/388c0cae-7d0d-11e5-842b-6ae62a4607cd.png)

### Expected Behavior

Bring me to the Subscriptions Table.

### Observed Behavior

Blank page is loaded with the following logged to my error log:

```
PHP Parse error:  syntax error, unexpected ',' in /Users/raam/Sites/test.dev/wp-content/plugins/comment-mail/includes/classes/menu-page-table-base.php on line 614
```

---

### Other ways to reproduce this

When there are 0 subscriptions (i.e., a clean WordPress installation), visiting any of these sections results in a blank page and the above error logged:

- Visit **Comment Mail → Subscriptions**
- Visit **Comment Mail → Subscriptions → Event Log**
- Visit **Comment Mail → Mail Queue**
- Visit **Comment Mail → Mail Queue → Event Log**

**Comment by jaswsinc** [comment]
## Next Actions

- New feature branch in the `websharks/comment-mail-pro` repo.

- Replace [this line](https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/includes/classes/menu-page-table-base.php#L614) with the following:

  ```php
  $post_comments_status = $this->plugin->utils_i18n->status_label($this->plugin->utils_db->post_comment_status__($item->{$prefix.'comment_status'}), 'ucwords');
  ```

- Replace [this line](https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/includes/classes/menu-page-table-base.php#L681) with the following:

  ```php
  $comment_status = $this->plugin->utils_i18n->status_label($this->plugin->utils_db->comment_status__($item->{$prefix.'approved'}), 'ucwords');
  ```

- Submit PR.

**Comment by jaswsinc** [comment]
Merged both PRs. Thanks @kristineds  and thanks @raamdev for reporting!

**Comment by jaswsinc** [comment]
_Noting that this bug was introduced in https://github.com/websharks/comment-mail/pull/145, which has never been released; i.e., this bug only impacted the dev branch. Skipping changelog entry for that reason._

**Comment by jaswsinc** [comment]
@kristineds You might have noticed the `{}` curly brackets while working on this issue and on the original PR that you worked on where the i18n utilities were being modified; i.e., where you added the `, 'ucwords'` parameter to several function calls as an enhancement.

I thought I'd try to point out why curly brackets are used, and how they work. See also: [this article](http://stackoverflow.com/questions/2596837/curly-braces-in-string-in-php) for some discussion about curly brackets in PHP.

In Comment Mail, you will find some instances where I am building class property names dynamically. This is accomplished in Comment Mail by formulating a string (dynamically) that references a named property in the class.

So for instance, the `$item` class has a property named `post_comment_status`. In the code what you see is `$item->{$prefix.'comment_status'}`. If I were to hard-code this, I would write it as: `$item->post_comment_status`

So `$prefix` is equal to `post_`, and the curly brackets are used to build that string, which is then parsed as: `$item->post_comment_status`; i.e., `{$prefix.'comment_status'}` becomes `post_comment_status`
