### ISSUE TITLE
Improve Dashboard Notices

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#163]
## Improve "Upgrading from StCR" message:

**Before:**
![2015-11-23_16-06-26](https://cloud.githubusercontent.com/assets/53005/11350721/ee64d0e4-9200-11e5-9d5e-ab68534758ed.png)

**After:**
![2015-11-23_16-16-31](https://cloud.githubusercontent.com/assets/53005/11350716/e75e3eac-9200-11e5-9bca-c465ea5d2fec.png)

## Add "Comment Mail is disabled" message

It's easy to forget that Comment Mail has not yet been enabled, especially when upgrading from StCR to Comment Mail and going through the import process. It would be a good idea to have a message (NOT dismissable) that indicates Comment Mail is currently disabled:

![2015-11-23_16-46-55](https://cloud.githubusercontent.com/assets/53005/11350891/d1e4d08a-9201-11e5-8d94-14ef08d75974.png)

**Comment by jaswsinc** [comment]
Regarding this issue. There is a special file in Comment Mail that is dedicated to StCR migration routines. See: https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/stcr.php#L96

The notice that Raam referenced in that issue can be found and tweaked in that file.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Where can I add the "Comment Mail is disabled" message? I'm seeing this after enabling both CM and StCR on my directory.

![CM + StCR notice](https://cloud.githubusercontent.com/assets/7514953/11418087/7c167ba6-9457-11e5-9581-2ea4ccbd8154.png)

**Comment by jaswsinc** [comment]
@kristineds Great question. I will work on an outline for this and come back that soon.

**Comment by kristineds** [comment]
> I will work on an outline for this and come back to that soon.

Great. Thanks! :+1:

**Comment by jaswsinc** [comment]
## @kristineds Next Actions

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L1955) add the following:

  ```php
  if (!$this->options['enable']) {
    $this->enqueue_notice(__('NOTICE GOES HERE', $this->text_domain));
  }
  ```

---

Please repeat in the lite version.

**Comment by jaswsinc** [comment]
@raamdev I suggest that we also alter the code snippet that I gave Kristine above. Once she pushes her next commit and you have a chance to test, let's see if it is better if do it this way.

  ```php
  if (!$this->options['enable'] && !get_option(__NAMESPACE__.'_notices')) {
    $this->enqueue_notice(__('NOTICE GOES HERE', $this->text_domain));
  }
  ```

This way the new (additional) notice is not shown unless there are no others; i.e., it will not be shown on activation, because we already have a notice for that, and we have several other StCR and conflict/warning notices too. So I think showing this notice is going to be best when there are no others.

**Comment by jaswsinc** [comment]
@kristineds Is this ready for another review also?

**Comment by jaswsinc** [comment]
Nevermind! Too much vodka. I reviewed the PRs.

**Comment by raamdev** [comment]
@jaswsinc writes...
> I suggest that we also alter the code snippet that I gave Kristine above. Once she pushes her next commit and you have a chance to test, let's see if it is better if do it this way.
> [...]
> I think showing this notice is going to be best when there are no others.

I actually disagree. I think it's fine to have that notice always show up, even when there are other notices. The reason? Because if you have the Comment Mail plugin active, you probably intend to use it. If it's not enabled, then you're not using it and it makes sense to inform the site owner of as much. If the "Comment Mail is disabled" notice is annoying, then you should just deactivate the plugin.

The only reason I'm slightly bullish on having a notice there at all is that Comment Mail provides important front-end functionality. If Comment Mail is disabled, that functionality is not being provided and therefore we should alert the site owner of that fact. (I wouldn't add such a notice for a plugin like ZenCache only because if ZenCache is disabled, the site doesn't lose any functionality: it just gets a little slower).

What made me think of adding such a notice at all was having StCR + Comment Mail installed: I was losing track of which plugin was enabled and found myself wondering, "Is Comment Mail enabled?" when I was looking at other areas of the site. Basically, it felt like Comment Mail being disabled was simply "too quiet". A persistent Dashboard notice is perfect.

---

@kristineds I tested the latest PRs and noticed two things:

The "Comment Mail is disabled" message should have an `error` (red) class not an `updated` (green) class:

![2015-12-02_16-17-27](https://cloud.githubusercontent.com/assets/53005/11544529/5416af8c-9910-11e5-9ad7-7f31615fd6a6.png)
![2015-12-02_16-18-42](https://cloud.githubusercontent.com/assets/53005/11544562/8151de04-9910-11e5-9c6d-a471d7fb9495.png)

Also, please change the "Comment Mail settings" link to just "settings". Now that I see the notice in action, mentioning "Comment Mail" a second time in that notice seems redundant and unnecessary. :smile:

**Comment by kristineds** [comment]
@jaswsinc @raamdev Here are the updated PRs for both Pro and Lite

![screen shot 2015-12-03 at 5 36 41 pm](https://cloud.githubusercontent.com/assets/7514953/11557076/b495d9a2-99e5-11e5-8deb-6fd2f254f704.png)

- [Comment Mail Pro Pull Request](https://github.com/websharks/comment-mail-pro/commit/32aa1ae3db34c9f1b29ae38ad9160aec09b0e25c)
- [Comment Mail Lite Pull Request](https://github.com/websharks/comment-mail/commit/0ac87363d2a8c9b8a57275a621ac740bb0206b34)

**Comment by raamdev** [comment]
@kristineds Thank you! That looks great. :smile:

**Comment by Reedyseth** [comment]
OK, I just pull the latest commit c632e1c and after installing Comment mail I got the following notices.

![image](https://cloud.githubusercontent.com/assets/1228711/11604651/a7443362-9aac-11e5-8489-03accd1e26e5.png)

So basically the second notices is duplicated, at first I thought that I had my database corrupted but then after deleting the CM tables the same behavior pop up. Can you give it a try ?

**Comment by raamdev** [comment]
@Reedyseth When testing dev branches or feature branches, you need to make sure that the previous version is _completely_ uninstalled. The best way to do this:

1. Visit **Comment Mail → Config. Options → Data Safeguards** and turn them off (so that no data is saved in the database)
1. Deactivate and then delete the plugin in **Dashboard → Plugins**

When Data Safeguards are disabled and you delete the plugin, the deletion routines will clean up your database to ensure that there are no settings left behind. Then, you can install the new version that you want to test.

---

I just followed those steps and installed the latest Lite version from [this branch](https://github.com/websharks/comment-mail/issues/168) and it appears to be working fine. Here's what I saw after installing (with StCR active):

![2015-12-04_19-50-31](https://cloud.githubusercontent.com/assets/53005/11604895/edbe3b58-9ac0-11e5-8635-88a93ada4e54.png)

**Comment by Reedyseth** [comment]
> When testing dev branches or feature branches, you need to make sure that the previous version is completely uninstalled.

I just get rid of the folder and the CM tables, I will follow those steps and let you now.

**Comment by raamdev** [comment]
@Reedyseth writes...
> OK, I just pull the latest commit c632e1c

Also, the best way to test is to checkout the branch you want to test. So to test this branch you would `git fetch origin && git checkout -b feature/163 origin/feature/163`. Then you can simply test the `comment-mail/` directory. If the `feature/163` branch is updated (i.e., someone pushes more commits to it), you can simply run `git pull` from inside the `feature/163` branch to get the latest commits and then test again.

**Comment by Reedyseth** [comment]
> Also, the best way to test is to checkout the branch you want to test. So to test this branch you would git fetch origin && git checkout -b feature/163 origin/feature/163.

Thank you for that.



> When testing dev branches or feature branches, you need to make sure that the previous version is completely uninstalled. The best way to do this:
> 
> Visit Comment Mail → Config. Options → Data Safeguards and turn them off (so that no data is saved in the database)
> Deactivate and then delete the plugin in Dashboard → Plugins
> When Data Safeguards are disabled and you delete the plugin, the deletion routines will clean up your database to ensure that there are no settings left behind. Then, you can install the new version that you want to test.

I had information contaminated on my database, so after allowing comment mail to get rid of all the plugin by clicking on the delete button some features remained on the database.

* I deleted the plugin directory from wp_content
* Delete all the Comment Mail tables:
```sql
DROP TABLE wp_comment_mail_queue;
DROP TABLE wp_comment_mail_subs;
DROP TABLE wp_comment_mail_queue_event_log;
DROP TABLE wp_comment_mail_sub_event_log;
```
* Delete all the CM options, on this case this is where all the corrupted data was located, more specific the `comment_mail_notices` option.
```sql
DELETE FROM wp_options WHERE option_name LIKE 'comment_mail%';
```
* Update the latest changes of comment mail with `git fetch --all && git merge 000000-dev`
* Added the CM plugin directory again into my WordPress.
* Activated.
* Now everything work as it should be.

![image](https://cloud.githubusercontent.com/assets/1228711/11692926/525c0710-9e5f-11e5-8350-e62bf7d5fd4c.png)

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Improved Dashboard notices. The "Upgrading from Subscribe to Comments Reloaded" message has been improved and a new Dashboard notice lets you know when Comment Mail is disabled. Props @kristineds. See [Issue #163](https://github.com/websharks/comment-mail/issues/163).

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Improved Dashboard notices. The "Upgrading from Subscribe to Comments Reloaded" message has been improved and a new Dashboard notice lets you know when Comment Mail is disabled. Props @kristineds. See [Issue #163](https://github.com/websharks/comment-mail/issues/163).

**Comment by kristineds** [comment]
:+1:

**Comment by raamdev** [comment]
Updated Comment Mail to use a yellow warning notice instead of a red error notice when Comment Mail is disabled. Also updated the notice routines to support a new `enqueue_warning()` method.

![2015-12-18_09-35-10](https://cloud.githubusercontent.com/assets/53005/11899143/1c600c98-a56b-11e5-8b52-d3480f40738e.png)

**Comment by jaswsinc** [comment]
Nice! I did not know that class existed in core. Great!

**Comment by raamdev** [comment]
@jaswsinc Yep, I didn't either! I learned about it when I finally noticed the yellow "Update to WordPress v4.4" Dashboard notice. :grin:

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#163).
