### ISSUE TITLE
Begin StCR Auto-Importation button "appears" to do nothing (UI Issue)

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#172]
When you click the "Begin StCR Auto-Importation" button, there is no indication that clicking the button actually did anything.

![2015-12-10_14-41-25](https://cloud.githubusercontent.com/assets/53005/11726427/949edb96-9f4c-11e5-9685-c91110248ed5.png)

The problem is that clicking the button changes the box at the bottom of the page, which may be off the screen, and therefore the user has no indication that anything happened unless they decide to scroll to the bottom of the page and look.

![2015-12-10_14-41-39](https://cloud.githubusercontent.com/assets/53005/11726431/98bf9f44-9f4c-11e5-9ccd-bfbb91f13f43.png)

I suggest that we move the grey import box right underneath the Import button, since that's where it makes the most sense to see the changes. 

![2015-12-10_14-49-14](https://cloud.githubusercontent.com/assets/53005/11726570/360e3b0c-9f4d-11e5-90c2-d9199608f053.png)

---

Once the above changes are made, the following changes should also be made (add an `<h1>` title that helps clarify what the steps below are actually about, and any mentions of the status box being "below" should be changed to "above". 

![2015-12-10_14-51-44](https://cloud.githubusercontent.com/assets/53005/11726688/d9d8fe02-9f4d-11e5-838e-7d1b4098a639.png)

**Comment by jaswsinc** [comment]
:+1: I agree.

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Moved the Import Status box (for importing Subscribe to Comments Reloaded subscriptions) up underneath the "Begin StCR Auto-Importation" button to improve visibility when importing subscriptions. See [Issue #172](https://github.com/websharks/comment-mail/issues/172).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Moved the Import Status box (for importing Subscribe to Comments Reloaded subscriptions) up underneath the "Begin StCR Auto-Importation" button to improve visibility when importing subscriptions. See [Issue #172](https://github.com/websharks/comment-mail/issues/172).

**Comment by jaswsinc** [comment]
Nice!

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#172).
