### ISSUE TITLE
Digest notifications do not include all new comments

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#173]
_This was tested using the Lite version from the dev branch as of 2015-12-10 16:16:05 EST._

## Steps to reproduce this bug

- Install, activate, and enable Comment Mail Lite
- Logout and leave a comment on a post selecting "All Comments/Replies" and "Hourly Digest"
- Leave several additional comments on the same post with different email addresses (i.e., as different commenters)
- Wait for the Hourly Digest email that should be sent to the first commenter who selected "Hourly Digest"

## Expected Behavior

The subscriber who selected "Hourly Digest" should get a digest email that includes a list of all the comments left on the post after the digest subscription was created.

## Observed Behavior

The subscriber who selected the "Hourly Digest" receives an email that only contains the very last new comment that was posted, as opposed to all of the comments. Additionally, this notification makes no mention of "digest" at all and looks just like the email they would receive if they simply selected `asap`. (The title of the email that is received even says "New Comment on...", as opposed to "New Comments on...".)

**Comment by raamdev** [comment]
@kristineds @renzms @Reedyseth I could use some help attempting to reproduce the issue described above. :smile:

**Comment by kristineds** [comment]
@raamdev I was able to reproduce this issue. 

- Installed and enabled Comment Mail Lite v151224
- Posted as first commenter and selected "All Comments/Replies" and "Hourly Digest"
- First commented received an email (right after the confirmation email) that contains one comment that was posted right after. i.e. should be "digest" but received it as "asap". 
- Waited for an hour or two to see if I'll still get a "digest" of the other comments, but didn't received anything only the first comment
-  Title of the email that is received says "New Comment on.."

![Hourly Digest bug report](https://cloud.githubusercontent.com/assets/7514953/12361529/a51448a2-bbf9-11e5-96fb-eb020fd30af0.png)

**Comment by raamdev** [comment]
> should be "digest" but received it as "asap".

Can you confirm what the "Deliver" option is set to when you edit that subscription in **

**Comment by kristineds** [comment]
> Can you confirm what the "Deliver" option is set to when you edit that subscription in Comment Mail → Subscriptions? It should say "Hourly"...

It says "Hourly" on my end for that subscription.

![screen shot 2016-01-19 at 11 57 30 pm](https://cloud.githubusercontent.com/assets/7514953/12423860/77e297d2-bf08-11e5-9f33-9c3a2e97c867.png)

**Comment by raamdev** [comment]
@kristineds So it sounds like the problem is that the "Hourly" digest option isn't being passed properly to the routine that creates the subscription when someone selects "Hourly" on comment form? Would you mind running a few more tests to confirm that's the case? That should help us narrow this bug down quite a bit.

**Comment by raamdev** [comment]
@kristineds Oh, sorry, I totally misunderstood what you said the first time. :-) I realize now that it _should_ be hourly. 

Hmm, so it sounds like there might actually be a problem with the routine that processes the subscriptions to determine which ones require digests...

**Comment by jaswsinc** [comment]
I haven't looked over this issue with any great detail yet, but it might help to know that Comment Mail doesn't have any hard-coded handler for digest notification templates. Comment Mail simply adapts the emails that it sends based on the number of comments it contains.

So for instance, if you subscribe to a digest, you should be getting (at most) one notification every period for which you subscribed. This can lead to each notification that you receive containing multiple comment notifications (in the form of a digest), but if it so happens that there was only one additional comment since your last notification came through, the email will only contain just the one, and the notification format reverts automatically back to what a standard one-off notification would look like in that scenario.

This is mostly handled by the email templates, where we have `$is_digest`.
https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/includes/templates/type-a/email/comment-notification/subject.php#L40

**Comment by raamdev** [comment]
> if it so happens that there was only one additional comment since your last notification came through, the email will only contain just the one, and the notification format reverts automatically back to what a standard one-off notification would look like in that scenario.

Ah, that's helpful to know. Thank you. Yes, it sounds like what we need to test is multiple comment notifications within an hour, so that we can trigger the digest email template (which only appears when more than one comment notification is available).

@kristineds Could you try testing that? You'll just need to run a test where one email address is subscribed to a post, and then generate several new replies (with a different email address) so that the digest subscriber receives more than one comment notification and then after 1 hour the digest email with a list of all the notifications should be shown.

---

Once this has been confirmed, we should also publish a new KB Article for this that explains what Jason just clarified, i.e., that if there's only 1 notification, you'll see the regular `asap` notification template even if you selected one of the digest options. KB Article title: "Why don't I receive the digest notification?"

**Comment by raamdev** [comment]
@kristineds Did you get a chance to confirm the above?

**Comment by kristineds** [comment]
@raamdev I tested this but wasn't able to reproduce it. I didn't get any digest email after 1 hour. 

- Installed and enabled Comment Mail Lite v151224
- Subscribed and commented to a [post](http://kristine.websharks-inc.net/all-about-bacon/#comment-38) as `kristine_test1`, selected "**All Comments/Replies**" and "**Hourly Digest**". 

   ![screen shot 2016-02-07 at 2 39 38 am](https://cloud.githubusercontent.com/assets/7514953/12868655/bd2a5d8e-cd45-11e5-85c9-70eeaf870388.png)

- Received an email notification for the subscriber `kristine_test1` to confirm subscription.

   ![screen shot 2016-02-07 at 2 45 35 am](https://cloud.githubusercontent.com/assets/7514953/12868657/c77e086c-cd45-11e5-9ef7-95873aac8e69.png)

- Confirmed subscription and started posting several replies to that [comment](http://kristine.websharks-inc.net/all-about-bacon/#comment-38) from `kristine_test1`
- Received an email notification (again) for the first reply on the comment: 

   ![screen shot 2016-02-07 at 2 48 16 am](https://cloud.githubusercontent.com/assets/7514953/12868660/d06ed758-cd45-11e5-9859-3d55eec0f1a1.png)

- Waited for an hour to see if I'll still get a "digest email" of the other replies, but didn't receive anything

**Comment by jaswsinc** [comment]
@raamdev That sounds a lot like what you experienced, no?

**Comment by raamdev** [comment]
> That sounds a lot like what you experienced, no?

@jaswsinc Yes, that sounds exactly like what I experienced. My hourly digest subscriber received a comment notification for the first new comment reply (instantly), but no more after that.

**Comment by jaswsinc** [comment]
Thanks. I will keep my eyes open for this whenever I reformat this file on Friday.
https://github.com/websharks/comment-mail/issues/150#issuecomment-181493719

**Comment by jaswsinc** [comment]
I found a bug in this class, and it looks like a great suspect for this case.

Referencing: https://github.com/websharks/comment-mail-pro/blob/160213/comment-mail-pro/includes/classes/queue-processor.php#L647-L657

**Problem:** The case handlers are falling through on each other inadvertently in some scenarios.

**Comment by jaswsinc** [comment]
- This issue has been fixed by https://github.com/websharks/comment-mail/issues/150 (confirmed).
- I believe this resolves https://github.com/websharks/comment-mail/issues/192 as well, but further testing will be needed to confirm.

**Comment by raamdev** [comment]
@jaswsinc writes... 
> Problem: These case handlers are falling through on each other inadvertently in some scenarios.

Ah! Not `break`ing in case statements. One of my favorite "duh"s. :laughing: 

Great catch. Hopefully this does resolve #192; that will be awesome.

---

@websharks/comment-mail-team Please add this issue to your list of things to test this week.

**Comment by raamdev** [comment]
> Please add this issue to your list of things to test this week.

Sorry, that request was a little premature. I still need to merge @jaswsinc's work in `feature/150` into the dev branch. Once that's done, testing can begin. I'll come back here with another update once `feature/150` has been merged.

**Comment by raamdev** [comment]
@websharks/comment-mail-team Jason's work has been merged into `000000-dev`, which means we can now test it to confirm that this issue has been fixed.

Please post an update here once you get a chance to confirm whether or not this is fixed in `000000-dev`.

**Comment by IvanRF** [comment]
Possible related issue.

Steps to reproduce:
- Add a daily subscriber for all comments (it has to be subscribed)
- Post 4 comments and approve them waiting 2 to 5 minutes between each approval

The daily subscriber received a mail with test 1 and 2. Remaining comments went to the queue and disappeared. I thought a cron job will send the remaining comments, but two days passed and I didn't receive a notification for test 3 and 4. Daily digest is "digested" too soon maybe, and the remaining comments are never sent. I will do a second test on this.

**Comment by raamdev** [comment]
@IvanRF Thank you for the report. So it sounds like the daily digest email is not including all of the comments that it should but instead only including a smaller subset of comments (in your example, test 1 and test 2 comments), is that correct?

**Comment by IvanRF** [comment]
yes, I must add I was the only subscriber in the post. After I approve the first comment, it went to the queue. Then, the second one. Then, the email was sent only including those 2. I continued approving, but I never received an email for test 3 and 4.

**Comment by IvanRF** [comment]
Second test, same procedure waiting 2-4 minutes between approvals. Results:
- test 1 queued
- Email sent for test 1, includes "This comment was posted 2 minutes ago" (is it ok to send so fast a **daily** digest?)
- test 2 and 3 queued
- test 2 and 3 disappeared from the queue
- test 4 queued
- test 4 disappeared from the queue

Event Log only shows one entry with "(12 minutes ago)", surely for the email sent for test 1. I have no visible information about what happened to test 2, 3 and 4.

**Comment by raamdev** [comment]
@IvanRF During testing, it may help to have a plugin like [Email Log](https://wordpress.org/plugins/email-log/) installed so that you can see exactly what emails are sent from WordPress (instead of relying on receiving emails for testing). If there was a problem delivering the email notification to you, that would be a separate issue from Comment Mail actually generating the correct emails. Using a plugin like Email Log will tell you exactly what WordPress itself (i.e., Comment Mail) sent.

**Comment by IvanRF** [comment]
@raamdev thanks for the tip. Is it possible that the queue is discarding notifications? in my test, shouldn't test 2,3,4 remain in the queue until the next day?

**Comment by raamdev** [comment]
> shouldn't test 2,3,4 remain in the queue until the next day?

Yes, they should. I have no idea why they're not. I suspect there's a bug there somewhere. Hopefully I get reproduce this locally so that I can inspect things using XDebug and find out exactly what's going on.

**Comment by kristineds** [comment]
@raamdev Here are my observations for testing **Hourly Digest notifications**:

- Installed, activated, and enabled Comment Mail Lite `v160213`
- Use the default settings of: _"Yes, enable Auto-subscribe" & "No, require subscriptions to be confirmed via email"_
- Logged out and left a comment on a post selecting "All Comments/Replies" and "Hourly Digest"
- Received an email for the 1st commenter to confirm subscription. Clicked on the link to confirm subscription
- Went back to the post and left 4 additional comments on the same post with different email addresses (i.e., as different commenters)
- Received an email _instantly_ that a new comment (from the 2nd commenter) has been posted.
- Waited for an hour or two for the Hourly Digest email that should be sent to the 1st commenter who selected "Hourly Digest", but didn't receive any

I also tried testing **Daily Digest notifications**. I'll post an update here tomorrow (after 24hrs) regarding my observations. :)

**Comment by raamdev** [comment]
@kristineds writes...
> - Received an email instantly that a new comment (from the 2nd commenter) has been posted.
> - Waited for an hour or two for the Hourly Digest email that should be sent to the 1st commenter who selected "Hourly Digest", but didn't receive any

Thank you very much for running an additional test. That behavior appears to confirm exactly what @IvanRF reported, so there is almost certainly a bug here. 

Time for a bug hunt.

**Comment by kristineds** [comment]
@raamdev Just want to add my observations regarding the **Daily Digest notifications**. 

- Followed the same steps as what I did for the Hourly Digest & All Comments/Replies including posting additional comments with different email addresses.
- Received an email for the 1st commenter to confirm subscription. Clicked on the link to confirm subscription.
- Waited for more than 24hrs for the Daily Digest email that should be sent to the 1st commenter who selected "Daily Digest", but didn't receive any emails after that.

**Comment by raamdev** [comment]
@jaswsinc Any ideas about where to start the bug hunting here?

**Comment by jaswsinc** [comment]
Sorry, I am a little confused here about which bug we are testing for and in which version we should be testing against. Are these most recent reports coming from dev branch testing?

---

I noted after the last work that I did in this issue that I had confirmed that the original bug reported here was fixed in the PR I submitted with the restructuring for PSR2/4 compliance. Specifically, it was related to [these lines](https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/QueueProcessor.php#L211-L214) and also the [`case` fallthrough](https://github.com/websharks/comment-mail-pro/blob/160213/comment-mail-pro/includes/classes/queue-processor.php#L647-L657). These issues have been fixed in the dev branch.

---

@kristineds and @IvanRF were your most recent tests performed against the (as yet, unreleased) copy of the Comment Mail dev branch? Or against the latest official release of the software?

**Comment by IvanRF** [comment]
@jaswsinc all issues I sent are with the version in the WP directory, i.e. latest official release.

**Comment by kristineds** [comment]
@jaswsinc @raamdev I tested this again using the Lite version from the dev branch as of 2015-04-07. Here are my observations when testing the **Hourly Digest notifications** for all **All Comments/Replies**

- Received an email instantly that a new comment (from the 2nd commenter) has been posted.
Waited for an hour or two for the Hourly Digest email that should be sent to the 1st commenter who selected "Hourly Digest", but didn't receive any. 
- Received the "Hourly digest" after more than 7 hrs of waiting.

**Comment by jaswsinc** [comment]
Thanks @kristineds :-)

> Received the "Hourly digest" after more than 7 hrs of waiting.

Is it possible that this was a test site where only _you_ were the one visiting the site; i.e., it was private and you were the only one hitting any pages on the site while you were waiting?

If so, it's good to keep in mind that WP Cron (what WordPress and Comment Mail use for queue processing) is not a true CRON job that would ordinarily run on a server based on a timer. WP Cron does run on a timer, but it relies upon constant traffic hitting your site for it to run. Therefore, if you are waiting, waiting, waiting, and not visiting any pages on the site during that time period, you might not trigger WP Cron (or Comment Mail) until you hit the site again later, at which point Comment Mail will run again as intended and process pending items in the queue where it left off before.

So again, WP Cron operates under the assumption that you have a site with at least one visitor every 5 minutes or so; i.e., that at least one PHP script is going to run, which can then fork itself into a WP Cron task silently behind-the-scenes. Without this, WP Cron just does nothing by itself.

For this reason, whenever I'm testing a plugin that relies upon WP Cron, I get into the habit of refreshing a page on the site every few minutes just to be sure that WordPress will trigger WP Cron as it would under normal operating conditions in production.

**Comment by IvanRF** [comment]
>  I tested this again using the Lite version from the dev branch as of 2015-04-07. Here are my observations when testing the Hourly Digest notifications for all All Comments/Replies

> - Received an email instantly that a new comment (from the 2nd commenter) has been posted. 

That line confirms issue #261 for other digests too.

**Comment by kristineds** [comment]
> Is it possible that this was a test site where only you were the one visiting the site?; i.e., it was private and you were the only one hitting any pages on the site while you were waiting?

@jaswsinc: Yes, that is the case. I did refresh the page though since I'm posting as other commenters to trigger the digest. Would that not work? How long should I refresh the page on the site?

**Comment by raamdev** [comment]
@kristineds Can you please install [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) and try manually running the Comment Mail cron job to test the hourly digest notifications using the latest Lite version from the Dev branch?

**Comment by kristineds** [comment]
> Can you please install WP Crontrol and try manually running the Comment Mail cron job to test the hourly digest notifications using the latest Lite version from the Dev branch?

@raamdev Tested this using the Comment Mail Lite version from the dev branch as of 2015-05-27 with WP Crontrol installed. Below are my observations with the Hourly Digest notifications for all All Comments/Replies enabled. 

- Installed, activated, and enabled WP Crontrol
- Installed, activated, and enabled Comment Mail Lite v2015-05-27
- Logged out and left several comments (as different commenters) on a post selecting "All Comments/Replies" and "Hourly Digest"
- Didn't receive any confirmation emails _at all_ for any of the commenters
- Manually confirmed subscription for all commenters
- Waited for an hour to for the "hourly digest" for the first commenter or the other commenters, but didn't receive anything.

**Comment by jaswsinc** [comment]
@kristineds @raamdev I did a video to show how I walked through some extensive tests against the dev branch for both Lite and Pro and I have been unable to reproduce any of the problems being reported here. This seems to be working perfectly with moderation on and also with moderation off, in both the lite and pro repos. Maybe the video will offer some insight or maybe you can spot something that I'm not doing that would help reproduce the bug.

📹 Video posted in Slack as **Comment Mail Mysteries**.

**Comment by raamdev** [comment]
@jaswsinc writes in https://github.com/websharks/comment-mail/issues/173#issuecomment-184008627...
> I found a bug in this class, and it looks like a great suspect for this case.
> 
> Referencing: https://github.com/websharks/comment-mail-pro/blob/160213/comment-mail-pro/includes/classes/queue-processor.php#L647-L657
> 
> Problem: These case handlers are falling through on each other inadvertently in some scenarios.

I was just reviewing that code and trying to better understand what scenario (if any) would result in a bug there. I could not come up with any scenario, so I'm not seeing any bug at all. I agree that there should be `break;` statements there, however since each `case` statement includes a `return` statement, a `break` statement would never be reached anyway (because the return statement would exit the switch first). 

To verify this, I created the following test with the missing `break` statements:

```php
<?php
function tester($v)
{
    switch($v) // Check for digests.
    {
        case 'hourly': // Delivery option = hourly digest.
            if($v == 'hourly')
                return 'returning from hourly';
        case 'daily': // Delivery option = daily digest.
            if($v == 'daily')
                return 'returning from daily';
        case 'weekly': // Delivery option = weekly digest.
            if($v == 'weekly')
                return 'returning from weekly';
    }
    return 'returning from tester() + $v = ' . $v;
}

echo tester('hourly') . "\n";
echo tester('daily') . "\n";
echo tester('weekly') . "\n";
echo tester('n/a') . "\n";
```

As expected, the results are as follows:

```

returning from hourly
returning from daily
returning from weekly
returning from tester + $v = n/a
```

And even if one of those `if` conditionals returned false and we did fall through the `case` statement due to a lack of `break` statements, none of the other case statements would be true (e.g., if we entered `case "hourly"`, `case "daily"` and `case "weekly"` would not be true and we'd never enter those). The only way I'm seeing potential for a bug in this case would be if we also had a `default:` case (because then if an `if ` statement did fail, the `default` case would always be run despite our having entered one of the other `case` statements).

So in what scenario might that code cause a problem?

The reason I'm trying to better understand how that (bad) code might have introduced a bug is that [you said](https://github.com/websharks/comment-mail/issues/173#issuecomment-184139431) that fixing it potentially solves two issues: this one, and #192. However, I'm not seeing a bug there at all.

The other reason I'm trying to understand how that's a bug is that I tried reproducing the original issue outlined at the top of this issue, with digest emails not going out, and I'm once again able to reproduce it—the queued notifications get to Holding Until "(less than a minute)" and then just sit there indefinitely (testing Comment Mail Lite, built from `000000-dev` branch as of 2016-06-09 21:58:25 EDT). 

Here's a video demonstrating the issue: http://quick.as/0Gj3C76PA

**Comment by jaswsinc** [comment]
@raamdev writes...

> So in what scenario might that code cause a problem?

In the example you're using it would not be an issue I agree. But that's different from what I fixed in Comment Mail. See: [these lines](https://github.com/websharks/comment-mail-pro/blob/160213/comment-mail-pro/includes/classes/queue-processor.php#L647-L657) where falling through in each case is a definite possibility.

Given the original code, if a subscriber has never been notified before, and they have a setting of `hourly`, that will result in three separate DB queries and perhaps (although unlikely) be treated as `weekly`, which would be incorrect. This could occur given three separate queries that _might_ (however unlikely) return something different if the user is still active on the site and doing other things.

> And even if one of those if conditionals returned false and we did fall through the case statement due to a lack of break statements, none of the other case statements would be true (e.g., if we entered case "hourly", case "daily" and case "weekly" would not be true and we'd never enter those).

A `case` only needs to match a starting point, and then when it falls through there is no `case` check again. It simply falls through to the next case. A neat way to experiment with this is using byte notation. Change `$modifier` to something else and see how this works.

```php
$value = 1; $modifier = 'tb';
// Convert 1 TB to bytes.

switch ($modifier) {
    case 't':
    case 'tb':
        $value *= 1024;
        // Fall through.

    case 'g':
    case 'gb':
        $value *= 1024;
        // Fall through.

    case 'm':
    case 'mb':
        $value *= 1024;
        // Fall through.

    case 'k':
    case 'kb':
    case 'kbs':
        $value *= 1024;
}
echo $value; // 1099511627776
```

---

@raamdev writes...

> The reason I'm trying to better understand how that (bad) code might have introduced a bug is that you said that fixing it potentially solves two issues: this one, and #192. However, I'm not seeing a bug there at all.

### The Bigger Problem ...

I see. I was trying to avoid adding confusion here, but it looks like I failed, because I left something out that would help you. As I mentioned in the video I did recently, this was actually a two-part fix.

1. The issue with `case` falling through in certain circumstances was fix 1.

2. The next fix. See [these lines](https://github.com/websharks/comment-mail-pro/blob/160213/comment-mail-pro/includes/classes/queue-processor.php#L232-L233). Now, look [just above into the main loop](https://github.com/websharks/comment-mail-pro/blob/160213/comment-mail-pro/includes/classes/queue-processor.php#L206-L207). See how an entry could be 'processed' but held, and yet it was being deleted in all cases? i.e., NOT held as it should be.

  That was the bigger problem and I discovered this after doing some of the same digging that you are, given how rare it would be for that `case` issue to occur. So like you, I kept digging and eventually found that additional problem that was far more likely to be the culprit in most of the bug reports we were getting.

**Comment by jaswsinc** [comment]
> —the queued notifications get to Holding Until "(less than a minute)" and then just sit there indefinitely (testing Comment Mail Lite, built from 000000-dev branch as of 2016-06-09 21:58:25 EDT).
> 
> Here's a video demonstrating the issue: http://quick.as/0Gj3C76PA

I just tried to reproduce this again locally without success; i.e., it's working as expected on my end. However, given your video and the reports from others it makes me wonder if there is something going on with `wp-cron.php` on some of your collective test sites.

My suggestion would be to start monitoring activity in [this file](https://github.com/WordPress/WordPress/blob/master/wp-cron.php) by adding lines that log incoming requests processed by that file and see what you can find out.

In short, if you find they are just sitting in the queue, it's almost certainly because the CRON is not running. So I'd start by trying to prove that CRON is working (or not) and go from there.

e.g., after [this line](https://github.com/WordPress/WordPress/blob/master/wp-cron.php#L12) add the following and then work your way down through this file to see if you can figure out where the CRON is failing at, or if it's never actually running at all?

```php
file_put_contents(WP_CONTENT_DIR.'/cm-debug-cron.log', print_r($_REQUEST, true)."\n\n", FILE_APPEND);
```

In addition to that, you could also add a similar logging routine [here](https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/Plugin.php#L2681)

```php
file_put_contents(WP_CONTENT_DIR.'/cm-debug-cron-hook.log', print_r($_REQUEST, true)."\n\n", FILE_APPEND);
```

**Comment by raamdev** [comment]
@jaswsinc writes...
> A case only needs to match a starting point, and then when it falls through there is no case check again. It simply falls through to the next case.

Not true if the case statement includes a `return` statement, as all of the `case` statements in the original code did.

```php
<?php
$value = 1; $modifier = 'tb';
// Convert 1 TB to bytes.

function converter($value, $modifier) {
    switch ($modifier) {
        case 't':
        case 'tb':
            $value *= 1024;
            return $value;
            // DOES NOT fall through.

        case 'g':
        case 'gb':
            $value *= 1024;
            return $value;
            // DOES NOT fall through.

        case 'm':
        case 'mb':
            $value *= 1024;
            return $value;
            // DOES NOT fall through.

        case 'k':
        case 'kb':
        case 'kbs':
            $value *= 1024;
            return $value;
            // DOES NOT fall through.
    }
    return $value;
}

echo converter($value, $modifier); // 1024
```

**Comment by raamdev** [comment]
> if you find they are just sitting in the queue, it's almost certainly because the CRON is not running. So I'd start by trying to prove that CRON is working (or not) and go from there.

You know what, last night on my bike ride home I was thinking about this problem and came to the exact same conclusion, which reminded me of https://github.com/websharks/comment-mail/issues/194 (Cron event disappears in some scenarios: _cron_comment_mail_queue_processor), which we already know is an issue that we proved (and fixed) in Comet Cache. I'm willing to bet that what we're seeing here is THAT bug, which is leading to all of this confusion.

I'll run some more tests today and report back.

**Comment by raamdev** [comment]
> #194 (Cron event disappears in some scenarios: _cron_comment_mail_queue_processor), which we already know is an issue that we proved (and fixed) in Comet Cache. I'm willing to bet that what we're seeing here is THAT bug, which is leading to all of this confusion.

Confirmed!! The `_cron_comment_mail_queue_processor` is missing:

![2016-06-10_10-04-18](https://cloud.githubusercontent.com/assets/53005/15966841/d6dae4a6-2ef2-11e6-8266-98e912836ad9.png)

**Comment by jaswsinc** [comment]
> Not true if the case statement includes a return statement, as all of the case statements in the original code did.

Right. But that `return` was conditional; i.e., it would not always occur.

**Comment by jaswsinc** [comment]
> Confirmed!! The _cron_comment_mail_queue_processor is missing:

Aha! Very cool. I saw your commits a moment ago.

**Comment by raamdev** [comment]
> Right. But that return was conditional; i.e., it would not always occur.

Try adding in a conditional; it still does not fall through:

```php
        case 't':
        case 'tb':
            if (false) {
                $value *= 1024;
                return $value;
            }
            // DOES NOT fall through.
```

**Comment by raamdev** [comment]
> Try adding in a conditional; it still does not fall through:

Whoops, user error. 😄  I see it _does_ fall through in the above scenario. I concede defeat. 😆

**Comment by raamdev** [comment]
@jaswsinc writes...
> this was actually a two-part fix.
> 
> The issue with case falling through in certain circumstances was fix 1.
> 
> The next fix. See these lines. Now, look just above into the main loop. See how an entry could be 'processed' but held, and yet it was being deleted in all cases? i.e., NOT held as it should be.
> 
> That was the bigger problem and I discovered this after doing some of the same digging that you are, given how rare it would be for that case issue to occur. So like you, I kept digging and eventually found that additional problem that was far more likely to be the culprit in most of the bug reports we were getting. That was also fixed at the same time, even though I failed to mention that originally.

Ah, thank you for explaining that. Those sorts of bug fixes are important to document so that we can link them to existing bug reports. 

So I'm seeing a few bug fixes here:

- **Bug Fix:** If a subscriber had never been notified before, and they chose a Digest Delivery option of `hourly`, there was a possibility, in some scenarios, for that subscription to instead be treated as a `weekly` digest.
- **Bug Fix**: In some scenarios, a notification could be 'processed' but held (e.g., because it belongs to a digest and should go out later), and yet that notification was being deleted in all cases and not being sent out at all.

Do I have that right? Also, that last bug fix: I'm wondering what that would look like symptom-wise. Would it look like https://github.com/websharks/comment-mail/issues/192?

**Comment by raamdev** [comment]
↑ Noting that the fix I just pushed for a bug related to the Queue Processor cron event was likely the cause for many of the reports in this GitHub issue about never receiving the hourly digest notifications. See https://github.com/websharks/comment-mail/issues/194#issuecomment-225216195

**Comment by jaswsinc** [comment]
> Also, that last bug fix: I'm wondering what that would look like symptom-wise. Would it look like #192?

This was causing queue entries that one would expect to be held, to not be held (or sent). They would magically be processed and silently go poof, and never even be logged so they wouldn't show up in the queue event log either.

**Comment by raamdev** [comment]
> and silently go poof

So they would just disappear? I.e., a subscriber simply wouldn't receive the notifications they were expecting when new comments were posted?

**Comment by raamdev** [comment]
I'm adding two changelog entries to the next release for the two bugs described above that were fixed while restructuring the codebase (#150):

- **Bug Fix:** Fixed a bug where a subscriber who selected Hourly Digest and who had never been notified before could, in some scenarios, have their subscription treated instead as a Weekly Digest. This bug was found and fixed during the codebase restructuring. Props @jaswsinc. See [Issue #150](https://github.com/websharks/comment-mail/issues/150) and additional discussion in [Issue #173](https://github.com/websharks/comment-mail/issues/173#issuecomment-225215333).
- **Bug Fix:** Fixed a bug where in some scenarios Mail Queue entries for Digest Notifications that should have been held for sending later were not being held and were also not being sent. They also would not have shown up in the Mail Queue Event Log. This bug was found and fixed during the codebase restructuring. Props @jaswsinc. See [Issue #150](https://github.com/websharks/comment-mail/issues/150) and additional discussion in [Issue #173](https://github.com/websharks/comment-mail/issues/173#issuecomment-225215333).

Those two, plus the bug fixed in https://github.com/websharks/comment-mail/issues/194, makes me feel comfortable closing this GitHub issue. I also ran a few more tests on the dev branch (after fixing #194) and I haven't had any trouble with digest notifications.

Thank you to every for all the help testing and debugging this!

**Comment by jaswsinc** [comment]
@raamdev writes...

> So they would just disappear? I.e., a subscriber simply wouldn't receive the notifications they were expecting when new comments were posted?

That's correct, yes.

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#173).
