### ISSUE TITLE
Restore Default Options doesn't restore default options

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#181]
Testing the dev branch (as of 2015-12-15) of Comment Mail Pro, clicking "Restore Default Options" doesn't actually restore any default options. You can test this by enabling the plugin or disabling data safeguards, saving options, and then clicking "Restore Default Options". The defaults (Comment Mail disabled, Data Safeguards enabled) should be restored, but they are not.

**Comment by raamdev** [comment]
This probably also affects Comment Mail Lite, but I haven't confirmed yet.

**Comment by jaswsinc** [comment]
Try changing [this line](https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/includes/classes/utils-url.php#L584). Instead of `'1'` use:

```php
$args = array(__NAMESPACE__ => array('restore_default_options' => time()));
```

_I think this is a browser caching quirk. The redirection is getting cached._

**Comment by raamdev** [comment]
> I think this is a browser caching quirk. The redirection is getting cached.

I think you're right. I realized I was testing on my personal site, where there are quite a few plugins. I just tested on my clean install and the Restore Defaults works fine.

**Comment by raamdev** [comment]
> Try changing this line. Instead of '1' use:

Confirmed. This fixes the issue.

**Comment by raamdev** [comment]
@renzms Could you submit a PR for me? For both Pro and Lite.

**Comment by renzms** [comment]
@raamdev PRs submitted!

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Bug Fix**: Fixed a bug with "Restore Default Options" that was introducing a browser quirk that was preventing the default options from being restored. Props @renzms. See [Issue #181](https://github.com/websharks/comment-mail/issues/181).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Bug Fix**: Fixed a bug with "Restore Default Options" that was introducing a browser quirk that was preventing the default options from being restored. Props @renzms. See [Issue #181](https://github.com/websharks/comment-mail/issues/181).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#181).
