### ISSUE TITLE
"Comment Mail is disabled" notice margin is missing

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#186]
The `.notice-warning` class that is used for the "Comment Mail is disabled" notice needs the following style to fix alignment issues:

```css
margin: 1.25em 1.25em 1.25em .25em;
```

![2015-12-20_22-16-28](https://cloud.githubusercontent.com/assets/53005/11922732/c2d52b6e-a767-11e5-812e-e92b00d939b7.png)
![2015-12-20_22-16-48](https://cloud.githubusercontent.com/assets/53005/11922733/c3f06a9a-a767-11e5-9102-7625ea41e103.png)

**Comment by raamdev** [comment]
Note that this needs to be changed in both Comment Mail Lite and Comment Mail Pro.

**Comment by renzms** [comment]
PRs submitted! :+1:

**Comment by raamdev** [comment]
@renzms Thank you! I tested your PR and confirmed the Disabled notice is now aligned properly:

![2015-12-23_10-46-18](https://cloud.githubusercontent.com/assets/53005/11979579/7b891c50-a962-11e5-9738-af8aceca0e61.png)

**Comment by raamdev** [comment]
One thing I did notice during testing is that when you visit the Subscribe to Comments Reloaded options page, the StCR menu at the top clashes with these two Dashboard notices generated by Comment Mail:

![2015-12-23_10-42-33](https://cloud.githubusercontent.com/assets/53005/11979592/9afd85d0-a962-11e5-8e48-45d3928a1bf8.png)
![2015-12-23_10-42-53](https://cloud.githubusercontent.com/assets/53005/11979597/9ce277e8-a962-11e5-8164-e4242981d1e7.png)

This is really the fault of StCR and not Comment Mail, however given that new Comment Mail users who are migrating from StCR are likely to visit their StCR options page, I feel we should at least attempt to fix this clash to make the issue not quite as obvious. 

I'm pushing a fix to the PRs submitted by @renzms that will resolve this issue on the StCR options page:

![2015-12-23_10-49-28](https://cloud.githubusercontent.com/assets/53005/11979627/de367938-a962-11e5-92fd-8e96f0955fdf.png)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Bug Fix**: Fixed a UI bug where some of the Dashboard notices generated by Comment Mail were either misaligned or were clashing with the Subscribe to Comments Reloaded options menu. Props @renzms. See [Issue #186](https://github.com/websharks/comment-mail/issues/186).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Bug Fix**: Fixed a UI bug where some of the Dashboard notices generated by Comment Mail were either misaligned or were clashing with the Subscribe to Comments Reloaded options menu. Props @renzms. See [Issue #186](https://github.com/websharks/comment-mail/issues/186).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#186).

**Comment by Reedyseth** [comment]
Guys just FYI,

This Dashes are removed and included on my latest changes of StCR.

**Comment by raamdev** [comment]
@Reedyseth Can you point me to the commit on GitHub where you made that change in StCR?

**Comment by Reedyseth** [comment]
> Can you point me to the commit on GitHub where you made that change in StCR?

Sure, they are on a development branch on this commit https://github.com/stcr/subscribe-to-comments-reloaded/commit/ec65388243c348299f06a6615b8e4e63adc752ad

@ the file subscribe-to-comments-reloaded/style.css

**Comment by jaswsinc** [comment]
> This Dashes are removed and included on my latest changes of StCR.

Copy that. Thanks.

**Comment by raamdev** [comment]
@Reedyseth The problem isn't the dashed style; the problem is that the `<h2>` element that the StCR links are inside are overflowing onto Divs that show up underneath it.

I've opened a new GitHub issue with screenshots on the StCR repo, along with a suggested way of fixing the problem (that I've tested); see https://github.com/stcr/subscribe-to-comments-reloaded/issues/158.
