### ISSUE TITLE
Show installed version number on plugin options panels

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#187]
It would be nice to show the installed plugin version right inside the plugin options page along with a link to [the changelog](http://comment-mail.com/changelog/):

![2015-12-20_22-27-03](https://cloud.githubusercontent.com/assets/53005/11922874/48681d3a-a769-11e5-87c7-531b17ad4c39.png)

**Comment by kristineds** [comment]
@raamdev Do you want to add it in the same way as what was done with ZC?
- show both the installed version number and the 'latest' version number, if different. 
- show something like "Upgrade now" if there's a newer version.

On a different note, I feel like all those options below the Comment Mail logo feels a bit crowded, imo. :) What you have with ZC looks more organized and clean (i.e. the options for Pro Upgrade, Newsletter, Preview Pro features are placed on the upper right side). cc @jaswsinc

**Comment by raamdev** [comment]
> Do you want to add it in the same way as what was done with ZC?

Yes, that sounds great!

> On a different note, I feel like all those options below the Comment Mail logo feels a bit crowded, imo. :) What you have with ZC looks more organized and clean (i.e. the options for Pro Upgrade, Newsletter, Preview Pro features are placed on the upper right side). cc @jaswsinc

I totally agree. That has been bugging me for awhile. It feels like the least-polished part of Comment Mail that you use on a regular basis (and the first time you use it, those options are _not_ obvious at all--we improved this in https://github.com/websharks/comment-mail/issues/112). 

What I'd really love to see in place of what we have now is a tabbed system, something that looks like this but also includes the icons that we have now:

![2016-01-02_12-29-23](https://cloud.githubusercontent.com/assets/53005/12075390/ca557012-b14c-11e5-9acf-562d18c3f404.png)

Many plugins use a similar tabbed style, StCR and WP Super Cache being the two that immediately come to mind, so users are likely to already be familiar with it.

@jaswsinc Any objection to implementing a tabbed-style for those options?

**Comment by jaswsinc** [comment]
@raamdev Sounds cool. I have no objections.

**Comment by raamdev** [comment]
After putting a bit more thought into this, my feeling now is that we don't need a tabbed system at all. In fact, we can just clean things up so that there aren't so many items there.

![2016-01-03_13-54-11](https://cloud.githubusercontent.com/assets/53005/12080255/4c8e0c20-b223-11e5-9f90-aebe0a6c1076.png)

Instead of turning those items into a tabbed system, why don't we just _remove_ the items that really don't belong there and use something more like what we have in ZenCache:

![2016-01-03_14-02-35](https://cloud.githubusercontent.com/assets/53005/12080256/4eb9a464-b223-11e5-8ac5-fbf438d787e7.png)

**Comment by kristineds** [comment]
@jaswsinc @raamdev I was able to move the sub-section menu items but I'm having a hard time adding the version number and Pro Updater link on the PRO version. Would need your guidance on this. :) 

I have this so far..

- To display plugin version number: After [this line](https://github.com/websharks/comment-mail-pro/commit/64d6bdc3cb0ae8f6c43a74c553092f71d378aea6#diff-59e87032f4a4db38437327baf803be0fR4352), add this: 
```php
$heading .= '  <div class="pmp-version">'."\n";
$heading .= '     <span> '.__('%1$s&trade; Pro v%2$s', $this->plugin->text_domain), esc_html($this->plugin->name), esc_html($this->plugin->version).'</span>'."\n";
$heading .= '  </div>'."\n";
```

- To display Pro Updater Link: After [this line](https://github.com/websharks/comment-mail-pro/commit/64d6bdc3cb0ae8f6c43a74c553092f71d378aea6#diff-59e87032f4a4db38437327baf803be0fR4349), add this:
```php
if(!$this->plugin->is_pro) // Display pro updater
{
$heading .= '  <a href="'.esc_attr($this->plugin->utils_url->pro_updater_menu_page_only()).'"'.
($this->plugin->utils_env->is_pro_updater_menu_page_only() ? ' class="pmp-active"' : '').'>'.
'<i class="fa fa-magic"></i> '.__('Pro Updater', $this->plugin->text_domain).'</a>'."\n";
}

```

**Comment by jaswsinc** [comment]
@kristineds It looks all you're missing here is the `sprintf()` call.

```php
$heading .= '  <div class="pmp-version">'."\n";
$heading .= '     <span> '.sprintf(__('%1$s&trade; Pro v%2$s', $this->plugin->text_domain), esc_html($this->plugin->name), esc_html($this->plugin->version)).'</span>'."\n";
$heading .= '  </div>'."\n";
```

See also: http://php.net/manual/en/function.sprintf.php

Note that `sprintf()` is what handles the `%1$s` and `%2$s` replacement codes.

**Comment by jaswsinc** [comment]
@kristineds The function does not exist to my knowledge.

```
$this->plugin->utils_env->is_pro_updater_menu_page_only()
```

You can use this instead, which does exist:

```php
$this->plugin->utils_env->is_menu_page(__NAMESPACE__.'_pro_updater')
```

See also: https://github.com/websharks/comment-mail-pro/blob/8d9fce347e009ff6d6d2e5946581e22c4338af60/comment-mail-pro/includes/classes/utils-env.php#L87-L120

**Comment by jaswsinc** [comment]
@kristineds Just checking in here. Anything not clear enough? If so just give us a shout! :-)

**Comment by raamdev** [comment]
# Lite

![2016-02-08_10-43-07](https://cloud.githubusercontent.com/assets/53005/12890264/f77adf2a-ce50-11e5-8f7e-940b43e62f49.png)


# Pro
![2016-02-08_10-43-44](https://cloud.githubusercontent.com/assets/53005/12890272/faf5ea32-ce50-11e5-9f28-efe4293d8542.png)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Added the installed version number to the plugin options pages. Props @kristineds. See [Issue #187](https://github.com/websharks/comment-mail/issues/187).
- **Enhancement**: Improved the organization of navigation links on the plugin options pages. Props @kristineds. See [Issue #187](https://github.com/websharks/comment-mail/issues/187).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Added the installed version number to the plugin options pages. Props @kristineds. See [Issue #187](https://github.com/websharks/comment-mail/issues/187).
- **Enhancement**: Improved the organization of navigation links on the plugin options pages. Props @kristineds. See [Issue #187](https://github.com/websharks/comment-mail/issues/187).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#187).
