### ISSUE TITLE
Cron event disappears in some scenarios: _cron_comment_mail_queue_processor

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#194]
This bug was originally found in the ZenCache plugin and reported in https://github.com/websharks/zencache/issues/613#issuecomment-162317215. Comment Mail suffers from this same bug:

> **Here's what's happening:** [When `wp_schedule_event()`](https://github.com/WordPress/WordPress/blob/4.3.1/wp-includes/cron.php#L132) is called via `wp_reschedule_event()` (_after_ ZenCache has been uninstalled: remember, this only occurs when rescheduling the event after the plugin has been uninstalled), it passes the custom `every15m` schedule to `wp_schedule_event()`, which then gets a list of schedules via `wp_get_schedules()` and since ZenCache has been deleted and no longer [adds the custom `every15m` schedule via `add_filter('cron_schedules', ...)`](https://github.com/websharks/zencache-pro/blob/151114/src/includes/classes/Plugin.php#L520), the `wp_schedule_event()` function finds that `every15m` no longer exists and [doesn't reschedule the `_cron_zencache_auto_cache` event](https://github.com/WordPress/WordPress/blob/4.3.1/wp-includes/cron.php#L76-L77).

Comment Mail [creates](https://github.com/websharks/comment-mail/blob/151224/comment-mail/plugin.inc.php#L2387-L2388) and [uses](https://github.com/websharks/comment-mail/blob/151224/comment-mail/plugin.inc.php#L882-L903) two (2) custom cron schedules (actually, only the `every5m` scheduled is used; the `every15m` schedule is not currently used).

So, if you ever install Comment Mail and then delete it (without disabling Data Safeguards), it's possible that the `_cron_comment_mail_queue_processor` cron event will get deleted and will not be recreated the next time you install Comment Mail. 

The only way to ensure the `_cron_comment_mail_queue_processor` gets recreated is to disable Data Safeguards (**Comment Mail → Config. Options → Data Safeguards**), then delete the Comment Mail plugin.

**Comment by raamdev** [comment]
Note that I **don't** believe this is related to #192 (see https://github.com/websharks/comment-mail/issues/192#issuecomment-167335709).

**Comment by jaswsinc** [comment]
:+1: Good catch. Yep, probably impacts CM too.

**Comment by raamdev** [comment]
Next Release Changelog:

- **Bug Fix**: Fixed a bug where the cron job for the Queue Processor could get deleted and never recreated, which would result in notifications getting stuck in the Mail Queue and not being sent out. If you ever installed Comment Mail and then deleted it (without first disabling Data Safeguards), and then installed Comment Mail again, you were probably affected by this issue. This release fixes the issue and makes the cron setup more robust. Props @kristineds, @renzms, @jaswsinc, and @IvanRF for help testing. See [Issue #194](https://github.com/websharks/comment-mail/issues/194) and [Issue #173](https://github.com/websharks/comment-mail/issues/173).

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#194).
