### ISSUE TITLE
Remove unnecessary quotes from front-end pages and email templates

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#201]
@RealDavidoff writes in https://github.com/websharks/comment-mail/issues/199#issuecomment-170415300...
> 1) Return to "website name" - Why the " " ?? Leave out, makes no sense, you are not quoting us. Same here: You'll be notified about all comments/replies to: "German Shepherd Dog Training" - it's linked, quotes are needless if not irritating (quotes are used to, well, QUOTE someone!)

**Comment by renzms** [comment]
@raamdev  Hi Raam, PR submitted, do I need to repeat for Pro? Or do they have the same templates?

**Comment by jaswsinc** [comment]
I just want to go on record as disagreeing with this change request. It's common practice to quote titles, particularly when it would be easy to misunderstand that it is a title. Since a Post can potentially have a strange title, quoting it helps to ensure that someone can see it is all one entity; i.e., a title.

If quotes are not desirable, then I suggest an alternative approach. In either case though, it should be easy to see that the title is a full string of words that are separate from the wording used around it.

Imagine a Post with the title...

```
Return to Paradise
```

Now incorporate that into a sentence as seen above...

```
Return to "Return to Paradise"
```

is far less confusing than...

```
Return to Return to Paradise
```

_Removing the quotes leads to confusion._

**Comment by jaswsinc** [comment]
I suggest the use of italics instead of quotes.

**Comment by RealDavidoff** [comment]
To repeat: I was saying there must not be any quotes around the website NAME and similar items. While "It's common practice to quote titles", yes, it's misleading to "quote" a NAME (here the website). Have you ever seen, say the NY Times etc, to write:
According to "Bill Gates" quotes around names are helpful.
:-)
You only quote, well, QUOTES. S.o. said sth. Or here, s.o. wrote sth, eg a title, yes.
Clear now?

**Comment by raamdev** [comment]
@renzms Please update your PRs (yes, we need PRs for Lite and Pro) with the following:

- Add `<em></em>` tags wherever there were quotes to help emphasis the Title / Blog Name now that the quotes are gone.

**Comment by RealDavidoff** [comment]
It's ridiculous, but I never saw ANY mention of websharks FROM websharks where you felt the need to put your own name in italics or in quotes!

what a time-waste for me when trying to help/open eyes...

**Comment by raamdev** [comment]
@RealDavidoff What is the problem? You asked us to fix something and we're fixing it. It's hard to help when you don't want to see that we're doing exactly as you asked.

**Comment by RealDavidoff** [comment]
But you aren't. Just read it tomorrow, afresh.

**Comment by jaswsinc** [comment]
@RealDavidoff If my comment felt personal, it was not. I assure you. I respect and appreciate your feedback here, and you have pointed out several ways that we can improve. Props!

However, working through issues in code, contemplating other angles, these are things that require various people and respect for differing opinions. Statements like, _"It's ridiculous"_, and _"what a time-waste for me"_, is not you looking at the problem objectively and showing respect for the feedback that I have about this. This is about the end result. No quotes, italics instead. That's an improvement. One that is coming about as a result of feedback we got from you. Thanks!

You replied...

> To repeat: I was saying there must not be any quotes around the website NAME and similar items. While "It's common practice to quote titles", yes, it's misleading to "quote" a NAME (here the website). Have you ever seen, say the NY Times etc, to write:

It's the _similar items_ that we are working with right.

For instance, you suggested previously...

> Same here: You'll be notified about all comments/replies to: "German Shepherd Dog Training"

Right now we are working with titles.

**Comment by renzms** [comment]
> Please update your PRs (yes, we need PRs for Lite and Pro) with the following:
> 
> Add <em></em> tags wherever there were quotes to help emphasis the Title / Blog Name now that the quotes are gone.

Got it, will update for Pro and Lite and use italics in place of the quotes for emphasis.

**Comment by raamdev** [comment]
@RealDavidoff writes...
> But you aren't. Just read it tomorrow, afresh.

Yes, please read it afresh tomorrow and you'll see that we are, in fact, doing exactly as you asked: Removing quotes. They are being replaced with `<em>` tags, which are not quotes. The `<em>` tags will make the titles italic so that they stand separate from any text that may proceed them.

**Comment by renzms** [comment]
@raamdev 

Submit PR for both Pro and Lite. Thanks!

**Comment by raamdev** [comment]
@renzms It looks like you missed the `/includes/templates/type-a/` templates in the Pro version in [this PR](https://github.com/websharks/comment-mail-pro/pull/49). I realized that after merging the PR, so please open another PR, `feature/201a`, and submit those same changes except for `type-a` templates.

**Comment by renzms** [comment]
@raamdev 

Hi, updated for type A. Ready for review, thanks!

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Improved front-end pages and email templates by using `<em>` (emphasis) tags instead of quotation marks in various areas. Props @RealDavidoff @renzms. See [Issue #201](https://github.com/websharks/comment-mail/issues/201).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Improved front-end pages and email templates by using `<em>` (emphasis) tags instead of quotation marks in various areas. Props @RealDavidoff @renzms. See [Issue #201](https://github.com/websharks/comment-mail/issues/201).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#201).
