### ISSUE TITLE
External links should always open in new tab/window, internal links should not

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#202]
@RealDavidoff writes in https://github.com/websharks/comment-mail/issues/199#issuecomment-170415300...
> 2) The "Subscribe without commenting" and "Manage my subscriptions" links open in a new window/tab. This doesn't make sense, and is needless: If user doesn't comment then he doesn't click the send-comment button at the end of the article that he has just finished reading. So keep him in the same window/tab.
> Most sensible is: Always open a NEW window/tab for EXTERNAL links, and whenever the user wants/needs to continue reading (or filling in data) on the current page but shall be able to see additional information on another internal page. Links before the end of an article likely meet this criterion (if the article is good enough!), but if the linked NEW article is standalone (not just helping to understand the current page) then keeping the reader in the SAME window/tab is least annoying. - And obviously, links that open a new window/tab should be marked as such. This is brilliantly done in s2m, but not in cm.

**Comment by jaswsinc** [comment]
@kristineds This looks like an issue that you could outline.

Search the template files for `target="_blank"` and try to locate those links which currently open in a new window. We should remove `target="_blank"`. I agree with that.

**Comment by raamdev** [comment]
> try to locate those links which currently open in a new window.

And vice versa, i.e., all links should be reviewed and any links that _are_ external links should have `target="_blank"` _added_ to them.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Waiting for feedback on this outline. :)  cc@renzms
---

## Next Actions

- New feature branch in the `websharks/comment-mail-pro` repo.
- Searching the template files for: `target="_blank"`.  Removing `target="_blank"` from internal links and adding `target="_blank"` on external links. 

- Remove `target="_blank"` from these internal links 

  | Template File | Internal Links |
  | --- | --- |
  | `/comment-mail-pro/includes/templates/type-s/site/comment-form/snippet/sub-ops.php` | https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-s/site/comment-form/snippet/sub-ops.php#L10 |
  |  | https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-s/site/comment-form/snippet/sub-ops.php#L10 |
  | `/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php` | https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php#L74 |
  |  | https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php#L76 |
  | `comment-mail-pro/includes/classes/menu-page-table-base.php ` | https://github.com/websharks/comment-mail-pro/blob/c466208f9a8fe0d824501795ca2afc32f60b11fd/comment-mail-pro/includes/classes/menu-page-table-base.php#L2008 |
  |  | https://github.com/websharks/comment-mail-pro/blob/c466208f9a8fe0d824501795ca2afc32f60b11fd/comment-mail-pro/includes/classes/menu-page-table-base.php#L2044 |
  | `comment-mail-pro/plugin.inc.php`  | https://github.com/websharks/comment-mail-pro/blob/b5a67f413afabf0ce9ee91cd45288a7e81813047/comment-mail-pro/plugin.inc.php#L1738 |

- Add `target="_blank"` on these external links 

  | Template File | External Links |
  | --- | --- |
  | `comment-mail-pro/includes/stcr.php ` | https://github.com/websharks/comment-mail-pro/blob/a4213992bf987091ab18431b2be7916d1c5bee75/comment-mail-pro/includes/stcr.php#L98 |

- Submit PR for review.

---

- Repeat in the Lite version of Comment Mail.

**Comment by jaswsinc** [comment]
@kristineds Looks good to me. All except for https://github.com/websharks/comment-mail-pro/blob/b5a67f413afabf0ce9ee91cd45288a7e81813047/comment-mail-pro/plugin.inc.php#L1738

That is an external link, because it moves you from the installation site to comment-mail.com.

**Comment by kristineds** [comment]
> Looks good to me. All except for https://github.com/websharks/comment-mail-pro/blob/b5a67f413afabf0ce9ee91cd45288a7e81813047/comment-mail-pro/plugin.inc.php#L1738

@jaswsinc Copy that. I have updated the outline above. cc @renzms

**Comment by renzms** [comment]
@raamdev @jaswsinc Ready for review. Thanks! cc @kristineds

**Comment by raamdev** [comment]
@kristineds @renzms Nice work collaborating on this one! Reviewed and merged.

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Improved the way some links work by opening on-site links in current tab, and external links in new tab. Props @RealDavidoff @kristineds @renzms. See [Issue #202](https://github.com/websharks/comment-mail/issues/202).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Improved the way some links work by opening on-site links in current tab, and external links in new tab. Props @RealDavidoff @kristineds @renzms. See [Issue #202](https://github.com/websharks/comment-mail/issues/202).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#202).
