### ISSUE TITLE
Add New Subscription form should pre-populate name/email fields when possible

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#204]
When Subscribing Without Commenting, the Add New Subscription form should pre-populate the Name and Email address fields when possible (i.e., when a cookie exists from previously leaving a comment, or when the user is logged in):

![2016-01-11_10-49-18](https://cloud.githubusercontent.com/assets/53005/12238273/2f3dff02-b851-11e5-8e70-2cb3b103043a.png)

![2016-01-11_10-49-37](https://cloud.githubusercontent.com/assets/53005/12238260/1ea401be-b851-11e5-999b-851d0b45a6fa.png)

---

This was pointed out by @RealDavidoff here: https://github.com/websharks/comment-mail/issues/199#issuecomment-170415300

**Comment by jaswsinc** [comment]
## Next Actions

- New feature branch in the `websharks/comment-mail-pro` repo.

- After [this line](https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/includes/classes/sub-manage-sub-form-base.php#L254) add the following:

  ```php
  if(!$this->is_edit && !static::$processing && in_array($key_prop, array('fname', 'lname', 'email'), TRUE)) {
      // We can try to autofill fname, lname, email for new subscriptions.
      $current = wp_get_current_commenter();

      switch($key_prop) {
          case 'fname':
              if(!empty($current['comment_author'])) {
                  return $this->plugin->utils_string->first_name((string)$current['comment_author']);
              }
              break;

          case 'lname':
              if(!empty($current['comment_author'])) {
                  return $this->plugin->utils_string->last_name((string)$current['comment_author']);
              }
              break;

          case 'email':
              if(!empty($current['comment_author_email'])) {
                  return (string)$current['comment_author_email'];
              }
              break;
      }
  }
  if(!$this->is_edit && !static::$processing && in_array($key_prop, array('fname', 'lname', 'email'), TRUE)) {
      // We can try to autofill fname, lname, email for new subscriptions.
      $current = wp_get_current_user();

      switch($key_prop) {
          case 'fname':
              if(!empty($current->first_name)) {
                  return $this->plugin->utils_string->first_name((string)$current->first_name);
              }
              break;

          case 'lname':
              if(!empty($current->last_name)) {
                  return $this->plugin->utils_string->last_name((string)$current->last_name);
              }
              break;

          case 'email':
              if(!empty($current->email)) {
                  return (string)$current->email;
              }
              break;
      }
  }
  ```

- Submit PR for review.

---

- Repeat in Lite version of the software also.

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: When Subscribing Without Commenting, the Add New Subscription form now pre-populates the Name and Email address fields whenever possible. Props @kristineds. See [Issue #204](https://github.com/websharks/comment-mail/issues/204).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: When Subscribing Without Commenting, the Add New Subscription form now pre-populates the Name and Email address fields whenever possible. Props @kristineds. See [Issue #204](https://github.com/websharks/comment-mail/issues/204).

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#204).
