### ISSUE TITLE
Improve naming consistency of delivery options

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#206]
@RealDavidoff writes in https://github.com/websharks/comment-mail/issues/199#issuecomment-170415300
> 7) "Delivery option" - once you say "asap", then you say "instantaneous". Why use different words for the same thing?

**Comment by RealDavidoff** [comment]
Raam, there is a related bug, as follows:
![raam-error1](https://cloud.githubusercontent.com/assets/11789004/12323793/1b2dccc4-bab6-11e5-96ee-567ad65eb712.png)
![raam-error2](https://cloud.githubusercontent.com/assets/11789004/12323795/1b34954a-bab6-11e5-971c-ec300cb9ae60.png)
![raam-error3](https://cloud.githubusercontent.com/assets/11789004/12323794/1b327166-bab6-11e5-8d6b-2f1b203ed7f8.png)

**Comment by RealDavidoff** [comment]
you can also see the mini text-size there. solution would be as described earlier: define it, to make sure.

**Comment by raamdev** [comment]
@RealDavidoff I'm not able to reproduce that bug. Where are you testing that? I just tried it on a regular comment form on my test site and changing to "no, do not subscribe" and then back to "yes, all comments/replies" had no effect on the delivery options box... it still works as expected.

**Comment by RealDavidoff** [comment]
It's because you didn't start off at the SETTINGS page ;-)
We wanted default: No, do not subscribe... Try it!

**Comment by raamdev** [comment]
@RealDavidoff I'm still not able to reproduce any problem.

With my Settings configured with "No, do not subscribe" as the default:

![2016-01-14_10-11-45](https://cloud.githubusercontent.com/assets/53005/12327994/5fbdf508-baa7-11e5-9c77-0903272eaa58.png)

All of the options on the Comment Form work properly:

![2016-01-14_10-12-12](https://cloud.githubusercontent.com/assets/53005/12327999/675f8240-baa7-11e5-9bda-3d1b21cc7328.png)
![2016-01-14_10-12-19](https://cloud.githubusercontent.com/assets/53005/12328001/687c73b8-baa7-11e5-9035-7f9363974c20.png)
![2016-01-14_10-12-26](https://cloud.githubusercontent.com/assets/53005/12328003/69bd1070-baa7-11e5-86db-883e55a57360.png)

**Comment by jaswsinc** [comment]
@raamdev Which do we prefer?

- asap
- instantly

I'll vote for **instantly**, since it is a word that is more easily translated than the **asap** acronym.

**Comment by jaswsinc** [comment]
@kristineds This looks like an issue you could try to outline once Raam replies back.

**Comment by raamdev** [comment]
Yes, I agree that `instantly` is the better option.

**Comment by jaswsinc** [comment]
## Next Actions

- New feature branch in the `websharks/comment-mail-pro` repo.

- Search the entire codebase for the word `asap`: https://github.com/websharks/comment-mail-pro/search?p=1&q=asap&utf8=%E2%9C%93

- Note that are there two different ways this is used in the codebase.

  - In one form, it is used as a hard-coded identifier that assigns a specific delivery type in the DB.

  - In the second form, there are some places where **asap** is used in the UI or in translation routines that result in a GUI presentation of the word **asap**.

    - It is the second form that you should work to update. We want to use the word **instantly** instead of the acronym **asap**.

- Submit PR for review.

---

Once approved, repeat in the lite version of the software.

---

Examples of a hard-coded delivery type status code that should NOT change.

- https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/includes/classes/sub-injector.php#L115

- https://github.com/websharks/comment-mail-pro/blob/21ec1833c0abb440b92ce0cd91c8554c3ac10728/comment-mail-pro/includes/templates/type-a/site/sub-actions/confirmed.php#L145

Examples of a place where the word **asap** is used in HTML markup that is presented in a GUI.

- https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/classes/utils-i18n.php#L258

- https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-a/site/sub-actions/manage-sub-form.php#L246

**Comment by jaswsinc** [comment]
@kristineds I outlined this for Renz.

**Comment by kristineds** [comment]
> Maybe you can review his PR :-)

Sure thing! I'll just wait for @renzms to submit it . :)

**Comment by renzms** [comment]
@kristineds 
cc: @jaswsinc 

Ready for check! Thanks!

**Comment by kristineds** [comment]
@renzms Quoting what Jason said regarding POT translation files. :) 

> **FYI**: You don't need to edit anything in the POT translation file. That file is auto-generated before each release of the software. So any edits that you make there will get wiped away anyway. No harm in editing the file, but just so you know. Don't worry about that file. Saves time.

---

@jaswsinc: I'm seeing these files that needs to be updated as well, i.e. change `asap` to `instantly`. Could you please check ? :) cc @raamdev

| Template File | Link to Codebase |
| --- | --- |
| `/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php`  | https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php#L61 |
|  | https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php#L59 |
| `/comment-mail-pro/includes/templates/type-s/site/comment-form/sub-ops.php` | https://github.com/websharks/comment-mail-pro/blob/78ccc101b44deba820bea28875f3f567b45baea6/comment-mail-pro/includes/templates/type-s/site/comment-form/sub-ops.php#L100 |
| `/comment-mail-pro/includes/classes/utils-markup.php` | https://github.com/websharks/comment-mail-pro/blob/c466208f9a8fe0d824501795ca2afc32f60b11fd/comment-mail-pro/includes/classes/utils-markup.php#L571 |

**Comment by jaswsinc** [comment]
> https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php#L61

This shows **instantly**, even though the hard-coded DB value is `asap`. It's OK to leave this as-is.

---

> https://github.com/websharks/comment-mail-pro/blob/28bbe8b88b59a77e3632938d5c72314ff86488a2/comment-mail-pro/includes/templates/type-a/site/comment-form/sub-ops.php#L59

This is just a code comment, and it references the hard-coded DB value. So you can leave this as-is.

---

> https://github.com/websharks/comment-mail-pro/blob/78ccc101b44deba820bea28875f3f567b45baea6/comment-mail-pro/includes/templates/type-s/site/comment-form/sub-ops.php#L100

This shows **instantly**, even though the hard-coded DB value is `asap`. It's OK to leave this as-is.

---

> https://github.com/websharks/comment-mail-pro/blob/c466208f9a8fe0d824501795ca2afc32f60b11fd/comment-mail-pro/includes/classes/utils-markup.php#L571

```
$this->plugin->utils_i18n->deliver_label('asap')
```

Once this PR is merged, that translation utility should automatically convert `asap` into **instantly**.

---

The word `asap` is used internally, and it's one of the enumerable values in the DB for delivery type. So that term is still going to be a part of the codebase. Only the UI representation of that value is changing, so I think those places you pointed out are OK to leave as-is.

@kristineds Have you run this branch through any tests inside WordPress? Were any of the issues you noted above causing problems from the UI perspective whenever you tested?

**Comment by jaswsinc** [comment]
@kristineds It might help if you ask Renz to take some screenshots to make reviewing a little easier.

**Comment by raamdev** [comment]
@kristineds This is still waiting for a review from you. See also the PR Renz submitted https://github.com/websharks/comment-mail-pro/pull/50.

@renzms Also, noting here that we'll need a PR for the Lite version as well. When a PR will be needed for both versions, it's best to always work on those side-by-side, i.e., to make the changes at the same time for both the Lite and the Pro version, otherwise it becomes easy to lose track of what changed where. :smile:

**Comment by kristineds** [comment]
@raamdev I've posted my review here. :)  https://github.com/websharks/comment-mail-pro/pull/50#issuecomment-178574896

**Comment by renzms** [comment]
@raamdev 
> When a PR will be needed for both versions, it's best to always work on those side-by-side, i.e., to make the changes at the same time for both the Lite and the Pro version, otherwise it becomes easy to lose track of what changed where.

Ok, will do. Just following the instructions in order of what @jaswsinc laid out earlier above:

>Submit PR for review.
 > Once approved, repeat in the Lite version of the software.

Updating now and working on Lite version, thanks @kristineds

**Comment by renzms** [comment]
There were 6 additional instances of  `asap`, I removed those as well as the line about `(aka: instantly)`, as it would no longer make sense once the word was replaced with `instantly`. cc @kristineds

**Comment by raamdev** [comment]
> Note that there are two different ways this is used in the codebase.
> 
> In one form, it is used as a hard-coded identifier that assigns a specific delivery type in the DB.

@jaswsinc Is the only reason we're not changing _all_ uses of `asap` (including those used in the database) to `instantly` because that would require updating the database for existing Comment Mail installations when they upgrade? 

It seems to me that changing _all_ occurrences of `asap` to `instantly` and then creating a version upgrade routine that converts any existing uses in the database, would be better than continuing to have two ways of referring to the same thing (i.e., it adds to confusion in the code).

**Comment by jaswsinc** [comment]
> @jaswsinc Is the only reason we're not changing all uses of asap (including those used in the database) to instantly because that would require updating the database for existing Comment Mail installations when they upgrade?

That is correct, yes.

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Improved the consistency of how we refer to the "instant" delivery option by replacing any occurrences "asap" with "instantly". These names were previously being mixed. We now use "instantly". Props @RealDavidoff @renzms @kristineds. See [Issue #206](https://github.com/websharks/comment-mail/issues/206).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Improved the consistency of how we refer to the "instant" delivery option by replacing any occurrences "asap" with "instantly". These names were previously being mixed. We now use "instantly". Props @RealDavidoff @renzms @kristineds. See [Issue #206](https://github.com/websharks/comment-mail/issues/206).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#206).
