### ISSUE TITLE
Add Subscription Form: Remove "If empty, you'll be subscribed to all comments" note

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#207]
![2016-01-11_11-01-37](https://cloud.githubusercontent.com/assets/53005/12238641/fef4f7ea-b852-11e5-832f-7ba12d00761c.png)

This note not relevant as there's an option for "All Comments/Replies" and it's not possible to make the field empty. This note should be removed.

---

Pointed out by @RealDavidoff in https://github.com/websharks/comment-mail/issues/199#issuecomment-170415300.

**Comment by kristineds** [comment]
@raamdev Submitted Pull Request for both Pro and Lite

- [Pull Request for Comment Mail Lite](https://github.com/websharks/comment-mail/pull/215)
- [Pull Request for Comment Mail Pro](https://github.com/websharks/comment-mail-pro/pull/48)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Removed an irrelevant and confusing note from the Add New Subscription page. Props @kristineds @RealDavidoff. See [Issue #207](https://github.com/websharks/comment-mail/issues/207).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Removed an irrelevant and confusing note from the Add New Subscription page. Props @kristineds @RealDavidoff. See [Issue #207](https://github.com/websharks/comment-mail/issues/207).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#207).
