### ISSUE TITLE
Fix "You are receiving this email because asked" spelling mistake in email templates

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#208]
@RealDavidoff writes in https://github.com/websharks/comment-mail/issues/199#issuecomment-170415300
> 11) "You are receiving this email because asked to be notified about all comments/replies to:" - because YOU asked

**Comment by kristineds** [comment]
@raamdev Submitted Pull Request for both Pro and Lite

- [CM Lite](https://github.com/websharks/comment-mail/pull/214)
- [CM Pro](https://github.com/websharks/comment-mail-pro/pull/47)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Bug Fix**: Fixed a spelling mistake in one of the default email templates. Props @kristineds @RealDavidoff. See [Issue #208](https://github.com/websharks/comment-mail/issues/208).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Bug Fix**: Fixed a spelling mistake in one of the default email templates. Props @kristineds @RealDavidoff. See [Issue #208](https://github.com/websharks/comment-mail/issues/208).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#208).
