### ISSUE TITLE
Stats Log Endpoint

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#221]
Endpoint URL should be updated to:
`https://stats.wpsharks.io/log`

https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/includes/classes/stats-pinger.php#L50

**Comment by jaswsinc** [comment]
@kristineds This is one you could tackle if you'd like. It's actually the same change in all three products.

This issue, plus these other two also:

- https://github.com/websharks/s2member/issues/858
- https://github.com/websharks/zencache/issues/661

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- Updated WebSharks stats log endpoint URL. Props @kristineds. See [Issue #221](https://github.com/websharks/comment-mail/issues/221).

**Comment by raamdev** [comment]
**Comment Mail v160213** has been released and includes changes from this GitHub Issue. See the [release announcement](http://comment-mail.com/comment-mail-v160213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#221).
