### ISSUE TITLE
Searching Subscriptions by full email address should always return associated subscriptions

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#226]
When searching for Subscriptions that belong to a specific email address, it should be possible to paste in a full email address, hit search, and see the results filtered to only subscriptions that match that exact email address.

This is likely the most common type of search when searching subscriptions (i.e., searching by email address; such as when doing the administrative task of manually removing someone who asked to be unsubscribed).

At present, the behavior doesn't seem to work as expected. When I put in an email address, it seems to find more results than it should.

**Comment by raamdev** [comment]
@jaswsinc You did a team video awhile back where you found the bug here and I just wanted to leave a comment with what you found: `sub_email:test@example.com` works, but `test@example.com` does not because [full-text searches are being done `IN BOOLEAN MODE`](https://github.com/websharks/comment-mail-pro/blob/161110-RC/src/includes/classes/MenuPageSubsTable.php#L345-L349), so the search results are more like Google rather than an exact match.

So we need to update the search algorithm so that it can detect when a full email address is being searched and then perform an exact match against the email table (e.g., how it's done when you search `sub_email:test@example.com`). 

Here's a link to the video on Slack: https://websharks.slack.com/archives/comment-mail/p1479172353000208

**Comment by jaswsinc** [comment]
Ah, thank you for that.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** Searching by email address alone should always narrow to the search to that specific email address and not result in any fuzzy or fulltext matching. See [Issue #226](https://github.com/websharks/comment-mail/issues/226).

**Comment by jaswsinc** [comment]
Searching by email address is now treated exactly the same as if you had searched for: `sub_email:test@example.com`. You can now do this with just the email address: `test@example.com`

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Confirmed Working

![screen shot 2016-12-13 at 3 15 41 pm](https://cloud.githubusercontent.com/assets/13220018/21130996/122d8e28-c147-11e6-82ff-2fef8de6ee0b.png)


Tested using Comment Mail v161210-RC Pro + Lite and searched for specific email address. Searching by email address works for Subscriptions.

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#226).
