### ISSUE TITLE
RC :: Enhancement :: Pro Preview Link

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#227]
The RC is looking really great! Fantastic work, great improvements!

---

To take the recent navigation bar improvements to the next step, in the Lite version, I suggest moving the **Pro Preview** link into the main navigation area. Or, if that's not desirable try to find a way to make this easier to see. In this particular plugin (because it's a set-it-and forget-it kind of plugin), that Pro Preview link seems important. Ideally, it would be impossible to install the free version and not see there are pro features as soon as you begin to explore what it has to offer; i.e., one of the first things that you see.

![2016-02-11_11-20-32](https://cloud.githubusercontent.com/assets/1563559/12989357/b202df3e-d0b1-11e5-992d-9912ebabea4d.png)

**Comment by raamdev** [comment]
I'm not sure when it happened, but it looks like this was done at some point recently:

![2016-03-16_12-11-15](https://cloud.githubusercontent.com/assets/53005/13819563/511ea02a-eb70-11e5-9c8a-8a2cc8361c1b.png)

However my feeling is that these two links should go _after_ "Email Templates" and "Site Templates":

![2016-03-16_12-13-09](https://cloud.githubusercontent.com/assets/53005/13819608/7c9117b0-eb70-11e5-9774-e5c2d7dab876.png)

Also, while working on this we need to fix an issue with those menu links colliding with the bar below them when the browser is resized:

![2016-03-16_12-14-05](https://cloud.githubusercontent.com/assets/53005/13819623/98425bb8-eb70-11e5-9690-b8cc8f37a41f.png)

**Comment by raamdev** [comment]
Related: https://github.com/websharks/comment-mail/issues/236

**Comment by renzms** [comment]
@raamdev 

From #236, I think that solves the smaller browser issue of the links overlapping. 

I tested with a smaller browser size and with the notifications on top. The links stay in place, please see screen:
![screen shot 2016-03-20 at 2 03 23 am](https://cloud.githubusercontent.com/assets/13220018/13899700/3d90f27e-ee40-11e5-9b0b-14efd8275257.png)

Here is my test with it at regular browser size:

![screen shot 2016-03-20 at 2 03 45 am](https://cloud.githubusercontent.com/assets/13220018/13899703/5c16b68e-ee40-11e5-9a7d-cdd0695de1a5.png)

Is that okay, or should the `Preview Pro Features` and `Pro Upgrade` be below the template links? It seems crowded when it extends all the way to the right with all the links on one line.

**Comment by raamdev** [comment]
@renzms I just built and tested Comment Mail Lite from the latest dev branch, which includes the work from https://github.com/websharks/comment-mail/issues/236, and I'm still seeing an issue (Google Chrome on OS X):

![2016-03-19_13-17-25](https://cloud.githubusercontent.com/assets/53005/13900121/0489c534-edd5-11e5-8bb9-c8bc1199e26c.png)

**Comment by renzms** [comment]
@raamdev 

Hmm, I'm also using Google Chrome on OS X:
```
Mac  System Version:	OS X 10.11.3 (15D21)
Chrome Version 49.0.2623.87 (64-bit)
```

> tested Comment Mail Lite

In your screenshot it says Comment Mail Pro, or is that just because of the Phing Build version?
Because in the Lite Version you should not be able to remove the logo as that's locked under a Pro Feature under **Misc. UI Settings**. Even when previewing that Pro Feature, it should not save as it is grayed out.

Were there any recent merges after you tested and reviewed #236, that may have overwritten something in the CSS?

**Comment by raamdev** [comment]
> In your screenshot it says Comment Mail Pro, or is that just because of the Phing Build version?

The menu item says 'Pro' because we haven't finished updating the unified codebase to strip out all Pro-related things during a build (see https://github.com/websharks/comment-mail/issues/237).

So I was testing the Lite build (`.~build/comment-mail/.~build/comment-mail.zip` after running `phing`). Is that what you were testing?

**Comment by renzms** [comment]
> So I was testing the Lite build (.~build/comment-mail/.~build/comment-mail.zip after running phing). Is that what you were testing?

Nope, I will test with that version then. One question though, if I'm testing the Lite version of it, should I remove the logo? As that's a Pro feature, not sure ifs automatically disabled since the Pro-related features are still in the build.

**Comment by raamdev** [comment]
The logo doesn't show up in the Lite version.

**Comment by raamdev** [comment]
@renzms FYI, I merged the latest from `000000-dev` into this branch, so you'll need to `git pull`.

----

The Pro version looks fine, but the Lite version still has some issues:

![2016-04-26_15-05-19](https://cloud.githubusercontent.com/assets/53005/14830782/754f549c-0bc0-11e6-8cd4-e60f2057f2e3.png)

**Comment by raamdev** [comment]
Next Release Changelog:

- **Enhancement**: Minor improvements to the Options Page menu links and positioning of the Pro Preview link. Props @renzms. See [Issue #227](https://github.com/websharks/comment-mail/issues/227).

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#227).
