### ISSUE TITLE
Remove lg & gt signs from email address - Subscription Meta Box

### ISSUE THREAD

**Issue by Reedyseth** [websharks/comment-mail#228]
On the Subscription Meta Box email addresses are wrap with with the gt and lt. The email address will look better by removing them.

![image](https://cloud.githubusercontent.com/assets/1228711/12999012/9824920a-d107-11e5-8aae-b50664d1fa46.png)

Result:

![image](https://cloud.githubusercontent.com/assets/1228711/12999057/255d26d2-d108-11e5-8228-c6539aa60a5e.png)

**Comment by jaswsinc** [comment]
@Reedyseth I agree. Although, take a look here: https://github.com/websharks/comment-mail/issues/231#issuecomment-183384154

**Comment by raamdev** [comment]
@Reedyseth Thank you. I'm closing this in favor of https://github.com/websharks/comment-mail/issues/231#issuecomment-183384154.
