### ISSUE TITLE
Improve error message when both Lite and Pro version are enabled

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#230]
It would be nice to improve the error message displayed when both Comment Mail Lite and Comment Mail Pro are enabled on a site. Instead of saying `comment-mail` it should say **Comment Mail**.

**Before:**
![screen shot 2016-02-12 at 12 51 24 pm](https://cloud.githubusercontent.com/assets/7514953/13003539/165d5996-d1b1-11e5-8767-52afae96c948.png)

**After:**

![screen shot 2016-02-12 at 6 13 27 pm](https://cloud.githubusercontent.com/assets/7514953/13004108/5d447a3a-d1b4-11e5-8de6-36b60ebc275a.png)

**Comment by raamdev** [comment]
:+1: Slight improvement:

> Please disable **Comment Mail Lite** before activating **Comment Mail Pro**.

**Comment by jaswsinc** [comment]
I'm noting [this line](https://github.com/websharks/comment-mail/blob/151224/comment-mail/plugin.php#L28) that should be changed to just `'Comment Mail'` as the function argument.

- Adding this to my list [here](https://github.com/websharks/comment-mail/issues/150#issue-113717736).

**Comment by jaswsinc** [comment]
This has been resolved by https://github.com/websharks/comment-mail/issues/150

**Comment by raamdev** [comment]
@jaswsinc Thank you!

**Comment by kristineds** [comment]
@jaswsinc Great! :+1:

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Improved the Dashboard notice that appears when you try to enable the Pro version of Comment Mail when the Lite version is currently enabled. Props @kristineds @jaswsinc. See [Issue #230](https://github.com/websharks/comment-mail/issues/230).

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#230).
