### ISSUE TITLE
Build Lite From Pro Codebase

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#237]
A fork of https://github.com/websharks/comment-mail/issues/150#issue-113717736

@jaswsinc writes...

- ### One Codebase (Automatic Lite Generation; Partial Completion)

  - Comment Mail is now a single codebase capable of building the Lite version automatically.

  - [x] However, we need to fork another issue, so we can spend time adding more `/*[pro strip-from="lite"]*/ /*[/pro]*/` markers to the codebase. I added some of the most important ones to start with; e.g., no pro updater, no pings back to our stats server, no pro options allowed, and the menu page adjusts automatically with a pro preview in the lite version. However, the rest of the lite version is still filled with a lot of pro-only features. So there is still some work to be done on this. We just need to add a few more of the `/*[pro strip-from="lite"]*/ /*[/pro]*/` markers in various places.

**Comment by raamdev** [comment]
Completed via https://github.com/websharks/comment-mail-pro/issues/67.
