### ISSUE TITLE
Important Changes to Mandrill (used by Comment Mail RVE feature)

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#240]
Announced today; see http://blog.mailchimp.com/important-changes-to-mandrill/

Most importantly:

> Mandrill is becoming a paid add-on for monthly MailChimp accounts. It will only be available for MailChimp customers who have monthly plans.

@jaswsinc It sounds like this change should speed up our timeline for adding support for other integrations (such as SendGrid; see https://github.com/websharks/comment-mail/issues/200) to Comment Mail, as it sounds like Mandrill is not going to be a reasonable solution for the Comment Mail RVE handler going forward.

**Comment by jaswsinc** [comment]
Bummer. Well, SendGrid comes with a fee also. Looks like the end of free inbound email routing on the web. This is another one that I can add to my SaaS list as a future WS product offering.

Until then, I wish we could find another free (100% free) alternative. If not, then giving users the option between MailChimp and SendGrid would be the next best thing. I agree.

**Comment by jaswsinc** [comment]
I sent Mandrill an email to ask for more information about the future of Inbound Routes.

**Comment by yepher** [comment]
FYI, SparkPost support inbound routes too. 

See [here](https://developers.sparkpost.com/api/#/reference/inbound-domains)

**Comment by raamdev** [comment]
Also, SparkPost announced recently (on the heels of the Mandrill announcement) that it's offering 100,000 free emails per month: https://www.sparkpost.com/pricing

**Comment by oncecoupled** [comment]
I emailed Mandrill as well, and heard:

> Thanks for getting in touch. After your accounts are merged, Mandrill's inbound processing will remain a free feature, though you'll still be required to purchase one block of 25,000 outbound messages each month to have unlimited inbound messaging. However, Mandrill will still function as it does now and as long as they've set up proper MX records, you can add up to 5,000 inbound routes regardless of your MailChimp account status.

They then pointed me to their F.A.Q. at https://mandrill.zendesk.com/hc/en-us/articles/217467117-Mandrill-MailChimp-Transition-FAQs

The new pricing structure will mean a $20/mo minimum for Mandrill on top of a $10/mo minimum for MailChimp. Not something I can recommend to my average client.

**Comment by raamdev** [comment]
@oncecoupled Thanks so much for sharing that! We're definitely going to work on integration with another, (hopefully) free solution, as the RVE feature is an important part of Comment Mail. As long as there are free options available, we want to make that available. Have you found any other services that look like an interesting alternative?

**Comment by augustasas** [comment]
I think many people could have access to a simple POP3 email account. 
Would it be possible to implement a simple integration with a POP3 email address, which would be created specifically for the RVE?

**Comment by raamdev** [comment]
@augustasas It definitely wouldn't be "simple", but it would certainly possible, yes. In fact, before the birth of APIs everywhere, that was the only way to do it. You'd simply read a POP3 email account, watch for new email messages, and then ingest those messages. However, that's prone to all kinds of complexity (mostly related to the many subtle variations in the way servers implement POP3).

The API-way of handling things--which services like Mandrill, SendGrid, and SparkPost provide--gives us a clean, clear, reliable way of processing inbound messages, which is important for a plugin like Comment Mail. For sites that get a lot of comments, there could potentially be all sorts of performance issues that need to be considered if we were just reading a POP3 inbox. 

The last thing we want to be doing is spending the bulk of our development time trying to maintain a POP3 integration that works well for everybody.

**Comment by augustasas** [comment]
@raamdev Thank you. I was not aware that POP3 is quite complex.
Sure, I would vote for a simpler RVE implementation via API.

**Comment by oncecoupled** [comment]
@raamdev I also looked at mailgun, but the solutions above would all work for my clients. I work with food bloggers, and even the best of them wouldn't hit 10,000 inbound in a month.

**Comment by jaswsinc** [comment]
SparkPost looks interesting! i.e., like a decent alternative. Thanks! :-)

**Comment by jaswsinc** [comment]
Related post: http://www.dangrossman.info/2016/02/28/mandrills-betrayal/

**Comment by augustasas** [comment]
And here is information about Inbound Mail:
https://support.sparkpost.com/customer/portal/articles/2039614-enabling-inbound-email-relaying-relay-webhooks

**Comment by kristineds** [comment]
Looks like MailChimp is also recommending SparkPost as a Mandrill alternative. http://blog.mailchimp.com/important-changes-to-mandrill/

Mandrill Migration guide available here: https://www.sparkpost.com/mandrill-migration-guide

**Comment by yepher** [comment]
This is a Slack channel for SparkPost: http://slack.sparkpost.com and is a good place to get questions answered quickly.

**Comment by oncecoupled** [comment]
Any update on this? Just got a reminder email that free Mandrill service stops April 27th, yet the plugin still recommends (and requires) it. I have a few clients using this plugin, for the RVE feature, so I'd like to make a plan for them. 👍

**Comment by jaswsinc** [comment]
@raamdev @kristineds I got the same reminder from Mandrill again today.

> This is a reminder that all Mandrill users will be required to have a paid monthly MailChimp account beginning April 27. If you missed the original announcement, [this blog post](http://mandrillapp.com/track/click/9656353/blog.mandrill.com?p=eyJzIjoiRWRxeE8tdkUxLWVsVC1rQWdTaWEwR0ljNmFVIiwidiI6MSwicCI6IntcInVcIjo5NjU2MzUzLFwidlwiOjEsXCJ1cmxcIjpcImh0dHA6XFxcL1xcXC9ibG9nLm1hbmRyaWxsLmNvbVxcXC9pbXBvcnRhbnQtY2hhbmdlcy10by1tYW5kcmlsbC5odG1sXCIsXCJpZFwiOlwiYjA4ZjhlZTk0YTdmNDAxMzg2YTg0NDY0YmE0OWMxZjVcIixcInVybF9pZHNcIjpbXCJmMGUxMjhhZjVmODg2Njg0NWVhOThmM2U0MDUxZTBiMTRkYTQzNTc1XCJdfSJ9) explains in detail what is changing and why. To continue sending through Mandrill after April 27, here's what you need to do:

> Make sure you've added SPF and DKIM records and verified ownership of any domains you actively use for sending before connecting to a MailChimp account. [This article](http://mandrillapp.com/track/click/9656353/mandrill.zendesk.com?p=eyJzIjoiWlRzTjVXUWRnaFV5MmFWYkJhM1UzdVowZEtNIiwidiI6MSwicCI6IntcInVcIjo5NjU2MzUzLFwidlwiOjEsXCJ1cmxcIjpcImh0dHBzOlxcXC9cXFwvbWFuZHJpbGwuemVuZGVzay5jb21cXFwvaGNcXFwvZW4tdXNcXFwvYXJ0aWNsZXNcXFwvMjA1NTgyMzg3LUhvdy10by1TZXQtdXAtU2VuZGluZy1Eb21haW5zXCIsXCJpZFwiOlwiYjA4ZjhlZTk0YTdmNDAxMzg2YTg0NDY0YmE0OWMxZjVcIixcInVybF9pZHNcIjpbXCI3NGEwYzIyMzdmYWJjZjk0YTdjMDQ5MjdhMDRjYzQ0YTM5NjJhMTczXCJdfSJ9) explains how to do that. You can confirm this has been done in your Mandrill account on the [Sending Domains](http://mandrillapp.com/track/click/9656353/mandrillapp.com?p=eyJzIjoiYXJnQkZiUHI3eURPZzhmV0hRa0g4WEtpZWRjIiwidiI6MSwicCI6IntcInVcIjo5NjU2MzUzLFwidlwiOjEsXCJ1cmxcIjpcImh0dHBzOlxcXC9cXFwvbWFuZHJpbGxhcHAuY29tXFxcL3NldHRpbmdzXFxcL3NlbmRpbmctZG9tYWluc1wiLFwiaWRcIjpcImIwOGY4ZWU5NGE3ZjQwMTM4NmE4NDQ2NGJhNDljMWY1XCIsXCJ1cmxfaWRzXCI6W1wiMDZhOGQ0OWE0MGI2M2Y0M2M2ODg4YTQ3Mzc0ZmRlOWVkZWEzODI1ZlwiXX0ifQ) page. IMPORTANT: We will only send mail from verified domains, so please complete this step before connecting your accounts.

> Connect your Mandrill account to a paid monthly MailChimp account.
> Find detailed instructions for connecting your accounts in our knowledge base.

> **Any Mandrill accounts that have not been merged with a MailChimp account will be closed by April 27 will be disabled.**

**Comment by raamdev** [comment]
I just got the reminder email too, for my personal Mandrill account. I'm a MailChimp paying customer on a Monthly plan and I was hoping that would mean I'd be able to get Mandrill added to my account for free, but apparently the minimum amount required to connect Mandrill to your MailChimp account is $20/month—not practical at all for occasional use. Ugh.

It looks like SparkPost is going to be our next best option. They're honoring Mandrill's pricing and their free plan looks good. I've opened a GitHub issue to discuss SparkPost: https://github.com/websharks/comment-mail/issues/265

**Comment by raamdev** [comment]
The Comment Mail Replies via Email (RVE) feature now supports SparkPost integration (this was added a few months ago, as of v161118). See http://comment-mail.com/kb-article/replies-via-email-sparkpost-or-mandrill/

Thank you everyone for the feedback here!
