### ISSUE TITLE
Shortcodes for Email Footer Tag

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#246]
It would be nice to have some shortcodes available in the Header also in the Footer. Essentially:

- `[home_url] ` Site home page URL; i.e., back to main site.
- `[blog_name_clip]`  A clip of the blog's name; as configured in WordPress.

**Comment by raamdev** [comment]
@IvanRF Could you elaborate on what `[blog_name_clip]` would be and provide an example? Is there anywhere else that it makes sense to make these additional shortcodes available if they were to be added?

**Comment by IvanRF** [comment]
I copy and pasted those descriptions from the Email Header Tag shortcodes. Thus, the same functionality should be included for the Email Footer Tag.

**Comment by raamdev** [comment]
Oh, I see what you're referring to now (a screenshot is always helpful). 

![2016-03-08_12-51-10](https://cloud.githubusercontent.com/assets/53005/13610601/7d3cb56a-e52c-11e5-8b28-b109c3aa2a29.png)
![2016-03-08_12-51-24](https://cloud.githubusercontent.com/assets/53005/13610605/7e4bdc9c-e52c-11e5-83fc-e0766a2f8567.png)

**Comment by raamdev** [comment]
Next Release Changelog:

- **Enhancement**: It's now possible to use the following shortcodes in the Email Footer Tag for Email Footer Templates: `[home_url]`, `[blog_name_clip]`, and `[current_host_path]`. Props @kristineds and @IvanRF. See [Issue #246](https://github.com/websharks/comment-mail/issues/246).

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#246).
