### ISSUE TITLE
Template field for the end of the email

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#249]
Adding a new template field for the end of the email (to be included after CAN-SPAM content) will be useful. For example, Gmail and other email clients does not accept `<style>`, so everything has to be inline CSS. For that, I start every mail with a `<div>` with CSS like `background-color` and `font-family`. I'm able to do that in the Header template. However, there is no place to close that. I'm currently doing it at the end of the CAN-SPAM Mailing Address, but that's just a workaround.

References:
- http://templates.mailchimp.com/resources/inline-css/
- http://kb.mailchimp.com/campaigns/ways-to-build/css-in-html-email

**Comment by raamdev** [comment]
Can't you do that with **Comment Mail → Email Templates → Email Header Tag** and **Comment Mail → Email Templates → Email Footer Tag**?

![2016-03-08_12-41-06](https://cloud.githubusercontent.com/assets/53005/13610329/28575ad8-e52b-11e5-8db4-b6c207a7371e.png)

**Comment by IvanRF** [comment]
@raamdev no, that's why I said "**to be included after CAN-SPAM content**".
As I said, there are email clients that don't accept `<styles>`, only inline styles. To be able to set a background color or other styles to all the email content, I add `<div style="background-color: #f6f6f6;font-family:..">` in the Header, but closing it in the Footer will leave all the other information outside (contact info, manage subsc., CAN-SPAM).
I also had to do some tweaks to the plugin files in order to modify how that last information is shown. I would love if that could be edited from templates too.
Here is an example of how my mails look:
![8-3-2016 3-54-01 p- m-](https://cloud.githubusercontent.com/assets/6751650/13612587/ffde38a8-e546-11e5-8332-0075c3a83182.png)

**Comment by raamdev** [comment]
> I would love if that could be edited from templates too.

It can, in the Pro version. In fact, the part of the footer you're referring to can be edited with advanced templates in the Pro version:

![2016-03-08_14-25-06](https://cloud.githubusercontent.com/assets/53005/13613333/aaacd6d0-e539-11e5-9b32-c96b7dbeec2f.png)

**Comment by IvanRF** [comment]
@raamdev so, the Pro version allows to edit contact info, manage subsc., CAN-SPAM from the Footer? (oh, I see the section is not referred as Footer Tag)

**Comment by raamdev** [comment]
Correct. The Pro version includes Advanced templates which allow for very fine tweaking, like what you're trying to do. :-)

I had to trim the screenshot above so that I could point out what I was explaining, but here's a full list of all the Email Templates available in the Pro version:

![2016-03-08_14-47-30](https://cloud.githubusercontent.com/assets/53005/13614095/d46889c6-e53c-11e5-8fe8-a4d40e334d94.png)

**Comment by raamdev** [comment]
There are also a lot more Site Templates available with Advanced templates (19 vs 8).

**Comment by IvanRF** [comment]
ok, so this was already present on Pro version. I'm closing this then :smiley:

**Comment by raamdev** [comment]
Thank you. :smile:
