### ISSUE TITLE
Akismet: Spam comments are added to Subscriptions

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#250]
I just received one Spam comment detected by Akismet and the plugin added an entry in the Subscriptions with Delivery = `weekly` (default is `daily`) and Status = `unconfirmed`.

Mail Queue and Event Log is empty, maybe because in my WP settings all comments must to be approved.

So, luckily the confirmation mail was not sent to the Spam account (is what I guess from the log). However, I don't like the idea of having to remove an entry from Subscriptions every time I get one Spam.

**Comment by IvanRF** [comment]
I just sent a confirmation to myself and it was not present in the Queue Log, so I have no way to tell if the plugin sent or not a mail to the Spam account.

**Comment by raamdev** [comment]
> I just sent a confirmation to myself and it was not present in the Queue Log, so I have no way to tell if the plugin sent or not a mail to the Spam account.

Yes, there's an issue for that open here: https://github.com/websharks/comment-mail/issues/196

> I just received one Spam comment detected by Akismet and the plugin added an entry in the Subscriptions with Delivery = weekly (default is daily) and Status = unconfirmed.

Hmm, that shouldn't happen. If Akismet flags something as spam, Comment Mail should be ignoring it. Marking this as a bug that needs testing.

**Comment by IvanRF** [comment]
> Hmm, that shouldn't happen. If Akismet flags something as spam, Comment Mail should be ignoring it. Marking this as a bug that needs testing.

I currently have 6 spams, and they were not added in Subscriptions. The strange thing is that Delivery was set to `weekly`, so maybe this was a real comment (not bot) marked as Spam by Akismet. When I had this issue I didn't realized I had 2 pages of spam and I emptied all, so if it was a real comment I loose it.

**Comment by raamdev** [comment]
@IvanRF Great! Thank you. I was just reviewing the code and I see that Comment Mail should already be obeying Akismet, so I'm not sure how an Akismet-flagged comment would have a subscription created by Comment Mail. 

I'll leave this GitHub issue open for now, pending any future feedback.

**Comment by IvanRF** [comment]
This happened again. This time I know the confirmation mail was sent from the Email log data.

![14-3-2016 12-11-51 p- m-](https://cloud.githubusercontent.com/assets/6751650/13748993/3e3ec400-e9de-11e5-93d5-16ef3ac6b369.png)

![14-3-2016 12-12-27 p- m-](https://cloud.githubusercontent.com/assets/6751650/13748996/43c0af42-e9de-11e5-924e-5380c60eb7bb.png)


The IP 178.137.93.120 is from Ukraine.

**Comment by IvanRF** [comment]
I use Wordfence but I don't know if they send mails to Spam too. This is from Wordfence log:
```
[Mar 13 08:58:42] Scanning comment with Author: flqlplqo Email: yealiw@bjjxxe.com Source IP: 178.137.93.120
[Mar 13 08:58:42] Checking 7 host keys against Wordfence scanning servers.
[Mar 13 08:58:42] Done host key check.
[Mar 13 08:58:42] Scanned comment with Author: flqlplqo Email: yealiw@bjjxxe.com Source IP: 178.137.93.120
```

**Comment by IvanRF** [comment]
@raamdev some more proofs. I just emptied the Spam comments and there are 3 subscriptions still there:

![31-3-2016 4-00-31 p- m-](https://cloud.githubusercontent.com/assets/6751650/14187635/5d9a0f2e-f75a-11e5-852f-d899d24c92ef.png)

![31-3-2016 3-59-27 p- m-](https://cloud.githubusercontent.com/assets/6751650/14187638/6475b8ca-f75a-11e5-9555-9a0385da85e5.png)

Event Log:
![31-3-2016 4-07-39 p- m-](https://cloud.githubusercontent.com/assets/6751650/14187786/0ed7ff44-f75b-11e5-814f-401f3594caec.png)

**Comment by IvanRF** [comment]
I just checked the Subscriptions table before deleting Spam comments, and **the Subscriptions are added for Spam comments**.

Spam comments
![31-3-2016 10-06-42 p- m-](https://cloud.githubusercontent.com/assets/6751650/14195228/427ce2e2-f78d-11e5-84be-e7132723f8e7.png)

Subscriptions
![31-3-2016 10-07-26 p- m-](https://cloud.githubusercontent.com/assets/6751650/14195235/4ed2917c-f78d-11e5-82bb-fe7301321f28.png)

**Comment by raamdev** [comment]
@IvanRF Thanks for the additional info. It looks like this needs more testing on our end.

**Comment by gretlouise** [comment]
I am receiving "Mail delivery failed: returning message to sender" emails for every "confirm subscription" email that was sent to a spam commenter. This is definitely still an issue.

**Comment by IvanRF** [comment]
Today a bot that has nothing better to do sent 350 spam comments to my site and **294 subscriptions were created** for those spam mails. Any news with this issue?

**Comment by IvanRF** [comment]
@raamdev I also noticed that removing a comment which is not spam triggers a subscription removal, but **using the "Delete permanently" option from the Spam page does not trigger a subscription removal**.

**Comment by IvanRF** [comment]
Tired of doing this work, I did a research on blocking spam before being marked as Spam and I found this plugin: https://wordpress.org/plugins/wp-spamshield/
So far blocked 250 spams with no false positives. Excellent to avoid all the DB processing that my site was having.

**Comment by raamdev** [comment]
@jaswsinc It looks like we just need to add the following [here](https://github.com/websharks/comment-mail/blob/160213/comment-mail/includes/classes/comment-post.php#L79):

```php
if($this->comment_status == 'spam')
     return; // Not applicable.
```

Do you agree?

**Comment by jaswsinc** [comment]
Agree :-)

**Comment by raamdev** [comment]
@IvanRF I've submitted a patch for this to our dev branch, but if you could test this by modifying `includes/classes/comment-post.php#L79` by adding the following, that would be great:

```php
        if($this->comment_status == 'spam') {
            return; // Not applicable.
        }
```

This is the sort of thing that's hard to test unless you already have a site getting spam. I guess this is one case where we _need_ a site to get some spam to really test it. 😆

**Comment by IvanRF** [comment]
@raamdev I thought I had this under control with wp-spamshield but they do have false positives :angry: and were blocking some real comments.

So, back to Akismet, I added those 2 lines on `comment-post.php` and in the last 30 minutes I got 6 spams and nothing went to Subscriptions. Thus, the fix works!

I'll let you know more in the next days, since more spam is coming... :weary:

**Comment by raamdev** [comment]
> the fix works!

Thank you for confirming that! I'll make sure this fix gets pushed out with the next update. Good luck with the spam. 😞

**Comment by raamdev** [comment]
Next Release Changelog:

- **Bug Fix**: Fixed a bug that allowed spam comments to create subscriptions in Comment Mail when using Akismet. Props @IvanRF. See [Issue #250](https://github.com/websharks/comment-mail/issues/250).

**Comment by oncecoupled** [comment]
Is there a known date when the version with this fix be released? I have a client with the same problem. Actually, she has 63,637 entries in the subscriptions event log and they are even subscribed?! They are clearly spam emails.

By the way, and off-topic, @IvanRF did SpamShield allow you to work with email replies? We tried Anti-Spam in the past but it blocks Comment Mail email replies.

**Comment by IvanRF** [comment]
@oncecoupled no idea, as I said wp-spamshield was blocking real comments in my site so I remove it. I manually modified the line which solves this issue in the Comment Mail code for my site.

**Comment by raamdev** [comment]
@oncecoupled A release candidate was published a few days ago that includes the fix described here (see [announcement](http://comment-mail.com/comment-mail-v160611-rc-release-candidate/)). We usually publish a general availability release a week or so after the RC (to give us enough time for testing). Thanks for your patience!

_Note: If you'd like to be notified about release candidates, please sign-up to be a beta tester [here](https://comment-mail.com/beta-testers/)._

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#250).
