### ISSUE TITLE
Daily notification not being holded

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#256]
From my test [here](https://github.com/websharks/comment-mail/issues/173#issuecomment-194374994), I discovered that the first comment was sent to a daily subscriber too fast. The email says "This comment was posted 2 minutes ago", is it ok to send so fast notifications to daily subscribers?

**Comment by IvanRF** [comment]
@raamdev were you able to reproduce this issue? compared to other issues I sent, I think this should have a higher priority for next release. I'm currently writing replies real fast to avoid the digest issue #173 :smile:

**Comment by jaswsinc** [comment]
> "This comment was posted 2 minutes ago", is it ok to send so fast notifications to daily subscribers?

The way it works is that a daily subscriber is sent email notifications no less than 24 hours apart. So it's OK for them to get an email as soon as a comment is posted, so long as they have not already been notified about any for the past 24 hours. If you then post another comment, it _will_ be held and then delivered together with any others approx 24 hours later.

**Comment by raamdev** [comment]
@jaswsinc Thank you. That clarifies things. I'm going to draft a KB Article that explains this behavior.

I'm going to close this as `invalid`, since the behavior @IvanRF reported is expected. We have a separate issue (https://github.com/websharks/comment-mail/issues/173) open to address a separate issue with the digest notifications.

**Comment by IvanRF** [comment]
@raamdev @jaswsinc this might be the implemented behaviour but I don't think it's the best.

If a discussion starts in a post, all users with daily digest will receive only the first comment and all the replies will be sent the next day (currently they will never receive the follow ups). I think it would be better to set a fixed time for daily digest or at least wait a bit longer after the a comment is posted. They choose "daily" so what's the hurry :smile:

**Comment by raamdev** [comment]
@IvanRF After thinking about this a bit more, I agree with you. For Daily Digests, the expectation is that it will be at least a day before receiving any notification, including the _first_ notification. I've forked this into a separate GitHub issue here: https://github.com/websharks/comment-mail/issues/261

**Comment by raamdev** [comment]
Related: https://github.com/websharks/comment-mail/issues/173
