### ISSUE TITLE
Question: editing a comment

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#262]
What happens to notifications in the Mail Queue when I edit a new comment? is the comment content read just before sending the notifications or when they are queue?

It's just a doubt I have, if after I edit a comment the pending notifications will have the updated comment or the old one.

**Comment by raamdev** [comment]
A quick review of the codebase tells me that queued entires contain everything that will be sent for that notification (including the body of the message), so it looks like editing a comment after a notification for it has been queued will _not_ send the updated comment, but rather whatever content that comment contained when the notification was queued.

@jaswsinc Can you confirm this? This sounds like a good info for a KB Article.

**Comment by jaswsinc** [comment]
Comment Mail sends what is in the DB at the time the notification is sent via email. So if you edit a comment before it is sent (even if it was already queued), the user receives the updated comment content and not what was originally written.

**Comment by IvanRF** [comment]
@jaswsinc that's what I wanted, thanks!
