### ISSUE TITLE
Feature Request: SparkPost for RVE

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#265]
Mandrill has announced that it's no longer going to be free which means Comment Mail's RVE feature will soon depend on a paid-only service (see https://github.com/websharks/comment-mail/issues/240). 

SparkPost, a similar service, has announced that it will "honor Mandrill’s pricing for any customer that switches to SparkPost from Mandrill". See the [Mandrill Migration Guide](https://www.sparkpost.com/mandrill-migration-guide). 

I suggest that we prioritize SparkPost as a replacement for Mandrill. They have a free plan and the free plan (as far as I can tell) supports relay webhooks.

Here are the API Docs for their Relay Webhooks:
https://developers.sparkpost.com/api/#/reference/relay-webhooks

**Comment by yepher** [comment]
If you have any questions during your migration consider reaching out on SparkPost's developer Slack channel. You can join [here](http://slack.sparkpost.com)

There are developer there who can help answer integration questions.

**Comment by raamdev** [comment]
@yepher Awesome. Thanks for the tip! We use Slack at WebSharks too, so that should make things easy. :-)

**Comment by JeffVark** [comment]
I've been using Sparkpost since the Mandrill announcement. They have a great offer. Sparkpost would be an excellent choice for the Comment Mail's RVE feature.

**Comment by kristineds** [comment]
Also requested here: [Private Support Ticket #14930](https://websharks.zendesk.com/agent/tickets/14390).

**Comment by jaswsinc** [comment]
Estimate at three days.

**Comment by tech55541** [comment]
Can't wait to see this.

**Comment by kristineds** [comment]
Also requested here: [Private Support Ticket #14696](https://websharks.zendesk.com/agent/tickets/14696).

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **SparkPost Integration:** It is now possible to use SparkPost for Replies-via-Email (RVE) instead of Mandrill. Note that SparkPost is now the suggested RVE Handler for Comment Mail because Mandrill changed its pricing structure a while back. In short, Mandrill requires a fee, whereas SparkPost (recommended) offers Relay Webhooks as a part of their free plan. See also [issue #265](https://github.com/websharks/comment-mail/issues/265) for additional details.

**Comment by renzms** [comment]
@raamdev @jaswsinc 

Hi Guys, Observed a fatal Error and the links to the documentation were not working while testing this.

_____

@jaswsinc 

**Side Note**, for the test domains you've setup for us, in the documentation its noted that there is no SPF Text Record or DKIM Record available. Is it possible to add the following emails to verify for SparkPost? 

```
VERIFY EMAIL
abuse@name.domain.net 
postmaster@name.domain.net
```

**Comment by renzms** [comment]
@raamdev @jaswsinc 

Hi Guys, Observed a fatal Error and the links to the documentation were not working while testing this.


_____


## Observed Behaviour:  Fatal Error on all white page

```
Fatal error: Uncaught Error: Using $this when not in object context in /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/RveSparkPost.php on line 271 Error: Using $this when not in object context in /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/RveSparkPost.php on line 271 Call Stack: 0.0003 406200 1. {main}() /app/src/wp-admin/admin.php:0 0.0004 406680 2. require_once('/app/src/wp-load.php') /app/src/wp-admin/admin.php:31 0.0008 421040 3. require_once('/app/src/wp-config.php') /app/src/wp-load.php:39 0.0010 424600 4. require_once('/app/src/wp-settings.php') /app/src/wp-config.php:41 0.0731 3531072 5. do_action() /app/src/wp-settings.php:411 0.0731 3531472 6. WebSharks\CommentMail\Pro\Plugin->actions() /app/src/wp-includes/plugin.php:524 0.0737 3543296 7. WebSharks\CommentMail\Pro\Actions->__construct() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/Plugin.php:1034 0.0738 3543416 8. WebSharks\CommentMail\Pro\Actions->maybeDoMenuPageActions() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/Actions.php:41 0.0754 3712312 9. WebSharks\CommentMail\Pro\MenuPageActions->__construct() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/Actions.php:107 0.0755 3713128 10. WebSharks\CommentMail\Pro\MenuPageActions->maybeHandle() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/MenuPageActions.php:55 0.0853 4263568 11. WebSharks\CommentMail\Pro\MenuPageActions->saveOptions() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/MenuPageActions.php:79 0.0855 4263568 12. WebSharks\CommentMail\Pro\Plugin->optionsSave() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/MenuPageActions.php:99 0.1353 4504672 13. WebSharks\CommentMail\Pro\RveSparkPost::setupWebhook() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/Plugin.php:1152
```

## Steps to Reproduce Fatal Error

- Enable **Comment Mail Pro**, and setup SparkPost account to get API
- Choose SparkPost in the dropdown for RVE Handler, and input API and email into corresponding fields under **RVE Handler** panel
- Click `Save all changes`
- Fatal Error after submission redirect


## SparkPost KBA links
![screen shot 2016-11-10 at 4 24 54 pm](https://cloud.githubusercontent.com/assets/13220018/20169957/326d9df0-a765-11e6-850b-0ea7ef40424a.png)

Both links go to http://comment-mail.com/kb-article/sparkpost-rve-handler/ 

![screen shot 2016-11-10 at 4 46 36 pm](https://cloud.githubusercontent.com/assets/13220018/20169968/46f338e8-a765-11e6-9943-bcb03fe4c8f4.png)




_____

@jaswsinc 

**Side Note**, for the test domains you've setup for us, in the documentation its noted that there is no SPF Text Record or DKIM Record available. Is it possible to add the following emails to verify for SparkPost? 

```
VERIFY EMAIL
abuse@name.domain.net 
postmaster@name.domain.net
```

**Comment by jaswsinc** [comment]
> Using $this when not in object context

Fixed in dev branch. Thank you.

**Comment by jaswsinc** [comment]
@renzms Great catch BTW. Thanks! :-)

**Comment by jaswsinc** [comment]
@renzms The KBA is still in draft format here, for now:
https://github.com/websharks/comment-mail-kb/issues/27

**Comment by jaswsinc** [comment]
@renzms writes...

> that there is no SPF Text Record or DKIM Record available

This would be for your Outbound Sending Domain, which is not necessary to configure for the purpose of testing Comment Mail. So you can just ignore that message. Having said that, I did try to set up the @wpsharks.net domain for this purpose, but that appears to be probelmatic when it comes to SparkPost Sending Domains, due to the fact that they do not allow the same top-level domain to be used across multiple test accounts.

What I was able to do is setup the MX record for an Inbound Domain, which is what's needed to test Comment Mail. For the Reply-To address in Comment Mail you can use: `rve@spark-renz.wpsharks.net`

**Comment by renzms** [comment]
> What I was able to do is setup the MX record for an Inbound Domain, which is what's needed to test Comment Mail. For the SparkPost RVE Reply-To address in Comment Mail you can use:

Thanks! I will build again using the changes you made on the dev branch and test.

**Comment by renzms** [comment]
@jaswsinc 

Testing the latest dev build and following the instructions found in: websharks/comment-mail-kb#27

Good news is I no longer receive the fatal error message.

However,...

I received the following error prompt:

```
RVE Error: The Comment Mail™ plugin was unable to complete the integration with SparkPost. When attempting to create a Relay Webhook the SparkPost API said:
resource conflict
```

**Comment by jaswsinc** [comment]
@renzms Can you post a screenshot of the RVE config fields that returned this error please?

**Comment by renzms** [comment]
@jaswsinc 

Sure

## RVE Panel
![screen shot 2016-11-10 at 10 57 51 pm](https://cloud.githubusercontent.com/assets/13220018/20181443/2827b4c8-a799-11e6-8360-78a53f942945.png)

## SparkPost Dashboard
![screen shot 2016-11-10 at 10 53 42 pm](https://cloud.githubusercontent.com/assets/13220018/20181447/295d7b8e-a799-11e6-9599-b2cdcf365d57.png)

**Comment by renzms** [comment]
@raamdev @jaswsinc 

**Replies via RVE are now working.**

I can confirm this is working now with the latest dev build. Thanks @jaswsinc for clearing the Webhook from SparkPost so I could get this working!

**Comment by raamdev** [comment]
**Comment Mail v161118** has been released and includes changes from this GitHub Issue. See the [v161118 announcement](http://comment-mail.com/comment-mail-v161118-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#265).
