### ISSUE TITLE
stcr-import-start.html was not found on this server

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#266]
The current version of the Phing build system (Phings v160411) that we have on the `000000-dev` branch as of 2016-04-15 excludes the `src/client-s/iframes/stcr-import-start.html` file from the distributable zip file that gets generated, which produces the following error when you you try to use the StCR Importer:

> **Not Found**
> 
> The requested URL /wordpress/wp-content/plugins/comment-mail-pro/src/client-s/iframes/stcr-import-start.html was not found on this server.

I have confirmed that this issue is fixed with [the pending rewrite](https://github.com/websharks/phings/pull/83) of the Phings project, so this GitHub issue serves as a reminder that we need to update to the next release of Phings (pending merge of the Phings `feature/rewrite` branch) before the next Comment Mail release.

**Comment by raamdev** [comment]
@renzms This is one you could test. I think this has been resolved by the latest version of Phings that we're using in Comment Mail, but we just need to confirm by attempting to reproduce this bug.

**Comment by renzms** [comment]
> This is one you could test.

Noted, will test out.

**Comment by renzms** [comment]
@raamdev 

Ran `phing` on the `000000-dev` branch, and used the distributable to install. Ran the StCR importer and it successfully imported.

![screen shot 2016-05-21 at 1 10 38 pm](https://cloud.githubusercontent.com/assets/13220018/15446512/e0fd0c36-1f55-11e6-9398-ce6ace7db796.png)

**Comment by raamdev** [comment]
@renzms Great! Thank you for testing.
