### ISSUE TITLE
Bug: `esc_html()` should be `esc_sql()`

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#268]
@kristineds See [this line](https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/UtilsDb.php#L370) of code. That should be `esc_sql()` instead of `esc_html()`. I suggest a full review of the codebase (i.e., search for `esc_html()` in that context and see if I duplicated that same bug across multiple class methods at some point. My bad!

Referencing: https://developer.wordpress.org/reference/functions/esc_sql/

**Comment by raamdev** [comment]
Next Release Changelog: 

- **Bug Fix**: Fixed a bug where `esc_html()` was being used where `esc_sql()` should've been used. Props @jaswsinc @kristineds. See [Issue #268](https://github.com/websharks/comment-mail/issues/268).
