### ISSUE TITLE
Plugin Compatibility: Postman SMTP

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#271]
We have [a report](https://wordpress.org/support/topic/comment-mail-pro-edition-fine-but-can-do-better-for-the-best?replies=1#post-) of an issue using Comment Mail Pro + [Postman-SMTP](https://wordpress.org/plugins/postman-smtp/) (70k active installs): 
> When WordPress option "Comment must be manually approved" is on and if plugin Postman-SMTP (v. 1.7.2) is active, no new comment notification mails were sent and received (or few hours later, in some rare cases), whatever parameters set on both parties. Removing Postman-SMTP and using option "SMTP Server Integration" on Comment Mail (Pro version only) solved the problem.

Related: #258

**Comment by Reedyseth** [comment]
@raamdev I have notice that this Postman SMTP has some bug in its side, that same behavior happens with StCR and after removing Postman SMTP the notifications started to work, I searched a lot and StCR was not the issue. Issue reported here:

https://wordpress.org/support/topic/emails-send-from-stcr-through-postman-smtp-detected-as-spam

**Comment by renzms** [comment]
@raamdev 

Tested this under the following conditions:

- **WordPress 4.6.1** running **Twenty Sixteen theme** with **Comment Mail Pro Version 160818 / Comment Mail Version 160824** installed
- Postman SMTP Version 1.7.2 with Google as the configured API
- **Dashboard → Settings → Discussion → `Check Comment must be manually approved`**

I was able to receive comment notifications properly in the main Inbox and it was not marked **Spam**.

**Comment by raamdev** [comment]
@renzms So you were **unable to reproduce** any problem between Comment Mail and Postman SMTP, is that correct?

**Comment by renzms** [comment]
@raamdev 

Correct, I was unable to reproduce any issues between Comment Mail and Postman SMTP.

Editing the original comment to reflect this.
