### ISSUE TITLE
Disable Browser Username/Password Autofill on Pro Updater page

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#274]
This issue was recently solved for Comet Cache. We need to apply the same fix to the Comment Mail Pro plugin updater. See https://github.com/websharks/comet-cache/issues/741#issuecomment-223008092. 

> It looks like we can use `autocomplete="off"` in the `<form>` tag and Firefox will obey that. Then we can use `autocomplete="new-password"` in the individual fields, and Chrome will obey that. Woohoo! 

![2016-06-03_18-58-24](https://cloud.githubusercontent.com/assets/53005/15795184/3a247328-29bd-11e6-9a68-65b8c0a0a528.png)

**Comment by renzms** [comment]
@raamdev 

While I was testing this before I made changes, I noticed the header going into the panel and overlapping
![screen shot 2016-06-07 at 9 57 08 pm](https://cloud.githubusercontent.com/assets/13220018/15860657/8907325e-2cfc-11e6-808e-cf9c7b69edfc.png)

Is this happening in your install too?

**Comment by raamdev** [comment]
> Is this happening in your install too?

Nope, I'm not seeing that. Did you double check that you have the latest from the dev branch? Also, try clearing your browser cache.

**Comment by raamdev** [comment]
Next Release Changelog:

- **Bug Fix** (Pro): When Chrome or Firefox Autofill Username/Password was enabled, the Comment Mail Pro Updater fields would incorrectly be autofilled by the browser with invalid credentials. This has been fixed. Props @renzms. [Issue #274](https://github.com/websharks/comment-mail/issues/274).

**Comment by raamdev** [comment]
**Comment Mail v160618** has been released and includes changes from this GitHub Issue. See the [v160618 announcement](https://comment-mail.com/comment-mail-v160618-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#274).
