### ISSUE TITLE
Remove IP address in notification emails

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#288]
_This was originally reported [on the community forum](https://wordpress.org/support/topic/how-to-remove-ip-in-mail-notification?replies=1#post-8598282)._

We need <del>an option to hide</del> to remove the IP address that shows up in the notification emails to comply with data protection laws in certain countries, like Germany.

The subscriber IP address currently shows up in these templates: 

- [`/src/includes/templates/type-a/email/sub-confirmation/message.php`](https://github.com/websharks/comment-mail-pro/blob/160618/src/includes/templates/type-a/email/sub-confirmation/message.php#L120)
- [`/src/includes/templates/type-s/email/sub-confirmation/message.php`](https://github.com/websharks/comment-mail-pro/blob/160618/src/includes/templates/type-s/email/sub-confirmation/message.php#L83)

**Comment by kristineds** [comment]
@raamdev Where exactly do you want this option to be added? Here's a sample mock that I came up with. 

![screen shot 2016-07-26 at 12 57 09 am](https://cloud.githubusercontent.com/assets/7514953/17109768/fe09d314-52cb-11e6-9f5f-bacda6d6c340.png)

**Comment by raamdev** [comment]
I was just reviewing the Comment Mail options panels and I realized that it would make more sense to just remove the IP address from the default templates altogether. That seems like a better idea than adding a new option for this.

**Comment by raamdev** [comment]
Next release changelog:

- **UX Enhancement:** Removed IP address information from email notification templates to better comply with data protection laws in certain countries. Props @kristineds. See [Issue #288](https://github.com/websharks/comment-mail/issues/288).

**Comment by raamdev** [comment]
**Comment Mail v160818** has been released and includes changes from this GitHub Issue. See the [v160818 announcement](http://comment-mail.com/comment-mail-v160818-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#288).
