### ISSUE TITLE
Avoid StCR settings migration when StCR is not installed

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#294]
Quoted from [this conversation](https://websharks.slack.com/archives/comment-mail/p1470962999000234) with @raamdev: 

---

In the event that Comment Mail detects that you're migrating from StCR, it tries to figure out which settings it should apply in Comment Mail by default (i.e., migrates your StCR settings to Comment Mail; see [Subscribe to Comments Reloaded (StCR); Settings Imported by Comment Mail Upon Plugin Activation](http://comment-mail.com/kb-article/stcr-options-transitioned-by-comment-mail/)).

That said, it just occurred to me that we should probably _avoid_ importing settings when the StCR plugin is not installed, even if we detect StCR settings in the database. That scenario would indicate the site owner is most likely _not_ upgrading from StCR and won't expect settings to be migrated.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** Do not attempt to import StCR settings if StCR is no longer installed, even if old StCR options exist in the database. See [Issue #294](https://github.com/websharks/comment-mail/issues/294).

**Comment by renzms** [comment]
@jaswsinc @raamdev

### Confirmed Working

Tested using Comment Mail Pro/Lite v161210-RC and StCR Version 160915 in WP v4.7

### Steps taken

- Installed StCR
- Changed and saved some settings in StCR
- Deactivated StCR, then uninstalled and Activated Comment Mail
- There is no prompt for importing settings from StCR even if StCR settings are present in the database. 💯

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#294).
