### ISSUE TITLE
Pro Update Dashboard notification contains unecessary padding

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#296]
The Comment Mail Pro Update Dashboard notification contains unnecessary padding on the bottom that needs to be removed:

![2016-08-19_15-02-24](https://cloud.githubusercontent.com/assets/53005/17821174/40ade434-661e-11e6-96ec-611db258d2ba.png)
![2016-08-19_15-03-34](https://cloud.githubusercontent.com/assets/53005/17821178/41e8eb1e-661e-11e6-838d-d75a645e7711.png)

**Comment by raamdev** [comment]
Next Release Changelog:

- **UI Bug Fix** (Pro): Removed unnecessary padding from the bottom of the Pro Update Dashboard notification. Props @kristineds. See [Issue #296](https://github.com/websharks/comment-mail/issues/296).

**Comment by renzms** [comment]
@raamdev 

Looks good to me!

![screen shot 2016-11-10 at 10 45 40 pm](https://cloud.githubusercontent.com/assets/13220018/20181016/9f2b0c0c-a797-11e6-8324-df4b73e7eab4.png)

**Comment by raamdev** [comment]
**Comment Mail v161118** has been released and includes changes from this GitHub Issue. See the [v161118 announcement](http://comment-mail.com/comment-mail-v161118-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#296).
