### ISSUE TITLE
Option to reschedule events if necessary

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#301]
As part of one of the solutions to #192, it will be useful to add an option to force `wp_clear_scheduled_hook()` + `wp_schedule_event()`, like you do on the function `checkCronSetup()` of `Plugin.php`.

**Comment by raamdev** [comment]
@IvanRF I'm not sure I understand how this is useful?

**Comment by IvanRF** [comment]
It would have been useful for me in order to re create the cron job. Although it would be hard for a common user to realize that a cron job is missing...

**Comment by raamdev** [comment]
Right. There should never be a scenario where the cron job is missing. If it's missing, then there's either a bug that needs to be fixed, or more likely there's another plugin or something wonky about the WordPress installation that is removing the cron job... 

There was a bug related to that cron disappearing in some scenarios that was fixed back in v160618; see https://github.com/websharks/comment-mail/issues/194. If that bug hasn't been completely fixed, or if there's some other scenario we're not taking into account, then we need to open a new bug report to investigate. 

I'm going to close this GitHub issue though, as I don't feel that creating a way to manually reschedule the events in Comment Mail is necessary.
