### ISSUE TITLE
Comment Mail Pro Updater: Unknown error. Please wait 15 minutes and try again.

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#303]
Users are reporting the following error when trying to update Comment Mail Pro via the Pro Updater: "Unknown error. Please wait 15 minutes and try again."

![2016-10-07_12-30-36](https://cloud.githubusercontent.com/assets/53005/19197802/dc55543a-8c89-11e6-9012-88cb9bb2a390.png)

I've reproduced the issue from one of my test sites.

----

_Referencing [internal ticket](https://websharks.zendesk.com/agent/tickets/14509)._

**Comment by jaswsinc** [comment]
Resolved. SSL certificate renewal.

**Comment by raamdev** [comment]
Confirmed fixed. Thank you.

![2016-10-07_13-42-03](https://cloud.githubusercontent.com/assets/53005/19199803/db8c54ea-8c93-11e6-9766-b85b82cd7dc2.png)
