### ISSUE TITLE
Improve Accessibility for Screen Readers

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail#304]
On the Manage Subscriptions or Subscribe page, there are drop downs. When selecting a post, and selecting a comment to subscribe to, a [screen reader](https://en.wikipedia.org/wiki/Screen_reader) will read this as _read only_ and goes into **edit mode** when it should remain in **browse mode**. 

It would be nice if instead, we replace these drop downs with Combo Boxes or drop downs with **aria-labels** to let the user know when it is expanded or collapsed. 

---

Referencing Internal Ticket:

https://websharks.zendesk.com/agent/tickets/14702

**Comment by tech55541** [comment]
+1. Really looking for a solution, I am willing to test and work with everyone to get this fixed.

Thanks.

**Comment by tech55541** [comment]
@raamdev, This is more general, but the plugin has lots of FontAwesome icons scattered about through various parts of the plugin. Think in the future
`aria-hidden="true"`
could be added so screen readers know to ignore them? Haven't tried, but maybe that would help us on the drop downs by telling the screen reader to ignore the "read only" part, maybe that is a temporary solution.

**Comment by jaswsinc** [comment]
New option coming soon...

See: **Dashboard → Comment Mail → Config Options → Misc. UI Options**

![2016-12-01_23-47-12](https://cloud.githubusercontent.com/assets/1563559/20827786/977c2132-b820-11e6-80a8-0dbd881948c6.png)

**Comment by jaswsinc** [comment]
Referencing Chrome Extension for testing purposes:
https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Accessibility:** This release improves screen reader accessibility by adding `aria-hidden="true"` to all FontAwesome icons. See [Issue #304](https://github.com/websharks/comment-mail/issues/304).

- **Accessibility:** This release improves screen reader accessibility by offering a new setting that allows a site owner to enable or disable select menu option enhancement via jQuery. Disabling select menu option enhancement has the benefit of improving accessibility for screen readers whenever accessibility is of more concern than presentation. See: **Dashboard → Comment Mail → Config Options → Misc. UI-Related Settings**. See also [Issue #304](https://github.com/websharks/comment-mail/issues/304).

**Comment by jaswsinc** [comment]
Referencing accessibility issues with the jQuery Chosen extension that powers our enhanced select option menus in Comment Mail. Disabling jQuery Chosen (i.e., select menu option enhancements in Comment Mail) will restore accessibility until such time as this jQuery extension is enhanced. See: https://github.com/harvesthq/chosen/issues/264

**Comment by tech55541** [comment]
@jaswsinc, is this option available yet? To disable the special jQuery drop downs? Would really like to see some push to get this out fast since there are laws that say sites should be accessible.

If it's not an option, are there any quick patch work around?

Thanks.

**Comment by jaswsinc** [comment]
@tech55541 This is going to get pushed out really soon, yes.

In the meantime, if you'd like to test it even earlier you can signup for our beta mailing list here: http://comment-mail.com/beta-testers/ and you'll get an early copy of the release candidate via email.

**Comment by jaswsinc** [comment]
@tech55541 Here is an even earlier copy that is available for testing. This is an unstable bleeding edge copy of the latest revisions that make this possible. Please report any problems. Thanks!

Download link: https://cdn.wpsharks.com/software/bleeding-edge/comment-mail-pro/10bafd51ac92c9e.zip

**Comment by tech55541** [comment]
Will test on my staging site and let you know @jaswsinc.

**Comment by tech55541** [comment]
Hello again @jaswsinc,

I really haven't tested functionality overall yet, but the accessibility fix works. Please do include this in the documentation or make the accessibility option default. This jQuery drop downs in my opinion should not be enabled by default, it would not do the blind community any favors if the person setting this plugin up overlooks this setting.

I understand we're in the early stages, thanks for taking such swift action here. :)

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Confirmed as working in latest bleeding edge version of Comment Mail Pro

**Dashboard → Comment Mail → Config Options → Misc. UI-Related Settings → Select Menu Options: Enhance? → No** 

![screen shot 2016-12-09 at 7 20 13 pm](https://cloud.githubusercontent.com/assets/13220018/21047381/8eb31e96-be44-11e6-9f68-533c5e0cb2a8.png)


![screen shot 2016-12-09 at 7 08 12 pm](https://cloud.githubusercontent.com/assets/13220018/21047284/04f877a0-be44-11e6-8168-8dbe70891113.png)
![screen shot 2016-12-09 at 7 07 33 pm](https://cloud.githubusercontent.com/assets/13220018/21047286/04fd0a04-be44-11e6-9179-ed12423c6af0.png)


The dropdown selectors are not enhanced by jQuery and allow for better accessibility for readers.

_____


### Default View with jQuery enhancements

**Dashboard → Comment Mail → Config Options → Misc. UI-Related Settings → Select Menu Options: Enhance? → Yes** 
![screen shot 2016-12-09 at 7 19 09 pm](https://cloud.githubusercontent.com/assets/13220018/21047354/6b89a7a0-be44-11e6-952e-8dd442d78a76.png)
![screen shot 2016-12-09 at 7 18 48 pm](https://cloud.githubusercontent.com/assets/13220018/21047355/6b8af11e-be44-11e6-9c48-ea976e40ac9b.png)

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#304).
