### ISSUE TITLE
Feature Request: Dismissable Config Param for Notices

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#308]
A fork of https://github.com/websharks/comment-mail/issues/272#issuecomment-258196905. We need the notice system in the Comment Mail plugin to support a new `(bool) dismissable` configuration parameter so that persistent notices can also be non-dismissable.

**Comment by raamdev** [comment]
Excellent! Thank you.

**Comment by raamdev** [comment]
**Comment Mail v161118** has been released and includes changes from this GitHub Issue. See the [v161118 announcement](http://comment-mail.com/comment-mail-v161118-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#308).
