### ISSUE TITLE
Auto-disabling the Comment Form template system upon StCR config import is confusing

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#314]
When Comment Mail detects and imports certain configuration from the Subscribe to Comments Reloaded plugin, **Comment Mail → Config. Options → Comment Form** may get set to "No, disable built-in template system" because it's assumed that the site owner has a deep theme integration and probably doesn't want the subscription options to be automatically inserted into the comment form. 

However, I have seen this cause some confusion: Site owners write in asking where the subscription options are and how come they're not showing up on the comment form on their site.

When Comment Mail disables the built-in template system due to StCR options that were imported, a dismissable Dashboard notice should appear informing the site owner that "The Comment Mail built-in template system has been disabled due to your imported StCR configuration. To enable the built-in comment form template system, please see **Comment Mail → Config. Options → Comment Form**."

**Comment by jaswsinc** [comment]
![2016-12-02_01-41-22](https://cloud.githubusercontent.com/assets/1563559/20831228/7f258d84-b830-11e6-980e-0cdad8a53df2.png)

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** Notify StCR users about the comment form template being disabled under certain scenarios. See [Issue #314](https://github.com/websharks/comment-mail/issues/314).

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Confirmed Working

![screen shot 2016-12-13 at 4 14 53 pm](https://cloud.githubusercontent.com/assets/13220018/21132512/64648702-c14f-11e6-805c-8f3901379d60.png)

Tested using Comment Mail Pro/Lite v161210-RC and StCR Version 160915 in WP v4.7

### Steps taken
- Installed StCR
- Disable the checkbox for the Comment Form panel in StCR
- Deactivate StCR and Activate Comment Mail
- Prompt appears properly 💯

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#314).
