### ISSUE TITLE
StCR conflict detection no longer working

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#315]
The conflict detection for Subscribe to Comments Reloaded is no longer working. When both StCR and Comment Mail are active, there is no Dashboard notice indicating that both plugins should not be enabled at the same time.

## Steps to reproduce

- Install Comment Mail >= v161110-RC and StCR v160915+
- Activate and enable both plugins

## Observed Behavior

No Dashboard messages appear.

## Expected Behavior

A Dashboard notice should warn me that StCR and Comment Mail should not be enabled at the same time.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** The conflict check for 'Subscribe to Comments Reloaded' was not working in the previous release; i.e., if you attempt to activate both Comment Mail and the 'Subscribe to Comments Reloaded' plugin at the same, this should result in a Dashboard warning. Fixed in this release. See [Issue #315](https://github.com/websharks/comment-mail/issues/315).

**Comment by jaswsinc** [comment]
_Noting that this particular conflict detection never existed prior. However, it is now._

**Comment by raamdev** [comment]
> Noting that this particular conflict detection never existed prior. However, it is now.

Hmm, that's very odd. I'm almost certain I remember seeing a Comment Mail message telling me that StCR and Comment Mail shouldn't be active at the same time... maybe I imagined it!

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Confirmed Working

Prompt appears and does not activate Comment Mail if StCR is present.

![screen shot 2016-12-13 at 3 55 32 pm](https://cloud.githubusercontent.com/assets/13220018/21132105/4852e59c-c14d-11e6-8139-addcda3286ce.png)

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#315).
