### ISSUE TITLE
SparkPost logo appears when Mandrill RVE handler is selected

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#318]
When the Mandrill RVE handler is selected in **Comment Mail → Config. Options → Replies via Email (RVE Handler)**, the SparkPost logo appears to the right. The Mandrill logo (or no logo) should appear instead:

![2016-11-17_20-12-09](https://cloud.githubusercontent.com/assets/53005/20414774/420bb8ee-ad02-11e6-8177-9d4b3c9234b3.png)

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** Do not show SparkPost partner image when Mandrill is selected as the RVE handler. See [Issue #318](https://github.com/websharks/comment-mail/issues/318).

**Comment by jaswsinc** [comment]
_Noting that the Mandrill logo will be shown when Mandrill is selected._

**Comment by renzms** [comment]
@jaswsinc 

Works in the latest bleeding edge version. 👍 

![screen shot 2016-12-09 at 7 28 03 pm](https://cloud.githubusercontent.com/assets/13220018/21047587/aa206ba6-be45-11e6-8826-bc7e6fb8bbe6.png)

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#318).
