### ISSUE TITLE
MailChimp Integration: Empty API Key field autofills with password from browser

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#319]
If you have a password saved in your browser autofill, saving the Comment Mail options with MailChimp Integration enabled but the MailChimp API Key field empty, you can end up with a browser-filled password in the field:

![2016-11-17_20-22-51](https://cloud.githubusercontent.com/assets/53005/20415030/b464e9a0-ad03-11e6-99d4-e05450194f5a.png)

We dealt with this same issue in Comet Cache recently; see https://github.com/websharks/comet-cache/issues/741. 

----

The fix that covers both Firefox and Chrome seems to be the following:

> It looks like we can use `autocomplete="off"` in the `<form>` tag and Firefox will obey that. Then we can use `autocomplete="new-password"` in the individual fields, and Chrome will obey that

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** Prevent browser autocomplete in Comment Mail options. See [Issue #319](https://github.com/websharks/comment-mail/issues/319).

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Confirmed Working

![screen shot 2016-12-13 at 3 24 09 pm](https://cloud.githubusercontent.com/assets/13220018/21131202/4e3a3e88-c148-11e6-9acf-58591dba1505.png)

The MailChimp Integration fields do not autocomplete. 👍

**Comment by raamdev** [comment]
**Comment Mail v161213** has been released and includes changes from this GitHub Issue. See the [v161213 announcement](https://comment-mail.com/comment-mail-v161213-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#319)
