### ISSUE TITLE
Bug: Templates Not Saving

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#322]
## Steps to Reproduce

- Change a default template from the Dashboard.
- Click 'Save All Changes'.

## Expected Behavior

Templates would be saved.

## Observed Behavior

Templates not saved.

**Comment by raamdev** [comment]
Confirmed. Tested with Comment Mail Pro v161118. Tested both in Simple mode and Advanced mode. In both cases, changes to default templates are not saved.

**Comment by raamdev** [comment]
@jaswsinc If you can get this fixed ASAP, I'd like to do a maintenance release on Monday, November 28th.

**Comment by jaswsinc** [comment]
Referencing internal/private ticket: https://app.intercom.io/a/apps/zbpo3mkk/inbox/me@jaswsinc.com/conversations/6979498916

Also referencing internal/private ticket:
https://websharks.zendesk.com/agent/tickets/15041

**Comment by tech55541** [comment]
I hope there's a way to get my templates back. All that work out the door. So, so not good. That was multiple days worth of work to make things accessible and work properly with my setup and now it's all gone. Really interested to see if this will get fixed.

**Comment by raamdev** [comment]
@tech55541 Did updating to the latest version of Comment Mail cause the customized templates to revert to their defaults?

**Comment by tech55541** [comment]
@raamdev As soon as I enabled SSO integration and entered my Twitter information, I noticed all my templates were wiped clean. Not to mention SSO has some problems, but I will troubleshoot that later.

**Comment by raamdev** [comment]
@tech55541 Yikes! This bug sounds worse than I thought. Do you have a site backup by any chance that might include a backup of the database, just in case the custom templates did in fact get overwritten?

Also, just to clarify: You were running the previous version of Comment Mail and had customized templates, then you upgraded to v161118 and after upgrading you enabled SSO, which caused the custom templates to disappear?

**Comment by tech55541** [comment]
@raamdev No, checked the other day, backups were not working. I can't go back to the one I have since it would be on Sunday. I did the latest update and then enabled SSO, after saving, everything was wiped out. I think it's all gone, it wiped site and email templates.

**Comment by raamdev** [comment]
> I think it's all gone, it wiped site and email templates.

Ugh, I'm VERY sorry. ☹️  I'm still waiting for more info from @jaswsinc on whether or not this bug would've wiped out the saved templates, but one thing you could try doing right now is exporting your Comment Mail options (**Comment Mail → Config. Options → Import/Export → Export Config. Options**) and see if the custom templates appear in the export file.

Please send me a support message via https://comment-mail.com/support/ so that I can refund your Pro purchase. I know that it won't get the templates back, but it's the least I can do.

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Bug Fix:** This release corrects a nasty bug that was first introduced in the previous release, resulting in the loss of template modifications when/if any Comment Mail options were edited after having upgraded to the previous release. See [Issue #322](https://github.com/websharks/comment-mail/issues/322).

  In short, please avoid v161118 (the previous release).

  _**Note:** If you already upgraded to v161118, but you have not edited your Comment Mail options yet (or had no template modifications anyway), there is no cause for alarm._

  _However, if you upgraded to v161118 and **did** edit your Comment Mail options after updating, and if you also modified Comment Mail templates, you may have experienced a loss of template data; i.e., the changes you made to the default templates may have been lost as a result of this bug. We are very sorry about this. Please see [Issue #322](https://github.com/websharks/comment-mail/issues/322) for additional details._

**Comment by jaswsinc** [comment]
@tech55541 @raamdev I can confirm that this bug did result in a loss of the data associated with custom templates. Short of pulling a WordPress database backup, I'm afraid there is no path in Comment Mail itself to the recovery of the custom templates lost in the previous release.

Very sorry about this. It was my fault for having made a mistake in the previous release.

**Comment by raamdev** [comment]
**Comment Mail v161129** has been released and includes changes from this GitHub Issue. See the [v161129 announcement](http://comment-mail.com/comment-mail-v161129-maintenance-release/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#322).
