### ISSUE TITLE
Empty message on notification

### ISSUE THREAD

**Issue by IvanRF** [websharks/comment-mail#323]
I'm still on **v160213**, if this issue was fixed before, forget about it. If not, today I received a mail notification in which the comment content was empty. That is, `[comment_clip]` was replaced by an empty string.

The template is:
```
<p style="font-size:110%; font-weight:bold;">
	This comment was posted [comment_time_ago][if comment_author] by [comment_author][endif].
</p>
<p style="font-size:130%;border: 1px solid #d12028;padding: 15px;margin-top: 17px;-webkit-border-radius: 3px;-moz-border-radius: 3px;border-radius: 3px;">
	[comment_clip]
</p>
```

and the mail had this:

```
<p style="font-size:110%;font-weight:bold">
	This comment was posted 7 hours ago by Gisela.
</p>
<p style="font-size:130%;border: 1px solid #d12028;padding: 15px;margin-top: 17px">
	
</p>
```

This is the first time it happens, any thoughts? could it be a failure when reading the comment from the database?

**Comment by raamdev** [comment]
@IvanRF It's hard to say. We don't run tests against old versions of the software (v160213 is 9 months old). The best thing to do is update and see if that fixes the issue. I'm willing to bet it will, as I recall work related to `[comment_clip]` occurring over the past 9 months.
