### ISSUE TITLE
The plugin shows the options without a layout

### ISSUE THREAD

**Issue by ignaciosantiago** [websharks/comment-mail#329]
Hi, 

I would like to show the layout of the options with an "order". If you see the option to subscribe, it is not in its place (ex. https://frenchiemania.com/razones-para-no-comprar-bulldog-frances)

**Comment by raamdev** [comment]
@ignaciosantiago We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://forums.wpsharks.com/c/comment-mail) (for Comment Mail Lite) or open a [Support Ticket](https://comment-mail.com/support/) (Comment Mail Pro). Thank you! :)
