### ISSUE TITLE
Testing Comment Mail with WordPress v4.8

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail#338]
**This issue is to note any errors with Comet Cache Lite + Pro and WordPress v4.8**

### Tested with
_________

**WordPress 4.8-RC2-40868**
**Current WordPress Theme: Twenty Seventeen version 1.2**

**Active Plugins: Comment Mail Lite / Pro Version 161213**
**PHP Version: 7.1.3-3+deb.sury.org~xenial+1
MySQL Version: 10.0.29-MariaDB-0ubuntu0.16.04.1**

_____
### Comment Mail Lite Version 161213  Test || with WP_DEBUG disabled
<details><summary>Results with WP_DEBUG disabled</summary>

```
**No Issues found**
```

```
**No issues with Confirmation:**

```

</details>

_____
### Comment Mail Lite Version 161213  Test  || with WP_DEBUG enabled

<details><summary>Results with WP_DEBUG enabled</summary>

</details>

_______
### Comment Mail Pro Version 161213  Test || with WP_DEBUG disabled

<details><summary>Results with WP_DEBUG disabled</summary>

</details>

**Comment by renzms** [comment]
@raamdev 

**Status: Testing still in progress**

Just wanted to give a heads up, found an Error prompt only when `WP_DEBUG` was enabled for both Comment Mail Lite/Pro versions. When clicking the confirmation link from the Confirmation Subscription Email, you are redirected to a page with - `Deprecated: Function mcrypt_list_algorithms():` 

Details in the report above.

**Comment by raamdev** [comment]
> Deprecated: Function mcrypt_list_algorithms()

Can you please open a GitHub issue for that and reference the two lines in the source code where this function is used:

https://github.com/websharks/comment-mail/blob/161213/src/includes/classes/UtilsEnc.php#L124
https://github.com/websharks/comment-mail/blob/161213/src/includes/classes/UtilsEnc.php#L171

**Comment by renzms** [comment]
@raamdev 

Created GHI here: https://github.com/websharks/comment-mail/issues/340

Thanks!

**Comment by raamdev** [comment]
@renzms The issue with the deprecated `mcrypt_list_algorithms()` function is not related to WP v4.8 but rather PHP 7, so if there are no other issues found with WP v4.8, I'd like to mark this as closed.

**Comment by renzms** [comment]
@raamdev 

Sounds right to me, I'll update the above results. Thanks!
