### ISSUE TITLE
Use Proper Case for Statuses and Events on UI

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#72]
While it's fine to use all lowercase for the statuses and events in the database (e.g., `subscribed`, `unsubscribed`, `trashed`, `inserted`, etc.) it would be nice to use proper case (`Subscribed`, `Unsubscribed`, `Trashed`, `Inserted`, etc.) on the front-end UI. 

It feels a bit out of place to see everything else in the Subscriptions table and the Event Log using proper case except for the statuses and events:

![2014-12-09_20-37-01](https://cloud.githubusercontent.com/assets/53005/5369556/a87dbac6-7fe3-11e4-84dc-0ef8abf860ee.png)

![2014-12-09_20-42-40](https://cloud.githubusercontent.com/assets/53005/5369586/1ce8a8da-7fe4-11e4-9351-84bfb9360511.png)

---

## Next Actions / Project Outline

See: <https://quire.io/w/7C4cVjc0O3g2ZXK3OnQUG9eJ/Modify_i18n_Utilitie...>

**Comment by jaswsinc** [comment]
## Next Actions / Project Outline

See: <https://quire.io/w/7C4cVjc0O3g2ZXK3OnQUG9eJ/Modify_i18n_Utilitie...>

**Comment by jaswsinc** [comment]
@kristineds You're welcome to give this one a shot if you'd like. It was outlined on Quire a while back and it's one that might be good practice. If you decide to tackle it just let me know and I can help if you need it.

**Comment by jaswsinc** [comment]
Be sure to expand the details "read more" link on Quire.
![2015-08-21_08-10-52](https://cloud.githubusercontent.com/assets/1563559/9413094/3355c362-47dc-11e5-97cf-12f42d2ee20b.png)

**Comment by jaswsinc** [comment]
It's these steps only.

![2015-08-21_08-11-46](https://cloud.githubusercontent.com/assets/1563559/9413106/4ef6d020-47dc-11e5-96fa-5200b08cbc62.png)

**Comment by kristineds** [comment]
@jaswsinc I'm ready to work on this. Should I start with creating a feature branch for this issue and work on the "Modify i18n Utilities Class" step?

**Comment by kristineds** [comment]
@jaswsinc Submitting PR for CM Lite and Pro to **Modify i18n Utilities Class**
- websharks/comment-mail/pull/142
- websharks/comment-mail-pro/pull/18

**Comment by jaswsinc** [comment]
> Should I start with creating a feature branch for this issue and work on the "Modify i18n Utilities Class" step?

Perfect, yes. I merged your PRs for step one. Nice!

**Comment by kristineds** [comment]
@jaswsinc Cool! Could you please you give me some guidance on what to do on the next step ~ Update Codebase; i.e., Utility Calls (Run a search on the entire codebase for calls to those i18n utilities)? Thanks

**Comment by jaswsinc** [comment]
What you want to search for is `i18n->action_ed(`
See: https://atom.io/docs/v1.0.7/using-atom-find-and-replace

Note also, that in this file, there are still several other utilities that need to be converted in much the same way that you did with `action_ed()`; i.e., to add the `$transform` parameter and adjust the code to deal with the `$transform` parameter. See: [this checklist item](https://quire.io/w/7C4cVjc0O3g2ZXK3OnQUG9eJ/Modify_i18n_Utilitie...).

These are the methods that still need work:

- `status_label()` https://github.com/websharks/comment-mail/blob/5d1e9b97395e165ce2eba00d2b69bce8f83664e7/comment-mail/includes/classes/utils-i18n.php#L98

- `deliver_label()` https://github.com/websharks/comment-mail/blob/5d1e9b97395e165ce2eba00d2b69bce8f83664e7/comment-mail/includes/classes/utils-i18n.php#L191

- `sub_type_label()` https://github.com/websharks/comment-mail/blob/5d1e9b97395e165ce2eba00d2b69bce8f83664e7/comment-mail/includes/classes/utils-i18n.php#L221

---

Once each of these are converted, you will need to search the codebase to find areas where each of these have been used also, and update accordingly; e.g., `i18n->status_label(`, `i18n->deliver_label(`, and `i18n->sub_type_label(`

**Comment by kristineds** [comment]
@jaswsinc: Can you check this code when you get the chance before I send the PR for it? :) Thanks! https://gist.github.com/kristineds/72f15c4833dc102cb0f6

**Comment by kristineds** [comment]
@jaswsinc Submitting PRs for CM Lite and Pro to Update codebase for i18n utility calls:
- websharks/comment-mail/pull/143
- websharks/comment-mail-pro/pull/19

**Comment by jaswsinc** [comment]
@kristineds Merged both of those. Thank you!

---

## Next Actions (Final Step)

- New feature branch:

  ```bash
  $ cd ~/projects/websharks/comment-mail
  $ git checkout 000000-dev # Start from the dev branch.
  $ git pull # Make sure your local dev branch is up-to-date with the remote copy.
  $ git checkout -b feature/72-step-3 # New feature branch based on dev branch.
  ```

- Search the codebase to find areas where each of those i18n utilities have been used; i.e., search for the word fragments:

  - `i18n->action_ed(`
  - `i18n->status_label(`
  - `i18n->event_label(`
  - `i18n->deliver_label(`
  - and `i18n->sub_type_label(`

- Review [Raam's request above](https://github.com/websharks/comment-mail/issues/72#issue-51507802) and attempt to locate the i18n calls that correlate with the labels he suggested that we update. Many of those will be in files that end with `-table.php` or `-table-base.php`.

- **Mission:** To update each of those i18n function calls, so that we pass the new [`$transform` parameter](https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/classes/utils-i18n.php#L33) you added, as `ucwords` (i.e., to force uppercase in first letter of each word). That way we will be displaying `Unsubscribed`, `Trashed`, `Inserted`, etc.. Instead of the all-lowercase labels that we have now.

  - For example. See [these lines](https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/classes/menu-page-subs-table.php#L181-L186). They should be changed to the following:

    ```php
    'status::unconfirmed' => $plugin->utils_i18n->status_label('unconfirmed', 'ucwords'),
    'status::subscribed'  => $plugin->utils_i18n->status_label('subscribed', 'ucwords'),
    'status::suspended'   => $plugin->utils_i18n->status_label('suspended', 'ucwords'),
    'status::trashed'     => $plugin->utils_i18n->status_label('trashed', 'ucwords'),
    ```

    _Note that we are adding the `$transform` parameter; i.e., `, 'ucwords'`_

**Comment by kristineds** [comment]
@jaswsinc Submitting PRs for CM Lite and Pro for Step 3

- websharks/comment-mail/pull/145
- websharks/comment-mail-pro/pull/20

**Comment by jaswsinc** [comment]
@kristineds Merged both. Nice work! :100:

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Improved the Subscriptions table and the Event Log UI by using proper case for Status and Event values. Props @kristineds. See [Issue #72](https://github.com/websharks/comment-mail/issues/72).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Improved the Subscriptions table and the Event Log UI by using proper case for Status and Event values. Props @kristineds. See [Issue #72](https://github.com/websharks/comment-mail/issues/72).

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#72).
