### ISSUE TITLE
SSO to Show Service Connection in Dashboard

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#73]
The SSO integration should show an indication of which SSO service is connected to a user's account from the Dashboard so that site owners can know what to tell a user if they have trouble accessing their account.

![2014-12-14_00-27-10](https://cloud.githubusercontent.com/assets/1563559/5426938/01935976-8328-11e4-81d4-a7cbb4a0e92b.png)

**Comment by jaswsinc** [comment]
## Next Actions (Pro Version Only)

- New feature branch in the `websharks/comment-mail-pro` repo.

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/includes/classes/utils-sso.php#L151) add the following:

  ```php
  $user_sso_services = get_user_option(__NAMESPACE__.'_sso_services');
  $user_sso_services = is_array($user_sso_services) ? $user_sso_services : array();
  $user_sso_services = array_unique(array_merge($user_sso_services, array($service)));
  update_user_option($user_id, __NAMESPACE__.'_sso_services', $user_sso_services);
  ```

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L687) add the following:

  ```php
  add_filter('manage_users_columns', array($this, 'manage_users_columns'), 10, 1);
  add_filter('manage_users_custom_column', array($this, 'manage_users_custom_column'), 10, 3);
  ```

- After [this line](https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L1716) add the following:

  ```php
  /**
   * Adds columns to the list of users.
   *
   * @since 15xxxx Enhancing users list.
   *
   * @attaches-to `manage_users_columns` filter.
   *
   * @param array $columns Existing columns passed in by filter.
   *
   * @return array Filtered columns.
   */
  public function manage_users_columns(array $columns)
  {
    $user_columns = &$this->static_key(__FUNCTION__);
    $user_columns = new user_columns();
    
    return $user_columns->filter($columns);
  }

  /**
   * Fills columns in the list of users.
   *
   * @since 15xxxx Enhancing users list.
   *
   * @attaches-to `manage_users_custom_column` filter.
   *
   * @param mixed $value Existing column value passed in by filter.
   * @param string $column Column name; passed in by filter.
   * @param int|string $user_id User ID; passed in by filter.
   *
   * @return mixed Filtered column value.
   */
  public function manage_users_custom_column($value, $column, $user_id)
  {
    if(!($user_columns = &$this->static_key('manage_users_columns')))
      return $value; // Not possible to fill; no class instance.

    return $user_columns->maybe_fill($value, $column, $user_id);
  }
  ```

- Add a new class file in [this directory](https://github.com/websharks/comment-mail-pro/tree/150709/comment-mail-pro/includes/classes).

  ```php
  <?php
  /**
   * User Columns
   *
   * @since 15xxxx Adding custom user columns.
   * @copyright WebSharks, Inc. <http://www.websharks-inc.com>
   * @license GNU General Public License, version 3
   */
  namespace comment_mail // Root namespace.
  {
    if(!defined('WPINC')) // MUST have WordPress.
      exit('Do NOT access this file directly: '.basename(__FILE__));

    if(!class_exists('\\'.__NAMESPACE__.'\\user_columns'))
    {
      /**
       * User Columns
       *
       * @since 15xxxx Adding custom user columns.
       */
      class user_columns extends abs_base
      {
        /**
         * Class constructor.
         *
         * @since 15xxxx Adding custom user columns.
         */
        public function __construct()
        {
          parent::__construct();
        }

        /**
         * Filter (and add) user columns.
         *
         * @since 15xxxx Adding custom user columns.
         *
         * @param array $columns Existing columns.
         *
         * @return array Filtered columns.
         */
        public function filter(array $columns)
        {
          if(!$this->plugin->options['enable'])
            return $columns; // Not applicable.

          if($this->plugin->options['sso_enable'])
            $columns[__NAMESPACE__.'_sso_services'] = __('SSO Service', $this->plugin->text_domain);

          return $columns;
        }

        /**
         * Maybe fill custom user columns.
         *
         * @since 15xxxx Adding custom user columns.
         *
         * @param mixed $value Existing column value.
         * @param string $column Column name.
         * @param int|string $user_id User ID.
         *
         * @return mixed Filtered value.
         */
        public function maybe_fill($value, $column, $user_id)
        {
          if ($column === __NAMESPACE__.'_sso_services') {
            $user_sso_services = get_user_option(__NAMESPACE__.'_sso_services', $user_id);
            $user_sso_services = is_array($user_sso_services) ? $user_sso_services : array();
            $value = $user_sso_services ? implode(', ', $user_sso_services) : '—';
          }
          return $value;
        }
      }
    }
  }
  ```

- Submit PR.

---

**Tip:** While working on this issue you can take note of how WordPress fills custom columns added by plugins. See [this line of code](https://github.com/WordPress/WordPress/blob/8a386cb24f701502eceb30160425303882df8596/wp-admin/includes/class-wp-users-list-table.php#L499) in the WordPress core.

**Comment by jaswsinc** [comment]
Next Pro Release Changelog:

- **SSO Improvement:** If you have Comment Mail's SSO integration enabled and have users who are registering an account via Facebook, Twitter, LinkedIn, or Google+, the SSO service that a particular user (or commenter) signed up with is now shown in the list of Users. Props @kristineds See also [this GitHub issue](https://github.com/websharks/comment-mail/issues/73) if you'd like additional details.

  ![2015-11-03_21-06-16](https://cloud.githubusercontent.com/assets/1563559/10931000/00a088e8-8270-11e5-9510-15deee65eddd.png)

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#73).
