### ISSUE TITLE
MySQL tables SQL 'COMMENT' unsupported?

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#74]
@jaswsinc Regarding the issue I discovered while attempting to activate Comment Mail v141206-beta9 on raam.org, running MySQL v5.1.73:

> Fatal error: Uncaught exception 'Exception' with message 'DB table creation failure: `wp_comment_mail_queue_event_log` CREATE TABLE IF NOT EXISTS `wp_comment_mail_queue_event_log` ( `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key.', `queue_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'Queue entry ID from the `queue` table; at the time of the event. The entry may or may not still exist.', `dby_queue_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'Digested by queue entry ID from the `queue` table; at the time of the event. The entry may or may not still exist.', `sub_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'Subscription ID from the `subs` table; at the time of the event. The subscription may or may not still exist.', `user_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'User ID from the `wp_users` table; at the time of the event, if applicable. The user may or may not still exist.', `post_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'Post ID from the in /home/raamorg/public_html/wordpress/wp-content/plugins/comment-mail/includes/classes/installer.php on line 60

I noticed the SQL output in that error message was getting cut off after `COMMENT 'Post ID from the in` and that led me to try removing any `COMMENT`'s that contain backticks. Sure enough, that started to fix things, however I continued running into errors that always seemed to break on a `COMMENT`.

When I removed all `COMMENT` lines from all `includes/tables/*.sql` files, everything worked as expected and Comment Mail activated. 

I then searched the [MySQL documentation for comment syntax](http://dev.mysql.com/doc/refman/5.7/en/comments.html) to see what version of MySQL is required to use `COMMENT` and was surprised to discover that not even MySQL v5.7 makes any mention of `COMMENT`. For comments, we can use `#`, `--`, and `/* */`, but I'm not seeing `COMMENT` mentioned anywhere.

When I replaced all the `COMMENT`'s in the `includes/tables/*.sql` files with `#` (and moved the comma's that separate lines to just before the `#`), everything worked as expected.

**Comment by jaswsinc** [comment]
Great. Thank you for the help on this :-)
