### ISSUE TITLE
Possible release / Beta testing?

### ISSUE THREAD

**Issue by jmslbam** [websharks/comment-mail#75]
Hi everyone!

I came here after following the trail of STCR and @raamdev and I am pleased too see a possible alternative.

A client of ours is in need of a modern solution of STCR and would like to purchase a pro version when released. Do you have a roadmap / estimation of when it could be tested / tried? 

I could not test the current Beta plugin because of all the git submodules being private...  

I even suggested that if they really wanted a solution to customize e-mails and a more user-friendly "management page" he could donate to speed things up ;) 

Thanks in advance

**Comment by raamdev** [comment]
@jmslbam Thank you for showing interest. :-) We currently have our internal milestone set for a March 1st initial public release. But that's an internal milestone date, so no promises!

I'm not sure if we have a beta mailing list setup for this project yet that you could get on to be notified when a beta is available. @jaswsinc is the lead on this project, so he would be the one to ask. 

@jaswsinc do we have a beta mailing list setup yet? If not, can we do that asap?

**Comment by jaswsinc** [comment]
> @jaswsinc do we have a beta mailing list setup yet? If not, can we do that asap?

No, not yet. I'm adding this to my list for the week. I'll follow-up here when it's ready :-) Thanks!

**Comment by jaswsinc** [comment]
@jmslbam Mailing list is here :-) http://eepurl.com/bdRcLr

**Comment by raamdev** [comment]
> Mailing list is here :-) http://eepurl.com/bdRcLr

Woohoo! Thanks @jaswsinc. :-) 

@jmslbam I'm going to close this Issue, but please do get on that mailing list so that we can contact you as soon as something is ready for testing. :-)

**Comment by jmslbam** [comment]
Aight! Thanks for the mailing list, subscribed to it! And thank you for the response! Closing this one is fine. Good luck with development!
