### ISSUE TITLE
Security Issue w/ User ID to Emails

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#76]
Accessing the Subscriptions Summary page can result in the exposure of others email addresses whenever the `key` is not associated with a user ID and there are other email addresses in the database with a `user_id` of `0`.

Referencing bug fix here: https://github.com/websharks/comment-mail/commit/27764b521d9ba9ac4a3aecb80037090a197906f0

Thank you @raamdev for reporting this!

**Comment by raamdev** [comment]
@jaswsinc Glad I was able to catch this one! :-) I discovered it at random, clicking a link I didn't even need to click but wondered, "Hmm, what will happen if I click this?"
