### ISSUE TITLE
Improve Default Comment Reply Notification Template

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#77]
The current default Comment Mail "New comment" notification email feels way too busy and there are several things I feel could greatly improve it.

---

by @jaswsinc See Next Actions / Project Outline: https://quire.io/w/kx2VYsoJkIs4L6P3pfFuVDVg/Understanding_Commen

---

Here's an example of the current default new comment reply notification email:

## As seen from GMail

![2015-03-24_21-43-32](https://cloud.githubusercontent.com/assets/53005/6817153/87e991e4-d273-11e4-971d-50347cf99cf4.png)

## As seen from an iPhone 5

![img_4958](https://cloud.githubusercontent.com/assets/53005/6817193/f530e3ce-d273-11e4-95a2-426ef0910d4a.PNG)

- **A)** The small font size in the author quote is too small, especially on mobile devices. It also doesn't need to be part of a list item. It's unnecessary to mention the author name, since the recipient of the email is the author--it's redundant. Showing and linking the comment ID is also unnecessary (it means nothing to the person receiving the email and there's already a link to their comment in the "New Reply to 'your Comment' on..." section right above). 

     The clip here is also weird: it shows the beginning and the end of the comment, which makes you quickly feel lost reading your own comment. It would be better to just give a clip of the beginning of the comment, which would be enough to remind the author of the comment they left. I would also increase the default length of the clip here to `300` characters. Anywhere there _is_ a clip, it should be `[...]` instead of just `...`, as the latter can easily be mistaken for an ellipsis added by the commenter.
- **B)** The main comment reply text doesn't need to be a list item. The default clip here of `200` characters is way too short. The default should really be `1000`+ characters, if not something even higher. The whole point of this notification email is to see this content (the reply comment), so this is the most important content in the entire email. I would be comfortable setting this to `5000` characters by default. 

- **C)** I would get rid of the "Create New Subscription" section in the comment reply notification email. It doesn't seem like the right context here... "create a new subscription to what?" The only place people will be thinking about creating a comment subscription is when they're on the site viewing comments. I would also move the "Our Mailing Address" to the bottom of "Contact Info" and get rid of the tables that currently make the structure of this section. On mobile devices, tables totally fail (see mobile screenshot above). 

## Revised comment reply notification email mockup (GMail)

![2015-03-24_22-15-13](https://cloud.githubusercontent.com/assets/53005/6817350/cc0bb31e-d275-11e4-9862-273b3a283d1c.png)

**Comment by jaswsinc** [comment]
Thank you. I most work on this during the soft launch and try to improve before the official launch.

**Comment by kristineds** [comment]
@jaswsinc Do you need help with this? :)

**Comment by jaswsinc** [comment]
> Do you need help with this? :)

Yes, and I will do my best to outline a game plan for this soon. For the moment though, I don't enough information together in order to expose what needs to happen here. Will work on it! :-)

**Comment by kristineds** [comment]
> Will work on it! :-)

Cool. Looking forward to it. :)

**Comment by jaswsinc** [comment]
@kristineds @raamdev I posted an outline of how to complete the work on (A). Please see: https://quire.io/w/kx2VYsoJkIs4L6P3pfFuVDVg/Understanding_Commen... if you'd like to learn more about how you can help on this issue.

**Comment by raamdev** [comment]
@kristineds @jaswsinc I'm going to assign this issue to myself and work on completing this.

**Comment by raamdev** [comment]
## New Screenshots

As an update to [the screenshots I posted at the top](https://github.com/websharks/comment-mail/issues/77#issue-64154434), here is how things look on the desktop (Gmail) and on mobile (an iPhone 6s) after the changes I committed in #174 (Lite) and https://github.com/websharks/comment-mail-pro/issues/35 (Pro):

### Gmail (desktop)

![2015-12-12_18-08-53](https://cloud.githubusercontent.com/assets/53005/11764411/ec819d70-a0fb-11e5-8566-d60ef619293b.png)

### iPhone 6s (mobile)

![2015-12-12_18-05-55](https://cloud.githubusercontent.com/assets/53005/11764403/bb14dafe-a0fb-11e5-8728-5a8f37b735cb.png)

![2015-12-12_18-06-25](https://cloud.githubusercontent.com/assets/53005/11764407/c85c6cea-a0fb-11e5-965c-59e88e4a9b31.png)

**Comment by raamdev** [comment]
Next Lite Release Changelog:

- **Enhancement**: Many improvements the default email templates. The templates are now fully responsive and look much better on mobile devices. The wording in several places was also cleaned up for clarity and consistency and any references to an ID# (which is generally useless for readers) have been removed. The default templates also use a single font style now instead of mixing font styles and the email templates no longer use tables (this improves responsiveness). If you've modified the default Comment Mail email templates on your site, your changes will not be overwritten by updating, however if you've modified the templates and you want to get these changes, you'll need to reset to the default email templates and make your changes again (you can do this by emptying the email template fields completely and saving your options). See [Issue #77](https://github.com/websharks/comment-mail/issues/77).
- **Bug Fix**: Fixed an email template bug that was forcing an ellipsis to show even when the length of the comment content was shorter than the max length. See [this commit](https://github.com/websharks/comment-mail/commit/80aab562fb1fe3cdcdb4f10eda7e74c8ea21aa61) for details.
- **Bug Fix**: Fixed an email template bug that was not linking the "add reply" link directly to the comment form for replying to the comment (it was just linking to the comment itself). See [this commit](https://github.com/websharks/comment-mail/commit/686b2737e708dc4a70ede129b7f4a9151c150907#commitcomment-14925636) for details.
- **Enhancement**: Ellipses (`...`) in email templates are now surrounded by square brackets (i.e., `[...]`) to avoid confusion about whether or not the ellipsis was part of the comment content. See [Issue #77](https://github.com/websharks/comment-mail/issues/77).
- **Enhancement**: In the email templates, the "Add Reply" links have been changed to "Reply" and when the reply is in response to someone and we have the authors name, the link includes the authors name (e.g., "Reply to <author-name>"). See [Issue #77](https://github.com/websharks/comment-mail/issues/77).
- **Enhancement**: Updated email templates to use `\WP_Comment` instead of `\stdClass` where appropriate. See [Issue #77](https://github.com/websharks/comment-mail/issues/77).

**Comment by raamdev** [comment]
Next Pro Release Changelog:

- **Enhancement**: Many improvements the default email templates. The templates are now fully responsive and look much better on mobile devices. The wording in several places was also cleaned up for clarity and consistency and any references to an ID# (which is generally useless for readers) have been removed. The default templates also use a single font style now instead of mixing font styles and the email templates no longer use tables (this improves responsiveness). If you've modified the default Comment Mail email templates on your site, your changes will not be overwritten by updating, however if you've modified the templates and you want to get these changes, you'll need to reset to the default email templates and make your changes again (you can do this by emptying the email template fields completely and saving your options). See [Issue #77](https://github.com/websharks/comment-mail/issues/77).
- **Bug Fix**: Fixed an email template bug that was forcing an ellipsis to show even when the length of the comment content was shorter than the max length. See [this commit](https://github.com/websharks/comment-mail/commit/80aab562fb1fe3cdcdb4f10eda7e74c8ea21aa61) for details.
- **Bug Fix**: Fixed an email template bug that was not linking the "add reply" link directly to the comment form for replying to the comment (it was just linking to the comment itself). See [this commit](https://github.com/websharks/comment-mail/commit/686b2737e708dc4a70ede129b7f4a9151c150907#commitcomment-14925636) for details.
- **Enhancement**: Ellipses (`...`) in email templates are now surrounded by square brackets (i.e., `[...]`) to avoid confusion about whether or not the ellipsis was part of the comment content. See [Issue #77](https://github.com/websharks/comment-mail/issues/77).
- **Enhancement**: In the email templates, the "Add Reply" links have been changed to "Reply" and when the reply is in response to someone and we have the authors name, the link includes the authors name (e.g., "Reply to <author-name>"). See [Issue #77](https://github.com/websharks/comment-mail/issues/77).
- **Enhancement**: Updated email templates to use `\WP_Comment` instead of `\stdClass` where appropriate. See [Issue #77](https://github.com/websharks/comment-mail/issues/77).

**Comment by jaswsinc** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by raamdev** [comment]
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#77).
