### ISSUE TITLE
Test Table Changes In Upcoming WP Release

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#78]
Referencing: https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/

**Comment by raamdev** [comment]
Referencing this comment on the aforementioned post that includes a bug report: https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/#comment-25443

We should make sure that we manually specify the index length as 191 in any MySQL CREATE TABLE statements that we write for VARCHARs.

**Comment by jaswsinc** [comment]
Thank you. I just reviewed CM against this issue. I'm not seeing any immediate problem. We don't use any indexes against the core tables, and all of the custom CM tables were created with a `utf8` charset and tested as such. I'm going to leave this open for future consideration though. Just in case we decide to upgrade the CM tables to `utf8mb4 `.

**Comment by jaswsinc** [comment]
I have been working with `utf8mb4` quite a bit in some recent projects. I just took another look at the Comment Mail source code and the tables that we use. I'm not seeing any compatibility issues against the latest versions of WordPress and these table changes.

As for Comment Mail itself, it currently uses the `utf8` charset and `utf8_unicode_ci` tables. Tables that use `utf8mb4` would be a little more modern, but Comment Mail itself doesn't have any reason to store 4 byte characters at this time. Since all of the testing thus far has been against `utf8`, I suggest leaving it as-is for now. If there is a need for `utf8mb4` in the future it should be an easy upgrade.
