### ISSUE TITLE
Full Security Review

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#85]
We need to do a full security review of Comment Mail prior to its initial release.

In particular, we need to test these areas:

- Add a new subscription from the front-end.
- Delete all subscriptions from the front-end.
- Subscription summary page on the front-end. A security issue was found here previously, and I believe there is still room for security hardening here; i.e., another look is in order, and some tweaks should be applied to harden security in every way possible.

**Comment by raamdev** [comment]
@jaswsinc Copy that. I'll test a few of these things as part of my review of Comment Mail Lite this week and report back here with my findings.

**Comment by jaswsinc** [comment]
Referencing prior security fix: https://github.com/websharks/comment-mail/commit/27764b521d9ba9ac4a3aecb80037090a197906f0

**Comment by jaswsinc** [comment]
@raamdev  My security review is complete now. I wanted to go back over the bug you reported some time back that was found on my site, and I did that. Hardened a few routines. Looks pretty good to me now. I'm not going to dwell on this any longer, I'll just wait and see what else might turn up in the rest of our collective testing.

I'll leave this open for you anything more you'd like to add/report here.

**Comment by raamdev** [comment]
@jaswsinc Noting a security issue I discovered here: https://github.com/websharks/comment-mail/issues/103

**Comment by jaswsinc** [comment]
> Noting a new security issue I discovered here (as of v150620): #103

Thank you. #103 has been closed. I'll leave this open for your review, but feel free to close this if you like.

**Comment by raamdev** [comment]
@jaswsinc Thanks! I'm closing this.
