### ISSUE TITLE
Quick Review of pre-release 150613

### ISSUE THREAD

**Issue by brucewsinc** [websharks/comment-mail#90]
Hey, I saw a notification for a pre-release of Comment Mail the other day, and I just tested it out. Looking good! Thought I'd give you a couple of my thoughts from my (limited) testing.

It may be useful to note that I'm running a clean installation of WordPress `4.2.2` with PHP version `5.3.29`. Apache `2.4.10`.

 - I got an error when I activated with the activation SQL. `Duplicate dolumn name 'insertion_region'`. I'll send you the entire error as a reply after I send this message.
 - Additionally, there was an Exception that said `Query failure` within the updater. Also sending after this message.
 - While testing, I noticed that comment moderation isn't an option that's editable from the plugin options page. That's something that a new User is going to stumble on (I think). I've been using WordPress for forever and I still had to dig through panels to turn that option off to get the plugin to work as expected. Might be something to think about.
 - All of the emails from Comment Mail (despite being fine both through the default `wp_mail` function, even if I template it with my own plugin) go straight to Spam for me. I would try checking the emails out at mailtrap.io to see if you can find out why. That's gonna be the first complaint from Users regardless, but if you can do something to help it along that might help everything out.

Those are all of my complaints. Otherwise, the plugin is GREAT! I love how the templating system is working, and even the base template looked good in every theme I tested it with. The emails send almost instantly, but I can see that you have a queue of some sort even for instant notifications.

Let me know if you need any more help testing anything out. I didn't test on MultiSite or any of the more advanced features, so there may be things I missed.

**Comment by brucewsinc** [comment]
Database Error: 
```
WordPress database error: [Duplicate column name 'insertion_region']
ALTER TABLE `wp_comment_mail_subs` ADD `insertion_region` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Geographic region code at time of insertion.', ADD `insertion_country` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Geographic country code at time of insertion.', ADD `last_region` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Last known geographic region code.', ADD `last_country` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Last known geographic country code.'
```

Exception on activation:
```
Fatal error: Uncaught exception 'Exception' with message 'Query failure.' in /private/etc/www/devs/wp-content/plugins/comment-mail/includes/classes/upgrader-vs.php:88 Stack trace: #0 /private/etc/www/devs/wp-content/plugins/comment-mail/includes/classes/upgrader-vs.php(54): comment_mail\upgrader_vs->from_lt_v141115() #1 /private/etc/www/devs/wp-content/plugins/comment-mail/includes/classes/upgrader-vs.php(43): comment_mail\upgrader_vs->run_handlers() #2 /private/etc/www/devs/wp-content/plugins/comment-mail/includes/classes/upgrader.php(57): comment_mail\upgrader_vs->__construct('141111') #3 /private/etc/www/devs/wp-content/plugins/comment-mail/includes/classes/upgrader.php(41): comment_mail\upgrader->maybe_upgrade() #4 /private/etc/www/devs/wp-content/plugins/comment-mail/plugin.inc.php(957): comment_mail\upgrader->__construct() #5 [internal function]: comment_mail\plugin->check_version('') #6 /private/etc/www/devs/wp-includes/plugin.php(496): call_user_func_array(Array, Array) #7 /private/etc/www/devs/wp-admin/admin.php( in /private/etc/www/devs/wp-content/plugins/comment-mail/includes/classes/upgrader-vs.php on line 88
```

**Comment by jaswsinc** [comment]
Awesome! :-) Thanks for the feedback Bruce.

---

> WordPress database error: [Duplicate column name 'insertion_region']

It seems that this comes from an update routine. Do you remember if you had a previous copy of Comment Mail running already, and then you updated to this version? Or, had you installed a copy of Comment Mail in the past to test with?

**Comment by brucewsinc** [comment]
> Or, had you installed a copy of Comment Mail in the past to test with?

I do think I had Comment Mail installed at some point in the past, yes. I just disabled and activated it again, and there was no issue this time. So that's probably why. I'll try making a fresh install later today and see if I can recreate the error again.

**Comment by raamdev** [comment]
@brucewsinc Holy crap, may I be the first to say it's great to see your name/face here! lmao... I thought it must've been a bug or something when I saw your avatar pop up in the Slack GitHub notification. :D

Also, thanks for the awesome critique of Comment Mail! That's _exactly_ the type of feedback we need. I'll be keeping your comments in mind as I go through a full review of Comment Mail myself this week.

**Comment by jaswsinc** [comment]
> So that's probably why. I'll try making a fresh install later today and see if I can recreate the error again.

Copy that. I think the problem with this was a version conflict that I introduced by not bumping the version with each new release that I made. I will take a closer look to be sure though. Thanks!

**Comment by jaswsinc** [comment]
Related issues resolved as part of the work here:

- https://github.com/websharks/comment-mail/issues/95
- https://github.com/websharks/comment-mail/issues/92
- https://github.com/websharks/comment-mail/issues/91

---

> I got an error when I activated with the activation SQL. Duplicate dolumn name 'insertion_region'. I'll send you the entire error as a reply after I send this message.

I reviewed the code for this again and I'm not seeing any problems. As I noted before, I believe this was a version conflict. If anyone sees this though, please let us know. Thanks again! @brucewsinc
