### ISSUE TITLE
Comment Moderation Option in Comment Mail Panel

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#91]
@brucewsinc writes...

> While testing, I noticed that comment moderation isn't an option that's editable from the plugin options page. That's something that a new User is going to stumble on (I think). I've been using WordPress for forever and I still had to dig through panels to turn that option off to get the plugin to work as expected. Might be something to think about.

**Comment by jaswsinc** [comment]
@brucewsinc To clarify, the confusion that you had was with the emails being sent out right, only _after_ a comment was approved. Is that right? What confused you about this exactly? Was it that you had to approve the comment before notifications went out?

**Comment by raamdev** [comment]
I _think_ he's referring to this default WordPress Discussion option:

![2015-06-17_16-09-47](https://cloud.githubusercontent.com/assets/53005/8217404/5223911a-150b-11e5-8114-2f10f3240f1d.png)

Basically, until the comment is approved, no subscribers are going to receive any emails. 

I personally don't see any confusion about this, but I can see how someone who maybe doesn't use WordPress for replying to comments on a regular basis and then suddenly installs Comment Mail and experiments with is might have some initial trouble figuring out why they're not receiving any of their test comment replies.

Assuming this is what @brucewsinc was referring to, a simple solution might be to have a little warning message somewhere that detects when comment moderation is enabled and notes that no emails will be sent until a comment is approved, along with  a link to **Settings → Discussion** where the site owner can review those settings.

**Comment by jaswsinc** [comment]
```
get_option('comment_moderation') || get_option('comment_whitelist')
```

**Comment by jaswsinc** [comment]
![](https://www.filepicker.io/api/file/l25kVM9aTY6A947tVHMe#.png)

**Comment by jaswsinc** [comment]
This has been implemented.
