### ISSUE TITLE
Spam Score in Comment Mail Notifications

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#92]
@brucewsinc writes...

> All of the emails from Comment Mail (despite being fine both through the default wp_mail function, even if I template it with my own plugin) go straight to Spam for me. I would try checking the emails out at mailtrap.io to see if you can find out why. That's gonna be the first complaint from Users regardless, but if you can do something to help it along that might help everything out.

**Comment by jaswsinc** [comment]
```php
<?php
function mailtrap($phpmailer) {
  $phpmailer->isSMTP();
  $phpmailer->Host = 'mailtrap.io';
  $phpmailer->SMTPAuth = true;
  $phpmailer->Port = 2525;
  $phpmailer->Username = '37794a46e1c0a25c0';
  $phpmailer->Password = 'xxxxxxxxxxxxxxxxxxxxxxx';
}

add_action('phpmailer_init', 'mailtrap');
```

**Comment by jaswsinc** [comment]
![](https://www.filepicker.io/api/file/eqUMDnbCTWyNMencrThj#.png)

**Comment by jaswsinc** [comment]
Spam score improved.

![](https://www.filepicker.io/api/file/U5fcnnfrTMCP2suP9HWk#.png)

**Comment by raamdev** [comment]
Awesome!
