### ISSUE TITLE
"Upgrading from StCR" Dashboard message

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#97]
(Note: This is as of v150620.)

![2015-06-22_19-21-54](https://cloud.githubusercontent.com/assets/53005/8295823/626810c8-1916-11e5-93ea-d59484b6f5e7.png)

## A

I was alarmed when I saw this line after installing Comment Mail on my personal site (where I currently have over 1,000 StCR subscriptions and where I've carefully tweaked things to work just right). (**NOTE:** The message says that StCR has been automatically deactivated, however upon checking I discovered that StCR was still active.)

I don't think we should deactivate StCR automatically--we should instead strongly suggest doing so _after_ importing subscriptions (**Comment Mail → Import/Export → Subscribe to Comments Reloaded (StCR)**). I would even show a persistent dashboard message that warns the site owner when Comment Mail detects these two plugins enabled at the same time (note that I said _enabled_; if Comment Mail is Active but not enabled that shouldn't matter--but if CM is active _and_ enabled _and_ we detect StCR is also enabled, then we should show a warning that CM + StCR being enabled at the same time can have very adverse side-effects).

## B

What settings were imported? That's the first thing I would wonder as a site owner installing Comment Mail for the first time who's also a long-time StCR user. We should make a list of the settings that are imported and write a KB Article that describes what gets imported, then link to that KB Article from inside this Dashboard message.

---

Related: https://github.com/websharks/comment-mail/issues/80

**Comment by jaswsinc** [comment]
@raamdev writes...
> I don't think we should deactivate StCR automatically--we should instead strongly suggest doing so after importing subscriptions (Comment Mail → Import/Export → Subscribe to Comments Reloaded (StCR)).

Agree, since we are no longer activating CM by default, that makes sense. Thanks!

**Comment by jaswsinc** [comment]
@raamdev writes...
> What settings were imported? That's the first thing I would wonder as a site owner installing Comment Mail for the first time who's also a long-time StCR user. We should make a list of the settings that are imported and write a KB Article that describes what gets imported, then link to that KB Article from inside this Dashboard message.

Great point. Referencing: https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/stcr.php

**Comment by jaswsinc** [comment]
Referencing new KBA: http://comment-mail.com/kb-article/stcr-options-transitioned-by-comment-mail/

**Comment by jaswsinc** [comment]
@raamdev writes...
> (note that I said enabled; if Comment Mail is Active but not enabled that shouldn't matter

Copy that.

**Comment by jaswsinc** [comment]
![](https://www.filepicker.io/api/file/DvoksOQVa015zsoRMHZQ#.png)

**Comment by jaswsinc** [comment]
![](https://www.filepicker.io/api/file/qFHKOLbGQFKSO4rQOlyY#.png)

**Comment by jaswsinc** [comment]
Updated message links to: http://comment-mail.com/kb-article/stcr-options-transitioned-by-comment-mail/

**Comment by raamdev** [comment]
@jaswsinc Do you mind tweaking that message a little?

"Keep Comment Mail, but please deactivate the StCR plugin"

change to:

"We recommend keeping Comment Mail; please deactivate the Subscribe to Comments Reloaded plugin"

Also, in the title of that message I would spell out "Subscribe to Comments Reloaded (StCR)" instead of only saying "StcR"; that title is the first thing people are going to see and seeing "StCR" might throw people off. In fact, I wouldn't use "StCR" anywhere in that message. If someone is running a non-English site (and is a non-English speaker), seeing StCR won't mean anything but seeing "Subscribe to Comments Reloaded" will.

I would also remove the SVG Comment Mail icon from that message and it just looks weird next to the `+` sign...

---

Here's the dialog with my suggested changes:

![2015-06-25_21-39-32](https://cloud.githubusercontent.com/assets/53005/8369110/dab73694-1b82-11e5-9a52-efa200c77179.png)

And the HTML that includes my changes:

```
<strong>Comment Mail™</strong>  + <strong>Subscribe to Comments Reloaded</strong> = Possible Conflict!
<strong>WARNING (ACTION REQUIRED):</strong> Running Comment Mail™ while Subscribe to Comments Reloaded is <em>also</em> an active WordPress plugin <strong>can cause problems</strong>; i.e., these two plugins do the same thing—Comment Mail being the newer of the two. We recommend keeping Comment Mail; please deactivate the Subscribe to Comments Reloaded plugin to get rid of this message.
```

**Comment by jaswsinc** [comment]
Agree. Done. Thanks! :-)

![](https://www.filepicker.io/api/file/jmKyhA2WRayKgoVvK9je#.png)
![](https://www.filepicker.io/api/file/cT11XcbSRaGFNnovAa7R#.png)
