### ISSUE TITLE
Improve instructions for Import/Export → Subscribe to Comments Reloaded (StCR)

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#98]
![2015-06-22_19-24-50](https://cloud.githubusercontent.com/assets/53005/8295879/0e5bf610-1917-11e5-8997-a66f2d35401f.png)

This panel, at present (as of v150620), feels too unfriendly. A site owner coming here would primarily see the big "Begin StCR Auto-Importation" button, which is fine, except that once the import process is done they're left wondering "what now?" (that's assuming they decided to take the risk of clicking that button at all, not really being _sure_ what it does). If the site owner then takes the time to read that entire paragraph in the blue box they'll find the tiny "click here" link that indicates what they should probably do next.

This entire panel could be greatly improved, IMO, by simply creating a few steps with headers:

![2015-06-22_19-57-39](https://cloud.githubusercontent.com/assets/53005/8296025/19f14f28-1919-11e5-9db1-c2069587eb0b.png)

```html
<h3>Step 1: Import StCR Subscriptions</h3>
<p>Click the "Begin StCR Auto-Importation" button above to start the import process. Comment Mail will import all of your existing Subscribe to Comments Reloaded comment subscriptions. Your existing StCR comment subscriptions will remain intact--nothing will be deleted or removed. Comment Mail will simply copy the subscriptions from StCR into Comment Mail's database.</p>
<p class="pmp-note pmp-info" style="font-size:90%;"><strong>Note:</strong> This process may take several minutes. Comment Mail will work through each post in your database, collecting all of the StCR subscriptions that exist (just a few at a time to prevent any script timeouts). The status bar below may refresh several times during this process. When it's complete, you should see a message that reads "<strong>Import complete!</strong>", along with a few details regarding the importation. If the importation is interrupted for any reason, you may simply click the button again and Comment Mail will resume where it left off.</p>
<h3>Step 2: Verify Subscriptions </h3>
<p>When you see a message below that says "<strong>Import Complete!</strong>", you can <a href="https://raam.org/wordpress/wp-admin/admin.php?page=comment_mail_subs" target="_blank_">click here</a> to view a list of all subscriptions; which will include any that were imported from StCR.</p>
<h3>Step 3: Activate Comment Mail</h3>
<p>Once Comment Mail has imported all of your existing Subscribe to Comments Reloaded subscriptions, you can review the rest of your Commetn Mail configuration, then deactivate the Subscribe to Comments Reloaded plugin (there's no need to delete the plugin--you can simply deactivate it for now), and then Enable Comment Mail.</p>
```

## Shouldn't this all go into a KB Article?

Normally I would say yes, however since importing existing subscription data from StCR is going to be such a common occurrence, and because the "instructions" are really not that long or complicated anyway, I'd say we should just explain things a little more right inside the plugin option panel. Having all that information right there for a site owner will make them feel a lot better about "trying" Comment Mail.

## Do we still need a 'StCR Migration' KB Article?

Yes! Definitely. The steps I added above do not replace a full-fledged KB Article. In fact, there are _so many_ more steps that we should suggest, things like configuring SMTP Server, verifying the templates look right, etc., etc.. 

---

Related: https://github.com/websharks/comment-mail/issues/80

**Comment by jaswsinc** [comment]
Agree :+1:

**Comment by jaswsinc** [comment]
All set. @raamdev TY for the copy, that helped me out! :-)

Initial screen:
![](https://www.filepicker.io/api/file/uKMrlEWMRAC4qTMcpdbQ#.png)

---

After import complete:
![](https://www.filepicker.io/api/file/YpWZ1oatQy6AsrdLOtLV#.png)

**Comment by raamdev** [comment]
@jaswsinc The blue note box in your update still includes redundant text (repeats what Step 2 describes), which I had removed in my copy above:

```
<p class="pmp-note pmp-info" style="font-size:90%;"><strong>Note:</strong> This process may take several minutes. Comment Mail will work through each post in your database, collecting all of the StCR subscriptions that exist (just a few at a time to prevent any script timeouts). The status bar below may refresh several times during this process. When it's complete, you should see a message that reads "<strong>Import complete!</strong>", along with a few details regarding the importation. If the importation is interrupted for any reason, you may simply click the button again and Comment Mail will resume where it left off.</p>
```

![2015-06-22_19-57-39](https://cloud.githubusercontent.com/assets/53005/8368658/0c3e182a-1b7b-11e5-9bed-c91eba423ba3.png)

**Comment by jaswsinc** [comment]
@raamdev writes...
> The blue note box in your update includes redundant text

Thanks for catching this! I updated it to your copy.
