### ISSUE TITLE
Fancy Double-Quotes in Template Editing Boxes?

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#99]
I noticed (as of v150620) there were fancy double-quotes in some of the template editing boxes:

![2015-06-22_20-08-32](https://cloud.githubusercontent.com/assets/53005/8296148/f6407b88-191a-11e5-8876-6186f08bd1e8.png)

### " ← normal double-quote (green arrow)

I noticed in some of the other template editing boxes, where there is HTML, normal double-quotes appear:

![2015-06-22_20-13-03](https://cloud.githubusercontent.com/assets/53005/8296167/32cb415a-191b-11e5-8233-145ff69db837.png)

---

I'm not sure if there's any harm here, but if a site owner edits the templates that include the fancy double-quotes, and then they start mixing fancy double-quotes with normal double-quotes, they may end up seeing things in their emails that don't look right (e.g., _"why does the first quote look different than the second quote?"_).

**Comment by jaswsinc** [comment]
@raamdev writes...
> I'm not sure if there's any harm here, but if a site owner edits the templates that include the fancy double-quotes, and then they start mixing fancy double-quotes with normal double-quotes, they may end up seeing things in their emails that don't look right

Thanks for the heads up.

I just reviewed this also. I'm not seeing any harm here either. The use of fancy quotes is for visual appeal only, in certain cases when they are used to encapsulate the title of the post.

I'm leaving this open for further discussion related to the potential for confusion on the part of a site owner making adjustments to these templates.

**Comment by raamdev** [comment]
@jaswsinc can we remove the fancy-quotes? If yes, is there any reason we shouldn't remove them?

**Comment by jaswsinc** [comment]
@raamdev writes...
> can we remove the fancy-quotes?

Certainly. Not a problem for me at all. My thinking is that fancy quotes would still work to encapsulate a title which may already include double quotes, but that's not that common. Anything we can use to encapsulate the title variable (which could be anything really) is fine with me.

```
“New Book title: "Together We Can"”
```

**Comment by raamdev** [comment]
> My thinking is that fancy quotes would still work to encapsulate a title which may already include double quotes

The 'proper' way to do that is by changing the inner double-quotes to single-quotes:

```
"New Book title: 'Together We Can'"
```

or a more common example:

```
His words were flustered. "Why, why would she say something like that to me? What on earth would make her say, 'I never want to see you again'?"

---

> Certainly. Not a problem for me at all.

Cool. Let's remove them then. :-)

**Comment by jaswsinc** [comment]
All set now.

**Comment by raamdev** [comment]
Confirmed. Thanks!

![2015-06-25_21-20-34](https://cloud.githubusercontent.com/assets/53005/8368963/19079036-1b80-11e5-8545-81d5459bfc70.png)
